using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators.Archetypes;

/// <summary>
/// Puts a query over several shapes on the chunk path.
/// </summary>
/// <remarks>
/// A single shape has one declaration to hang its binding off, and a combination has none, so this
/// one is driven by use: it looks for the combinations a compilation actually queries and emits a
/// binding for each. Bounded by what is written rather than by every pair that could be.
/// </remarks>
[Generator]
internal class ChunkCombinationGenerator : IIncrementalGenerator
{
    /// Bounded by the composed views that exist in the server SDK.
    private const int MaxArity = 6;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var combinations = context.SyntaxProvider
            .CreateSyntaxProvider(IsQueryOverSeveralShapes, Read)
            .Where(static combination => combination is not null)
            .Collect();

        context.RegisterSourceOutput(combinations, static (spc, found) =>
        {
            foreach (var combination in found.OfType<Combination>().Distinct())
                spc.AddSource(combination.HintName, Emit(combination));
        });
    }

    private static bool IsQueryOverSeveralShapes(SyntaxNode node, CancellationToken ct)
        => node is InvocationExpressionSyntax
        {
            Expression: MemberAccessExpressionSyntax
            {
                Name: GenericNameSyntax { Identifier.ValueText: "Query" } name
            }
        } && name.TypeArgumentList.Arguments.Count is > 1 and <= MaxArity;

    private static Combination? Read(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var name = (GenericNameSyntax)((MemberAccessExpressionSyntax)invocation.Expression).Name;
        var chunks = ChunkNames.Resolve(context.SemanticModel.Compilation);

        if (chunks is null)
            return null;

        var shapes = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

        foreach (var argument in name.TypeArgumentList.Arguments)
        {
            if (context.SemanticModel.GetSymbolInfo(argument, ct).Symbol is not INamedTypeSymbol shape
                || !HasChunkView(shape))
                return null;

            shapes.Add(shape);
        }

        return new Combination(shapes.ToImmutable(), chunks);
    }

    /// <summary>Whether the generator emitted a view for this shape in whichever assembly declared it.</summary>
    private static bool HasChunkView(INamedTypeSymbol shape)
    {
        var declared = shape.GetAttributes().Any(attribute
            => attribute.AttributeClass?.ToDisplayString() is ArchetypeNames.ArchetypeAttribute
                or ArchetypeNames.MixinAttribute);

        return declared && DeclarationModel.For(shape).SupportsChunks;
    }

    private static string Emit(Combination combination)
    {
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

        // The global namespace, because the shapes may be declared anywhere and this has to be in
        // scope wherever the query is written.
        using (writer.Braces($"public static class {combination.ClassName}"))
        {
            writer.Line($"public static {combination.Composed}.Enumerator GetEnumerator(");
            writer.Line($"    this {combination.Query} query)");
            writer.Line($"    => query.Chunks<{combination.Views}>();");
        }

        return writer.ToString();
    }

    private sealed class Combination(ImmutableArray<INamedTypeSymbol> shapes, ChunkNames chunks)
        : System.IEquatable<Combination>
    {
        public string Views { get; } = Compose(shapes, chunks);

        public string Composed { get; } = $"{chunks.ChunkQuery}<{Compose(shapes, chunks)}>";

        public string Query { get; } =
            $"{chunks.EntityQuery}<{string.Join(", ", shapes.Select(shape => shape.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))}>";

        public string ClassName { get; } =
            string.Join("_", shapes.Select(shape => shape.ToDisplayString().Replace(".", "_"))) + "_ChunkQuery";

        public string HintName => ClassName + ".g.cs";

        /// <summary>
        /// Flat rather than nested, so a loop deconstructs into as many names as it asked for
        /// instead of a head and a tail.
        /// </summary>
        private static string Compose(ImmutableArray<INamedTypeSymbol> shapes, ChunkNames chunks)
        {
            if (shapes.Length == 1)
                return ArchetypeNames.QualifiedViewOf(shapes[0]);

            var views = shapes.Select(ArchetypeNames.QualifiedViewOf);

            return $"{chunks.ChunkViews}<{string.Join(", ", views)}>";
        }

        public bool Equals(Combination? other) => other is not null && ClassName == other.ClassName;

        public override bool Equals(object? obj) => Equals(obj as Combination);

        public override int GetHashCode() => ClassName.GetHashCode();
    }
}
