using System.Collections.Generic;

namespace ReadyM.Api.Generators.Archetypes;

/// <summary>
/// The parts a mixin and an archetype share: the handle they wrap, and accessors that read through
/// the accessor class rather than the component.
/// </summary>
internal static class HandleEmitter
{
    public static void File(SourceWriter writer, DeclarationModel model)
    {
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        if (model.Namespace.Length > 0)
        {
            writer.Line($"namespace {model.Namespace};");
            writer.Line();
        }
    }

    public static void Handle(SourceWriter writer, DeclarationModel model)
    {
        writer.Line($"private readonly {ArchetypeNames.EntityHandle} _handle;");
        writer.Line();
        writer.Line($"public {model.Name}({ArchetypeNames.EntityHandle} handle) => _handle = handle;");
        writer.Line();

        using (writer.Braces($"{ArchetypeNames.EntityHandle} {ArchetypeNames.Queryable}.Handle"))
        {
            writer.Line("get => _handle;");
            writer.Line("init => _handle = value;");
        }

        writer.Line();
        writer.Line($"{ArchetypeNames.EntityHandle} {ArchetypeNames.Shape}.Handle => _handle;");
        writer.Line();
        writer.Line($"{ArchetypeNames.ComponentSet} {ArchetypeNames.Queryable}.Components => {model.QualifiedAccessors}.Components;");
    }

    /// <summary>The set an accessor class exposes: its own component plus whatever it includes.</summary>
    public static string ComponentSet(DeclarationModel model)
    {
        var sets = AccessorEmitter.Sets(model);

        return sets.Count switch
        {
            0 => $"{ArchetypeNames.ComponentSet}.Empty",
            1 => sets[0],
            _ => $"{ArchetypeNames.ComponentSet}.Combine({string.Join(", ", sets)})"
        };
    }

    /// The modifier the declaration used, which the implementing part has to repeat.
    private static string Keyword(AccessorModel accessor) => accessor.Accessibility switch
    {
        Microsoft.CodeAnalysis.Accessibility.Private => "private",
        Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
        Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
        Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
        Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
        _ => "public"
    };

    public static void Accessor(SourceWriter writer, AccessorModel accessor, string accessors, bool partial, bool replicated = false)
    {
        if (!partial && !accessor.IsExposed)
            return;

        var declaration = partial
            ? $"{Keyword(accessor)} partial {accessor.Type} {accessor.Name}"
            : $"{Keyword(accessor)} {accessor.Type} {accessor.Name}";

        if (!accessor.HasSetter)
        {
            writer.Line($"{declaration} => {accessors}.Get{accessor.Name}(_handle);");
            return;
        }

        using (writer.Braces(declaration))
        {
            writer.Line($"get => {accessors}.Get{accessor.Name}(_handle);");
            writer.Line($"set => {accessors}.Set{accessor.Name}(_handle, value);");
        }
    }

    public static void Accessors(
        SourceWriter writer,
        IReadOnlyList<AccessorModel> accessors,
        string accessorClass,
        bool partial,
        bool replicated = false)
    {
        foreach (var accessor in accessors)
        {
            writer.Line();
            Accessor(writer, accessor, accessorClass, partial, replicated);
        }
    }
}
