using System.Collections.Generic;

namespace ReadyM.Api.Generators.Archetypes;

/// <summary>
/// The parts a mixin and an archetype share: the handle they wrap, and accessors reading one component.
/// </summary>
internal static class HandleEmitter
{
    public static void File(SourceWriter writer, DeclarationModel model)
    {
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        if (model.Namespace.Length > 0)
        {
            writer.Line($"namespace {model.Namespace};");
            writer.Line();
        }
    }

    public static void Handle(SourceWriter writer, DeclarationModel model)
    {
        writer.Line($"private readonly {ArchetypeNames.EntityHandle} _handle;");
        writer.Line();
        writer.Line($"public {model.Name}({ArchetypeNames.EntityHandle} handle) => _handle = handle;");
        writer.Line();

        using (writer.Braces($"{ArchetypeNames.EntityHandle} {ArchetypeNames.Queryable}.Handle"))
        {
            writer.Line("get => _handle;");
            writer.Line("init => _handle = value;");
        }

        writer.Line();
        writer.Line($"{ArchetypeNames.ComponentSet} {ArchetypeNames.Queryable}.Components => {ComponentSet(model)};");
    }

    public static string ComponentSet(DeclarationModel model)
    {
        var components = model.RequiredComponents();

        if (components.Count == 0)
            return $"{ArchetypeNames.ComponentSet}.Empty";

        return $"{ArchetypeNames.ComponentSet}.Of<{string.Join(", ", components)}>()";
    }

    /// <summary>An accessor reading and writing one field of one component the entity always carries.</summary>
    public static void Accessor(SourceWriter writer, AccessorModel accessor, string component, bool partial)
    {
        var declaration = partial
            ? $"public partial {accessor.Type} {accessor.Name}"
            : $"public {accessor.Type} {accessor.Name}";

        var read = $"_handle.GetComponent<{component}>().{accessor.Field}";

        if (!accessor.HasSetter)
        {
            writer.Line($"{declaration} => {read};");
            return;
        }

        using (writer.Braces(declaration))
        {
            writer.Line($"get => {read};");
            writer.Line($"set => {read} = value;");
        }
    }

    public static void Accessors(
        SourceWriter writer,
        IReadOnlyList<AccessorModel> accessors,
        string component,
        bool partial)
    {
        foreach (var accessor in accessors)
        {
            writer.Line();
            Accessor(writer, accessor, component, partial);
        }
    }
}
