using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators.Archetypes;

/// <summary>
/// Gathers every registration a compilation emits into one entry point a host can call: what a shape
/// adds to an archetype, what it handles as it is created, and every service the assembly declares.
/// </summary>
/// <remarks>
/// Each registration also runs from a module initializer where the target has them, but that only
/// fires once something in the assembly is touched, and a netstandard2.0 target has none at all. A
/// single well-known type gives a loader something to call outright, before any entity exists.
/// </remarks>
[Generator]
internal class RegistrationAggregatorGenerator : IIncrementalGenerator
{
    private const string Namespace = "ReadyM.SDK.Generated";
    private const string ClassName = "ShapeRegistrations";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var archetypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            ArchetypeNames.ArchetypeAttribute,
            static (node, _) => node is StructDeclarationSyntax,
            Read);

        var mixins = context.SyntaxProvider.ForAttributeWithMetadataName(
            ArchetypeNames.MixinAttribute,
            static (node, _) => node is StructDeclarationSyntax,
            Read);

        var services = context.SyntaxProvider.ForAttributeWithMetadataName(
            ArchetypeNames.ServiceAttribute,
            static (node, _) => node is ClassDeclarationSyntax,
            ReadService);

        var all = archetypes.Collect().Combine(mixins.Collect()).Combine(services.Collect());

        context.RegisterSourceOutput(all, static (spc, found) =>
        {
            var names = found.Left.Left.Concat(found.Left.Right).Concat(found.Right)
                .SelectMany(entry => entry)
                .Distinct()
                .OrderBy(name => name, System.StringComparer.Ordinal)
                .ToList();

            if (names.Count == 0)
                return;

            spc.AddSource($"{Namespace}.{ClassName}.g.cs", Emit(names));
        });
    }

    /// <summary>The registration classes one declaration produces, by the names that emit them.</summary>
    private static ImmutableArray<string> Read(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol { ContainingType: null } symbol)
            return [];

        var model = DeclarationModel.For(symbol);
        var found = ImmutableArray.CreateBuilder<string>();
        var ns = ArchetypeNames.NamespaceOf(symbol);
        var prefix = ns.Length == 0 ? "global::" : $"global::{ns}.";

        if (model.Extends.Count > 0)
            found.Add($"{prefix}{symbol.Name}Extends");

        if (model.IndexedBy is not null)
            found.Add($"{prefix}{symbol.Name}Index");

        if (model.RegistersReplication)
            found.Add($"{prefix}{symbol.Name}Replication");

        if (NativeInitEmitter.Applies(model))
            found.Add($"{prefix}{symbol.Name}NativeInit");

        // A handler the shape declared for itself, which sits inside the shape rather than beside it.
        if (CreateHandlerEmitter.Check(model).Length == 0)
            foreach (var handler in model.CreateHandlers)
                found.Add($"{prefix}{symbol.Name}.{handler.Name}Registration");

        return found.ToImmutable();
    }

    /// <summary>The registration a service produces, unless the analyzer refuses the class.</summary>
    private static ImmutableArray<string> ReadService(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol { ContainingType: null } symbol)
            return [];

        if (Services.ServiceShape.Read(symbol).Problems.Any(problem => problem.Severity == DiagnosticSeverity.Error))
            return [];

        var ns = ArchetypeNames.NamespaceOf(symbol);
        var prefix = ns.Length == 0 ? "global::" : $"global::{ns}.";

        return [$"{prefix}{symbol.Name}.Registration"];
    }

    private static string Emit(System.Collections.Generic.IReadOnlyList<string> names)
    {
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {Namespace};");
        writer.Line();
        writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

        using (writer.Braces($"public static class {ClassName}"))
        using (writer.Braces("public static void RegisterAll()"))
            foreach (var name in names)
                writer.Line($"{name}.Register();");

        return writer.ToString();
    }
}
