namespace ReadyM.Api.Multiplayer.RPC;

/// <summary>
/// Base class for an RPC container.
/// Each class that defines RPC methods with [RpcEvent] attributes must inherit from this class.
/// </summary>
public abstract class ClientRpcHandler : RpcBase
{
    /// <summary>
    /// Number of RPC events defined in this class.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected abstract byte EventsCount { get; }
    
    /// <summary>
    /// Event code offset assigned to this RPC class.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected byte Offset { get; private set; }
    
    internal void Initialize(RpcOffsetProvider offsetProvider)
    {
        Offset = offsetProvider.GetNextOffset(EventsCount);
    }
}