using System;
using Friflo.Engine.ECS;
using ReadyM.Api.DI;
using ReadyM.Api.Helpers;
using ReadyM.Api.Multiplayer.Client;
using ReadyM.Api.Multiplayer.Serialization;

namespace ReadyM.Api.Multiplayer.RPC;

public abstract class RpcBase : IHostedService
{
    /// <summary>
    /// RPC client to use for sending RPCs. This is injected by the DI container.
    /// </summary>
    public IRpcClient RelayClient { protected get; set; } = null!;

    /// <summary>
    /// Serializer to use for serializing RPC parameters. This is injected by the DI container.
    /// </summary>
    public IRelaySerializer Serializer { protected get; set; } = null!;

    internal PendingActionScheduler<CommandBufferSynced> Scheduler { private get; set; } = null!;

    /// <summary>
    /// Initializes the RPC class, e.g. by registering RPC handlers.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected abstract void InitRpc();

    /// <summary>
    /// De-initializes the RPC class, e.g. by unregistering RPC handlers.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected abstract void DeInitRpc();

    public virtual void OnScopeStart()
    {
        InitRpc();
    }

    /// <inheritdoc />
    public virtual void Dispose()
    {
        DeInitRpc();
    }

    protected void RunOnGameThread(Action callback)
    {
        Scheduler.Schedule((_, c) => c(), callback);
    }
}