using System;
using Friflo.Engine.ECS;
using ReadyM.Api.DI;
using ReadyM.Api.Helpers;
using ReadyM.Api.Multiplayer.Client;
using ReadyM.Api.Multiplayer.Serialization;

namespace ReadyM.Api.Multiplayer.RPC;

/// <summary>
/// Base class for an RPC container.
/// Each class that defines RPC methods with [RpcEvent] attributes must inherit from this class.
/// </summary>
/// <param name="client">RPC client to use for sending RPCs. This is injected by the DI container.</param>
/// <param name="serializer">Serializer to use for serializing RPC parameters. This is injected by the DI container.</param>
public abstract class RpcClassBase(IRpcClient client, IRelaySerializer serializer) : IHostedService
{
    /// <summary>
    /// Number of RPC events defined in this class.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected abstract byte EventsCount { get; }

    /// <summary>
    /// Initializes the RPC class, e.g. by registering RPC handlers.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected abstract void InitRpc();

    /// <summary>
    /// De-initializes the RPC class, e.g. by unregistering RPC handlers.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected abstract void DeInitRpc();

    /// <summary>
    /// Event code offset assigned to this RPC class.
    /// Generated by the source generator in derived classes.
    /// </summary>
    protected byte Offset { get; private set; }

    /// <summary>
    /// RPC client to use for sending RPCs. This is injected by the DI container.
    /// </summary>
    protected IRpcClient RelayClient { get; } = client;

    /// <summary>
    /// Serializer to use for serializing RPC parameters. This is injected by the DI container.
    /// </summary>
    protected IRelaySerializer Serializer { get; } = serializer;

    private PendingActionScheduler<CommandBufferSynced> _scheduler = null!;

    internal void Initialize(RpcOffsetProvider offsetProvider, PendingActionScheduler<CommandBufferSynced> scheduler)
    {
        Offset = offsetProvider.GetNextOffset(EventsCount);
        _scheduler = scheduler;
    }

    public virtual void OnScopeStart()
    {
        InitRpc();
    }

    /// <inheritdoc />
    public virtual void Dispose()
    {
        DeInitRpc();
    }

    protected void RunOnMainThread(Action callback)
    {
        _scheduler.Schedule((_, c) => c(), callback);
    }
}