using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Archetypes;

namespace ReadyM.Api.Generators.Services;

/// Completes a <c>[Service]</c> class: the lifetime and the update a game calls, the handlers it
/// watches shapes coming and going with, and the registration that makes it one instance anything
/// can ask for.
[Generator]
internal class ServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var services = context.SyntaxProvider.ForAttributeWithMetadataName(
                ArchetypeNames.ServiceAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntax, _) => (Symbol: syntax.TargetSymbol as INamedTypeSymbol, syntax.SemanticModel.Compilation))
            .Select(static (found, ct) => Emit(found.Symbol, found.Compilation, ct));

        context.RegisterSourceOutput(services, static (spc, generated) =>
        {
            if (generated is { } source)
                spc.AddSource(source.HintName, source.Source);
        });
    }

    private static (string HintName, string Source)? Emit(
        INamedTypeSymbol? symbol,
        Compilation compilation,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (symbol is null)
            return null;

        var read = ServiceShape.Read(symbol);

        if (read.Problems.Any(problem => problem.Severity == DiagnosticSeverity.Error))
            return null;

        var name = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        var ns = ArchetypeNames.NamespaceOf(symbol);

        if (ns.Length > 0)
        {
            writer.Line($"namespace {ns};");
            writer.Line();
        }

        using (writer.Braces($"partial class {symbol.Name}{Implements(read)}"))
        {
            if (read.Update is not null)
            {
                writer.Line($"private {ArchetypeNames.Time} Time {{ get; set; }}");
                writer.Line();

                using (writer.Braces(
                           $"void {ArchetypeNames.UpdatingService}.Update(in {ArchetypeNames.Time} time)"))
                {
                    writer.Line("Time = time;");
                    writer.Line($"{ServiceShape.UpdateName}();");
                }

                writer.Line();
            }

            if (read.Hosted)
            {
                Lifetime(writer, $"void {ArchetypeNames.HostedService}.OnScopeStart()", read.Start);
                Lifetime(writer, $"void {ArchetypeNames.Disposable}.Dispose()", read.Stop);
            }

            writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

            using (writer.Braces("public static class Registration"))
            {
                // A module initializer runs this where the target has one, and the mod loader runs
                // it for every assembly it loads. Watching a shape appends, so saying it twice
                // would run the handler twice.
                writer.Line("private static bool _registered;");
                writer.Line();

                if (ExtendsEmitter.HasModuleInitializer(compilation))
                    writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");

                using (writer.Braces("public static void Register()"))
                {
                    using (writer.Braces("if (_registered)"))
                        writer.Line("return;");

                    writer.Line();
                    writer.Line("_registered = true;");
                    writer.Line();

                    if (read.Update is not null)
                        writer.Line($"{ArchetypeNames.ServiceRegistry}.Register<{name}>();");
                    else
                        writer.Line($"{ArchetypeNames.ServiceRegistry}.Hold<{name}>();");

                    foreach (var (method, shape) in read.Watching)
                        Watch(writer, name, method, shape, "ObserveCreated");

                    foreach (var (method, shape) in read.Leaving)
                        Watch(writer, name, method, shape, "ObserveDeleted");
                }
            }
        }

        return (ArchetypeNames.HintOf(symbol, "Service"), writer.ToString());
    }

    private static string Implements(ServiceShape.Service read)
    {
        var interfaces = new List<string>();

        if (read.Update is not null)
            interfaces.Add(ArchetypeNames.UpdatingService);

        if (read.Hosted)
            interfaces.Add(ArchetypeNames.HostedService);

        return interfaces.Count == 0 ? string.Empty : " : " + string.Join(", ", interfaces);
    }

    /// One end of a hosted lifetime. A service may declare only the other one, and the interface
    /// still wants both.
    private static void Lifetime(SourceWriter writer, string signature, IMethodSymbol? method)
    {
        if (method is null)
        {
            using (writer.Braces(signature))
            {
            }
        }
        else
        {
            writer.Line(signature);
            writer.Line($"    => {method.Name}();");
        }

        writer.Line();
    }

    /// The shape is what the handler is handed in to, since the component behind it never leaves the
    /// assembly that declared it. The service is resolved as the handler runs, not now: the
    /// container is still being filled.
    private static void Watch(
        SourceWriter writer,
        string service,
        IMethodSymbol method,
        INamedTypeSymbol shape,
        string watchPoint)
    {
        var name = shape.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        writer.Line();
        writer.Line($"{name}.{watchPoint}(");
        writer.Line($"    static (in {ArchetypeNames.EntityHandle} handle)");
        writer.Line($"        => {ArchetypeNames.CreateHandlers}.Services.Resolve<{service}>()");
        writer.Line($"            .{method.Name}(new {name}(handle)));");
    }
}
