using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Archetypes;

namespace ReadyM.Api.Generators.Services;

/// Completes a <c>[Service]</c> class: the lifetime and the update a game calls, the handlers it
/// watches shapes coming and going with, and the registration that makes it one instance anything
/// can ask for.
[Generator]
internal class ServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var services = context.SyntaxProvider.ForAttributeWithMetadataName(
                ArchetypeNames.ServiceAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntax, _) => (Symbol: syntax.TargetSymbol as INamedTypeSymbol, syntax.SemanticModel.Compilation))
            .Select(static (found, ct) => Emit(found.Symbol, found.Compilation, ct));

        context.RegisterSourceOutput(services, static (spc, generated) =>
        {
            if (generated is { } source)
                spc.AddSource(source.HintName, source.Source);
        });
    }

    private static (string HintName, string Source)? Emit(
        INamedTypeSymbol? symbol,
        Compilation compilation,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (symbol is null)
            return null;

        var read = ServiceShape.Read(symbol);

        if (read.Problems.Any(problem => problem.Severity == DiagnosticSeverity.Error))
            return null;

        var name = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        var ns = ArchetypeNames.NamespaceOf(symbol);

        if (ns.Length > 0)
        {
            writer.Line($"namespace {ns};");
            writer.Line();
        }

        using (writer.Braces($"partial class {symbol.Name}{Implements(read)}"))
        {
            Switch(writer, read);

            if (read.Update is not null)
            {
                writer.Line($"private {ArchetypeNames.Time} Time {{ get; set; }}");
                writer.Line();

                using (writer.Braces(
                           $"void {ArchetypeNames.UpdatingService}.Update(in {ArchetypeNames.Time} time)"))
                {
                    // A disabled service does not read the clock either, so its own Time still says
                    // when it last ran rather than how long it has been switched off.
                    using (writer.Braces("if (!Enabled)"))
                        writer.Line("return;");

                    writer.Line();
                    writer.Line("Time = time;");
                    writer.Line($"{ServiceShape.UpdateName}();");
                }

                writer.Line();
            }

            if (read.Started)
                Started(writer, read);

            if (read.Disposable)
                Lifetime(writer, $"void {ArchetypeNames.Disposable}.Dispose()", read.Stop);

            writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

            using (writer.Braces("public static class Registration"))
            {
                // A module initializer runs this where the target has one, and the mod loader runs
                // it for every assembly it loads. Watching a shape appends, so saying it twice
                // would run the handler twice.
                writer.Line("private static bool _registered;");
                writer.Line();

                if (ExtendsEmitter.HasModuleInitializer(compilation))
                    writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");

                using (writer.Braces("public static void Register()"))
                {
                    using (writer.Braces("if (_registered)"))
                        writer.Line("return;");

                    writer.Line();
                    writer.Line("_registered = true;");
                    writer.Line();

                    if (read.Update is not null)
                        writer.Line($"{ArchetypeNames.ServiceRegistry}.Register<{name}>({Order(read.Order)});");
                    else
                        writer.Line($"{ArchetypeNames.ServiceRegistry}.Hold<{name}>();");

                    foreach (var (method, shape) in read.Watching)
                        Watch(writer, name, method, shape, "ObserveCreated");

                    foreach (var (method, shape) in read.Leaving)
                        Watch(writer, name, method, shape, "ObserveDeleted");
                }
            }
        }

        return (ArchetypeNames.HintOf(symbol, "Service"), writer.ToString());
    }

    /// <summary>What the registration carries, which is nothing where the service said nothing.</summary>
    /// <remarks>
    /// Written as an array rather than a collection expression, because the mod compiling this may
    /// be on an older language version than the SDK.
    /// </remarks>
    private static string Order(ServiceShape.Ordering order)
    {
        if (order.IsDefault)
            return string.Empty;

        return $"{order.Priority}, {Types(order.Before)}, {Types(order.After)}";
    }

    private static string Types(IReadOnlyList<INamedTypeSymbol> services)
    {
        if (services.Count == 0)
            return "null";

        var named = services.Select(service
            => $"typeof({service.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})");

        return "new global::System.Type[] { " + string.Join(", ", named) + " }";
    }

    private static string Implements(ServiceShape.Service read)
    {
        // IUpdatingService is an IService, so a service that ticks says the one and means both.
        var interfaces = new List<string>
        {
            read.Update is not null ? ArchetypeNames.UpdatingService : ArchetypeNames.Service,
        };

        if (read.Started)
            interfaces.Add(ArchetypeNames.StartedService);

        if (read.Disposable)
            interfaces.Add(ArchetypeNames.Disposable);

        return " : " + string.Join(", ", interfaces);
    }

    /// The switch anything can read, and what the SDK calls once it has moved it. Enabled has no
    /// setter and the state sits in ServiceSwitch rather than here, so a service cannot switch
    /// itself behind the back of its own OnEnabled and OnDisabled: the two halves of a partial class
    /// are one class, so a field written here would be the service's to write too.
    private static void Switch(SourceWriter writer, ServiceShape.Service read)
    {
        writer.Line(
            $"private readonly {ArchetypeNames.ServiceSwitch} _switch = "
            + $"new {ArchetypeNames.ServiceSwitch}();");
        writer.Line();
        writer.Line("public bool Enabled => _switch.On;");
        writer.Line();
        writer.Line($"{ArchetypeNames.ServiceSwitch} {ArchetypeNames.Service}.Switch => _switch;");
        writer.Line();

        using (writer.Braces($"void {ArchetypeNames.Service}.Switched(bool enabled)"))
        {
            if (read.OnEnabled is not null)
                using (writer.Braces("if (enabled)"))
                    writer.Line($"{ServiceShape.OnEnabledName}();");

            if (read.OnDisabled is not null)
                using (writer.Braces(read.OnEnabled is not null ? "else" : "if (!enabled)"))
                    writer.Line($"{ServiceShape.OnDisabledName}();");
        }

        writer.Line();
    }

    /// Start and the first OnEnabled, in that order: a service is set up before it is told it runs.
    private static void Started(SourceWriter writer, ServiceShape.Service read)
    {
        writer.Line("private bool _started;");
        writer.Line();

        using (writer.Braces($"void {ArchetypeNames.StartedService}.Start()"))
        {
            // A host says its game is up once, but says it on a container, and a process may hold
            // more than one. Guarded here rather than there, so neither has to keep count.
            using (writer.Braces("if (_started)"))
                writer.Line("return;");

            writer.Line();
            writer.Line("_started = true;");

            if (read.Start is not null)
            {
                writer.Line();
                writer.Line($"{ServiceShape.StartName}();");
            }

            if (read.OnEnabled is not null)
            {
                writer.Line();

                // Something may have switched it off while the mods were loading, which is before
                // any of this runs, and then it never started ticking in the first place.
                using (writer.Braces("if (Enabled)"))
                    writer.Line($"{ServiceShape.OnEnabledName}();");
            }
        }

        writer.Line();
    }

    /// One end of a hosted lifetime. A service may declare only the other one, and the interface
    /// still wants both.
    private static void Lifetime(SourceWriter writer, string signature, IMethodSymbol? method)
    {
        if (method is null)
        {
            using (writer.Braces(signature))
            {
            }
        }
        else
        {
            writer.Line(signature);
            writer.Line($"    => {method.Name}();");
        }

        writer.Line();
    }

    /// The shape is what the handler is handed in to, since the component behind it never leaves the
    /// assembly that declared it. The service is resolved as the handler runs, not now: the
    /// container is still being filled, and the switch is read then for the same reason.
    private static void Watch(
        SourceWriter writer,
        string service,
        IMethodSymbol method,
        INamedTypeSymbol shape,
        string watchPoint)
    {
        var name = shape.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        writer.Line();
        writer.Line($"{name}.{watchPoint}(static (in {ArchetypeNames.EntityHandle} handle) =>");
        writer.Line("{");
        writer.Line($"    var service = {ArchetypeNames.CreateHandlers}.Services.Resolve<{service}>();");
        writer.Line();

        // The watch itself stays, since a service can be switched back on and taking it off and
        // putting it back would move the handler to the end of the list every time.
        writer.Line("    if (!service.Enabled)");
        writer.Line("        return;");
        writer.Line();
        writer.Line($"    service.{method.Name}(new {name}(handle));");
        writer.Line("});");
    }
}
