<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ReadyM.SDK\ReadyM.SDK.csproj"/>
        <ProjectReference Include="..\ReadyM.Api.Multiplayer\ReadyM.Api.Multiplayer.csproj"/>
        <ProjectReference Include="..\ReadyM.Relay.Server.Sdk\ReadyM.Relay.Server.Sdk.csproj"/>
        <ProjectReference Include="..\ReadyM.SDK.Server\ReadyM.SDK.Server.csproj"/>
        <ProjectReference Include="..\ReadyM.SDK.Chunks\ReadyM.SDK.Chunks.csproj"/>
    </ItemGroup>

</Project>
