<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>13.0</LangVersion>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;NoDisconnect;Testing</Configurations>
        <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Friflo.Json.Fliox.Annotation" Version="1.0.4" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Friflo.Engine.ECS\src\ECS\Friflo.Engine.ECS.csproj" />
        <ProjectReference Include="..\ReadyM.Api\ReadyM.Api.csproj" />
        <ProjectReference Include="..\ReadyM.Api.Generators\ReadyM.Api.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
