<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>13.0</LangVersion>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;NoDisconnect;Testing</Configurations>
        <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(IntermediateOutputPath)\generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
        <Compile Include="$(CompilerGeneratedFilesOutputPath)/**/*.cs" Condition="'$(TargetFramework)' == 'net9.0' and '$(DesignTimeBuild)' == 'true' and '$(BuildingInsideRider)' == 'true'" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Friflo.Engine.ECS\src\ECS\Friflo.Engine.ECS.csproj" />
        <ProjectReference Include="..\ReadyM.Api\ReadyM.Api.csproj" />
        <ProjectReference Include="..\ReadyM.Api.Generators\ReadyM.Api.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
