<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;NoDisconnect;Testing</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ReadyM.Api\ReadyM.Api.csproj" />
      <ProjectReference Include="..\ReadyM.Relay.Client\ReadyM.Relay.Client.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    </ItemGroup>

</Project>
