using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("ReadyM.Sdk.Common")]
[assembly: InternalsVisibleTo("ReadyM.Api.Tests")]
[assembly: InternalsVisibleTo("ReadyM.Api.Multiplayer")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Client")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server.PluginHost")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server.Sdk")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server.Wukong")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Server.Oblivion")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Web")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Tests")]
[assembly: InternalsVisibleTo("ReadyM.Wukong.Common")]
[assembly: InternalsVisibleTo("WukongMp.Api")]
[assembly: InternalsVisibleTo("OblivionMpCSharpMod")]
[assembly: InternalsVisibleTo("WukongMp.Sdk")]
[assembly: InternalsVisibleTo("OblivionMp.Sdk")]
[assembly: InternalsVisibleTo("WukongMp.Tests")]
[assembly: InternalsVisibleTo("ReadyM.Relay.Common.Oblivion")] // TODO: Change name to ReadyM.Oblivion.Common