<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <Configurations>Debug;Release;NoDisconnect;Testing;DebugSelfHosted</Configurations>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DryIoc.dll" Version="5.4.3" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
        <PackageReference Include="Nullable" Version="1.3.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Superpower" Version="3.1.0" />
        <PackageReference Include="System.Text.Encodings.Web" Version="10.0.8" />
        <PackageReference Include="System.Text.Json" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteNetLib\LiteNetLib\LiteNetLib.csproj" />
        <ProjectReference Include="..\Friflo.Engine.ECS\src\ECS\Friflo.Engine.ECS.csproj" />
        <ProjectReference Include="..\Friflo.Engine.ECS\src\ECS.Boost\Friflo.Engine.ECS.Boost.csproj" />
        <ProjectReference Include="..\YooniCSharp\Native\Container\Yooni.Native.Container.csproj" />
        <ProjectReference Include="..\YooniCSharp\Native\Serialization\Yooni.Native.Serialization.csproj" />
        <ProjectReference Include="..\ReadyM.Api.Generators\ReadyM.Api.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
