<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Friflo.Engine.ECS" Version="3.4.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ReadyM.Relay.Common\ReadyM.Relay.Common.csproj"/>
        <ProjectReference Include="..\ReadyM.Relay.Common.Generators\ReadyM.Relay.Common.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Wrappers\" />
    </ItemGroup>

</Project>
