<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;NoDisconnect</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../LowLevel/Yooni.Native.LowLevel.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NUnit" Version="3.13.2" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Tests/**/*.cs" />
        <None Remove="Tests/**" />
        <Content Remove="Tests/**" />
        <EmbeddedResource Remove="Tests/**" />
    </ItemGroup>
</Project>
