using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Archetypes;

namespace ReadyM.Api.Generators.Systems;

/// Completes a <c>[System]</c> class: the update a game calls, and the registration that makes the
/// class a singleton anything else can ask for.
[Generator]
internal class SystemGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var systems = context.SyntaxProvider.ForAttributeWithMetadataName(
                ArchetypeNames.SystemAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntax, _) => (Symbol: syntax.TargetSymbol as INamedTypeSymbol, syntax.SemanticModel.Compilation))
            .Select(static (found, ct) => Emit(found.Symbol, found.Compilation, ct));

        context.RegisterSourceOutput(systems, static (spc, generated) =>
        {
            if (generated is { } source)
                spc.AddSource(source.HintName, source.Source);
        });
    }

    private static (string HintName, string Source)? Emit(
        INamedTypeSymbol? symbol,
        Compilation compilation,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (symbol is null || SystemShape.Read(symbol).Update is not { } update)
            return null;

        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        var ns = ArchetypeNames.NamespaceOf(symbol);

        if (ns.Length > 0)
        {
            writer.Line($"namespace {ns};");
            writer.Line();
        }

        using (writer.Braces($"partial class {symbol.Name} : {ArchetypeNames.ModSystem}"))
        {
            var tick = update.Parameters.Length == 1 ? "tick" : string.Empty;

            writer.Line($"void {ArchetypeNames.ModSystem}.Update(in {ArchetypeNames.Tick} tick)");
            writer.Line($"    => {SystemShape.UpdateName}({tick});");
            writer.Line();
            writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

            using (writer.Braces("public static class Registration"))
            {
                if (ExtendsEmitter.HasModuleInitializer(compilation))
                    writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");

                writer.Line("public static void Register()");
                writer.Line($"    => {ArchetypeNames.SystemRegistry}.Register<"
                            + $"{symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();");
            }
        }

        return (ArchetypeNames.HintOf(symbol, "System"), writer.ToString());
    }
}
