using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public class ClientRpcEventGenerator : IIncrementalGenerator
{
    private const string ContextTypeName = "IRelayClientNetworkThreadContext";
    private const string PlayerIdTypeName = "PlayerId";
    private const string ContextParameterName = "__context";
    private const string SenderParameterName = "__sender";
    private const string EventCodeTypeName = "RelayMessageCode";
    private const string EventCodeParameterName = "__eventCode";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rpcMethods = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(m => m is not null)
            .Collect();

        context.RegisterSourceOutput(rpcMethods, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is MethodDeclarationSyntax method &&
        method.AttributeLists.Count > 0;

    private static RpcMethodInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not MethodDeclarationSyntax methodSyntax)
            return null;

        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol;

        // Check for [RpcEvent] attribute via semantic model
        var rpcAttr = methodSymbol?.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is "RpcEventAttribute" or "RpcEvent");

        if (rpcAttr == null)
            return null;

        var attributeSyntax = rpcAttr
            .ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        var args = attributeSyntax!.ArgumentList!.Arguments;

        var constants = args.Select(arg => context.SemanticModel.GetOperation(arg.Expression)?.ConstantValue.Value)
            .Where(val => val is not null)
            .Select(x => x!.ToString())
            .ToArray();

        return new RpcMethodInfo(methodSymbol!, constants);
    }

    private static void GenerateSources(SourceProductionContext context, ImmutableArray<RpcMethodInfo?> rawMethods)
    {
        var methods = rawMethods
            .Where(m => m is not null)
            .Select(m => m!)
            .OrderBy(m => m.Symbol.ToDisplayString()) // Deterministic order
            .ToList();

        var groupsByClass = methods.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default);

        var eventCodeByte = 0;

        foreach (var group in groupsByClass)
        {
            var minEventCode = eventCodeByte;
            var maxEventCode = eventCodeByte;
            
            var classSymbol = group.Key;
            var ns = classSymbol!.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var fullClassName = classSymbol.ToDisplayString();

            var sb = new StringBuilder($$"""
                                         // <auto-generated/>
                                         using System;
                                         using LiteNetLib;
                                         using LiteNetLib.Utils;
                                         using ReadyM.Api.Multiplayer;
                                         using ReadyM.Api.Multiplayer.Protocol;
                                         using ReadyM.Api.Multiplayer.Protocol.Enums;
                                         using ReadyM.Api.Multiplayer.Client;
                                         using ReadyM.Api.Multiplayer.Extensions;

                                         namespace {{ns}};

                                         public partial class {{className}}
                                         {
                                         """);

            var dispatchCases = new StringBuilder();

            foreach (var method in group)
            {
                if (eventCodeByte > byte.MaxValue)
                {
                    sb.AppendLine("""#error "Too many RPC events; limit is 256." """);
                    break;
                }

                var methodSymbol = method.Symbol;
                var methodName = methodSymbol.Name;

                var parameters = methodSymbol.Parameters;

                var valid = true;
                int? contextIndex = null;
                int? senderIndex = null;
                int? eventCodeIndex = null;
                List<(ITypeSymbol? Type, bool IsSerializablePrimitive, bool IsNetSerializable)> paramTypes = [];

                for (var i = 0; i < parameters.Length; i++)
                {
                    var param = parameters[i];
                    if (param.Name == ContextParameterName)
                    {
                        if (param.Type.Name != ContextTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // IRelayClientNetworkThreadContext __context
                        contextIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Name == SenderParameterName)
                    {
                        if (param.Type.Name != PlayerIdTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // PlayerId __sender
                        senderIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Name == EventCodeParameterName)
                    {
                        if (param.Type.Name != EventCodeTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // RelayMessageCode __eventCode
                        eventCodeIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (SerializationHelper.IsINetSerializable(param.Type))
                    {
                        // T payload
                        var isNetSerializable = true;
                        var payloadType = param.Type;
                        paramTypes.Add((payloadType, false, isNetSerializable));
                    }
                    else if (SerializationHelper.IsSerializablePrimitive(param.Type.SpecialType))
                    {
                        // int, string, etc.
                        var isSerializablePrimitive = true;
                        var payloadType = param.Type;
                        paramTypes.Add((payloadType, isSerializablePrimitive, false));
                    }
                    else
                    {
                        // T payload
                        var payloadType = param.Type; // T must be registered in RelayClient
                        paramTypes.Add((payloadType, false, false));
                    }
                }

                if (!valid)
                {
                    sb.AppendLine($"""#error "Invalid client RPC handler '{methodName}'. Supported signatures: void OnX([IRelayClientNetworkThreadContext __context], [PlayerId __sender], [RelayMessageCode __eventCode], [T arg...]) where T is either INetSerializable, or primitive" """);
                    continue;
                }

                var shortName = methodName.StartsWith("On") ? methodName.Substring(2) : methodName;

                var sendMethod = $"Send{shortName}";
                var sendParamList = new StringBuilder();
                
                var payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i == senderIndex)
                        continue;

                    if (i == eventCodeIndex)
                        continue;

                    if (i == contextIndex)
                        continue;

                    if (payloadCount > 0)
                        sendParamList.Append(", ");

                    var payloadType = paramTypes[i].Type;
                    sendParamList.Append(payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    sendParamList.Append($" payload{payloadCount}");
                    payloadCount++;
                }
                
                var relayMode = method.AttributeParams.FirstOrDefault(); // enum

                if (relayMode is null)
                {
                    sb.AppendLine($"""#warning "RelayMode must be specified in RpcEvent attribute for method '{methodName}'" """);
                    relayMode = "0"; // default
                }

                if (relayMode == "4" && !paramTypes.First(x => x.Type != null).Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Contains("NetworkId"))
                {
                    sb.AppendLine($"""#error "RelayMode.EntityOwner requires the first parameter to be NetworkId in method '{methodName}'" """);
                }

                sb.AppendLine($$"""
                                    public void {{sendMethod}}({{sendParamList}})
                                    {
                                        if (!RelayClient.PlayerId.HasValue)
                                            return;
                                        
                                        var message = RelayMessage.ByRelayMode((RelayMessageCode){{eventCodeByte}}, RelayClient.PlayerId.Value, (RelayMode){{relayMode}}, DeliveryMethod.ReliableOrdered);
                                        var writer = message.Writer;
                                """);

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    var (_, isSerializablePrimitive, isNetSerializable) = paramTypes[i];

                    if (i == senderIndex)
                        continue;

                    if (i == eventCodeIndex)
                        continue;

                    if (i == contextIndex)
                        continue;

                    if (isSerializablePrimitive)
                    {
                        sb.AppendLine($"        writer.Put(payload{payloadCount});");
                    }
                    else if (isNetSerializable)
                    {
                        sb.AppendLine($"        payload{payloadCount}.Serialize(writer);");
                    }
                    else
                    {
                        sb.AppendLine($"        Serializer.SerializeObject(writer, payload{payloadCount});");
                    }
                    
                    payloadCount++;
                }
                

                sb.AppendLine("""
                                      RelayClient.SendMessage(message);
                                  }

                              """);

                dispatchCases.AppendLine($"            case {eventCodeByte}:\n            {{");

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    var (payloadType, isSerializablePrimitive, isNetSerializable) = paramTypes[i];

                    if (i == contextIndex || i == senderIndex || i == eventCodeIndex)
                        continue;
                    
                    if (isSerializablePrimitive)
                    {
                        var getMethod = SerializationHelper.GetDeserializationMethod(payloadType!.SpecialType);
                        dispatchCases.AppendLine($"                var payload{payloadCount} = reader.{getMethod}();");
                    }
                    else if (isNetSerializable)
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = new {payloadType}();");
                        dispatchCases.AppendLine($"                payload{payloadCount}.Deserialize(reader);");
                    }
                    else
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = Serializer.DeserializeObject<{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(reader);");
                    }

                    payloadCount++;
                }

                dispatchCases.Append("                ");
                dispatchCases.Append(methodName);
                dispatchCases.Append('(');

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i > 0)
                        dispatchCases.Append(", ");

                    if (i == senderIndex)
                    {
                        dispatchCases.Append("header.Sender");
                        continue;
                    }

                    if (i == eventCodeIndex)
                    {
                        dispatchCases.Append("header.EventCode");
                        continue;
                    }

                    if (i == contextIndex)
                    {
                        dispatchCases.Append("context");
                        continue;
                    }
                    
                    dispatchCases.Append($"payload{payloadCount}");
                    payloadCount++;
                }

                dispatchCases.AppendLine(");");
                dispatchCases.AppendLine("                break;");
                dispatchCases.AppendLine("            }");

                maxEventCode = eventCodeByte;
                eventCodeByte++;
            }

            // Emit OnCustomEvent override
            sb.AppendLine($$"""
                                protected void OnCustomRpcMessageHandler(IRelayClientNetworkThreadContext context, CustomRelayEventHeader header, NetDataReader reader)
                                {
                                    switch ((byte)header.EventCode)
                                    {
                            {{dispatchCases}}
                                        default:
                                            throw new InvalidOperationException($"Unknown event code: {header.EventCode}");
                                    }
                                }
                                    
                                protected void InitRpc()
                                {
                                    RelayClient.AddClientRpcMessageHandler((RelayMessageCode){{minEventCode}}, (RelayMessageCode){{maxEventCode}}, OnCustomRpcMessageHandler);
                                }
                                    
                                protected void DeInitRpc()
                                {
                                    RelayClient.RemoveClientRpcMessageHandler((RelayMessageCode){{minEventCode}}, (RelayMessageCode){{maxEventCode}}, OnCustomRpcMessageHandler);
                                }
                            """);

            sb.AppendLine("}");

            var hintName = $"{fullClassName.Replace('.', '_')}_RpcEvents.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }

    private sealed class RpcMethodInfo(IMethodSymbol symbol, string[] attr)
    {
        public IMethodSymbol Symbol { get; } = symbol;
        public string[] AttributeParams { get; } = attr;
    }
}