using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public sealed class DeriveCppNativeComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);
        context.RegisterSourceOutput(
            codeProvider,
            static (spc, result) => spc.AddSource(result.Name + ".g.cpp", result.Code));
    }

    private static bool Predicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        if (cancellationToken.IsCancellationRequested)
            return false;

        var structDecl = syntaxNode as StructDeclarationSyntax;
        if (structDecl == null || structDecl.AttributeLists.Count == 0)
            return false;

        var attributes = structDecl.AttributeLists.SelectMany(static x => x.Attributes).ToList();
        return attributes.Any(x => x.Name is IdentifierNameSyntax { Identifier.Text: "DeriveINetworkedComponent" }) &&
               attributes.Any(x => x.Name is IdentifierNameSyntax { Identifier.Text: "NativeComponent" });
    }

    private static (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return (string.Empty, string.Empty);

        var symbol = DeriveUtils.GetAttributedSymbol(context, ct);
        var targetModel = DeriveComponentUtils.GetTargetModel(symbol);
        var code = GenerateCppFragment(targetModel);
        var genName = DeriveUtils.GetGeneratedFileName(symbol);

        return (genName, code);
    }

    private static string GenerateCppFragment(DeriveTargetModel model)
    {
        var info = model.SourceTarget;
        var emitDirtyMask = info.EmitDirtyMask;
        var mask = model.MaskInfo;
        var members = model.Members;
        
        if (info == null)
            throw new ArgumentNullException(nameof(info));
        if (mask == null)
            throw new ArgumentNullException(nameof(mask));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        var sb = new StringBuilder();

        sb.AppendLine("#if GENERATED_CPP_FRAGMENT");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        foreach (var error in DeriveComponentUtils.GetUserInputErrors(info, mask, members, emitDirtyMask, forCpp: true))
        {
            sb.AppendLine("#error " + error);
        }

        if (sb[sb.Length - 1] != '\n')
            sb.AppendLine();

        foreach (var member in members)
        {
            EmitCppAccessor(sb, mask, member);
        }

        sb.AppendLine("private:");

        if (emitDirtyMask)
        {
            sb.AppendLine("    " + mask.CppType + " _dirtyMask = 0;");
        }
        else
        {
            sb.AppendLine("    " + mask.CppType + " _dirtyMask = 0; // NOTE: Respecting the user-defined dirty mask size.");
        }

        sb.AppendLine();

        foreach (var member in members)
        {
            var type = member.Model.SourceMember.Type;
            if (type == null)
                throw new InvalidOperationException("Member type unexpectedly null.");

            var cppType = GetCppTypeName(member);
            var defaultValue = member is { IsCppSupported: true, CppSupport: not null }
                ? GetCppDefaultValue(member)
                : type.IsReferenceType ? "nullptr" : "{}";

            sb.AppendLine("    " + cppType + " " + member.Model.SourceMember.Name + " = " + defaultValue + ";");
        }

        sb.AppendLine();
        sb.AppendLine("#endif");

        return sb.ToString();
    }

    private static void EmitCppAccessor(
        StringBuilder sb,
        DeriveMaskInfo mask,
        DeriveMemberModelWithSupport member)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (mask == null)
            throw new ArgumentNullException(nameof(mask));
        if (member == null)
            throw new ArgumentNullException(nameof(member));

        var type = member.Model.SourceMember.Type;
        if (type == null)
            throw new InvalidOperationException("Member type unexpectedly null.");

        var cppType = GetCppTypeName(member);
        var propertyName = member.Model.GeneratedPropertyName;
        var fieldName = member.Model.SourceMember.Name;

        sb.AppendLine("public:");
        sb.AppendLine("    " + cppType + " " + propertyName + "() const");
        sb.AppendLine("    {");
        sb.AppendLine("        return " + fieldName + ";");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (!member.Model.SourceMember.ReadOnly)
        {
            sb.AppendLine("    void Set" + propertyName + "(" + cppType + " value)");
            sb.AppendLine("    {");

            var condition = BuildCppSetterCondition(member);
            sb.AppendLine("        if (" + condition + ")");
            sb.AppendLine("        {");
            sb.AppendLine("            " + fieldName + " = value;");
            sb.AppendLine("            _dirtyMask |= static_cast<" + mask.CppType + ">(1) << " + member.Model.Index + ";");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }
    
    internal static string GetCppTypeName(DeriveMemberModelWithSupport member)
    {
        if (member.CppSupport == null)
            throw new InvalidOperationException($"No C++ support registered for '{member.Model.SourceMember.Type.ToDisplayString()}'.");

        return member.CppSupport.GetCppTypeName(member.Model.SourceMember.Type);
    }

    internal static string GetCppDefaultValue(DeriveMemberModelWithSupport member)
    {
        if (member.CppSupport == null)
            throw new InvalidOperationException($"No C++ support registered for '{member.Model.SourceMember.Type.ToDisplayString()}'.");

        return member.CppSupport.GetCppDefaultValue(member.Model.SourceMember.Type);
    }

    internal static string BuildCppSetterCondition(DeriveMemberModelWithSupport member)
    {
        if (member.CppSupport == null)
            return "true";

        return member.CppSupport.BuildSetterCondition(member.Model);
    }
}