using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Derive.Cpp;
using ReadyM.Api.Generators.Derive.Cpp.FieldSupport;
using static ReadyM.Api.Generators.DeriveCppUtils;

namespace ReadyM.Api.Generators;

[Generator]
public sealed class DeriveCppNativeComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);
        context.RegisterSourceOutput(
            codeProvider,
            static (spc, result) => spc.AddSource(result.Name + ".g.cpp", result.Code));
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        if (cancellationToken.IsCancellationRequested)
            return false;

        var structDecl = syntaxNode as StructDeclarationSyntax;
        if (structDecl == null || structDecl.AttributeLists.Count == 0)
            return false;

        var attributes = structDecl.AttributeLists.SelectMany(static x => x.Attributes).ToList();
        return attributes.Any(x => x.Name is IdentifierNameSyntax { Identifier.Text: "NativeComponent" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return (string.Empty, string.Empty);

        var symbol = DeriveUtils.GetAttributedSymbol(context, ct);
        var targetModel = DeriveComponentUtils.GetTargetModel(symbol, context);
        var code = GenerateCppFragment(targetModel);
        var genName = DeriveUtils.GetGeneratedFileName(symbol);

        return (genName, code);
    }

    private string GenerateCppFragment(DeriveTargetModel model)
    {
        var info = model.SourceTarget;
        var members = model.Members;
        var maskInfo = model.MaskInfo;

        if (maskInfo != null)
        {
            if (maskInfo.Bits < members.Count)
            {
                if (model.SourceTarget.EmitDirtyMask)
                {
                    maskInfo.AddError(
                        $"Too many synced fields in `{model.SourceTarget.Name}` " +
                        $"to fit in a dirty mask. Maximum supported is {maskInfo.Bits.ToString(CultureInfo.InvariantCulture)}" +
                        $", but {members.Count.ToString(CultureInfo.InvariantCulture)} were found.");
                }
                else
                {
                    maskInfo.AddError(
                        $"Too many synced members in `{model.SourceTarget.Name}` " +
                        $"to fit in the user-supplied _dirtyMask. Maximum supported is {maskInfo.Bits.ToString(CultureInfo.InvariantCulture)}" +
                        $", but {members.Count.ToString(CultureInfo.InvariantCulture)} were found.");
                }
            }
        }
        
        foreach (var member in members)
        {
            if (!HasGetEmitFieldSupportImpl(member, false))
            {
                member.SourceMember.AddError($"Unsupported type '{member.SourceMember.Type.ToDisplayString()}' for networked member '{member.SourceMember.Name}'.");
            }
        }
        
        var sb = new StringBuilder();
        var moduleState = new CppModuleState();

        sb.AppendLine("""
// <auto-generated/>
#if GENERATED_CPP_FRAGMENT

""");

        if (info.HasErrors)
        {
            foreach (var error in info.Errors)
            {
                sb.AppendLine($"""
                                   #error {error}
                               """);
            }

            sb.AppendLine();
        }

        sb.AppendLine("""
public:
""");

        foreach (var member in members)
        {
            EmitAccessMethods(sb, member, model, moduleState);
        }

        EmitDirtyMaskAccessMethods(sb, model);
        
        sb.AppendLine("""
private:
""");

        EmitDirtyMask(sb, model);

        foreach (var member in members)
        {
            EmitBackingField(sb, member, model);
        }

        sb.AppendLine("""

#endif
""");

        return sb.ToString();
    }
    
    private void EmitAccessMethods(
        StringBuilder sb,
        DeriveMemberModel member,
        DeriveTargetModel model,
        CppModuleState moduleState)
    {
        EmitGetter(sb, member, model, moduleState);
        sb.AppendLine();

        if (!member.SourceMember.ReadOnly)
        {
            EmitSetter(sb, member, model, moduleState);
            sb.AppendLine();
        }
    }
    
    private void EmitGetter(StringBuilder sb, DeriveMemberModel member, DeriveTargetModel model, CppModuleState moduleState)
    {
        var impl = GetEmitFieldSupportImpl(member, true);
        var context = GetEmitFieldSupportContext(sb, member, model, moduleState);
        
        context.State.ResetIndent("    ");
        impl.EmitGetterMethod(member.SourceMember.Type, context);
    }
    
    private void EmitSetter(StringBuilder sb, DeriveMemberModel member, DeriveTargetModel model, CppModuleState moduleState)
    {
        var impl = GetEmitFieldSupportImpl(member, true);
        var context = GetEmitFieldSupportContext(sb, member, model, moduleState);
        
        context.State.ResetIndent("    ");
        impl.EmitSetterMethod(member.SourceMember.Type, context);
    }

    private void EmitDirtyMaskAccessMethods(StringBuilder sb, DeriveTargetModel model)
    {
        if (model.MaskInfo == null)
            return;
        
        sb.AppendLine("""
public:
    bool IsDirty()
    {
        return _dirtyMask != 0;
    }

""");
    }

    private void EmitDirtyMask(StringBuilder sb, DeriveTargetModel model)
    {
        var maskInfo = model.MaskInfo;
        if (maskInfo == null)
            return;
        
        if (model.SourceTarget.EmitDirtyMask)
        {
            sb.AppendLine($"""
    {CppTypeName(maskInfo.Type)} _dirtyMask = 0;

""");
        }
        else
        {
            sb.AppendLine($"""
    {CppTypeName(maskInfo.Type)} _dirtyMask = 0; // NOTE: Respecting the user-defined dirty mask size.

""");
        }
    }

    private void EmitBackingField(StringBuilder sb, DeriveMemberModel member, DeriveTargetModel model)
    {
        if (member.SourceMember.HasErrors)
        {
            foreach (var error in member.SourceMember.Errors)
            {
                sb.AppendLine($"""
    #error {error}
""");
            }
        }
        
        sb.AppendLine($"""
    {CppTypeName(member.SourceMember.Type)} {member.SourceMember.Name} = {GetCppDefaultValue(member.SourceMember.Type)};
""");
    }
    
    private static bool HasGetEmitFieldSupportImpl(DeriveMemberModel member, bool fallback)
        => CppFieldSupportRegistry.FieldTypeSupportVisitor.TryGetImpl(member.SourceMember.Type, fallback, out _);

    private static ICppFieldTypeSupportImpl GetEmitFieldSupportImpl(DeriveMemberModel member, bool fallback)
        => CppFieldSupportRegistry.FieldTypeSupportVisitor.GetImpl(member.SourceMember.Type, fallback);
    
    private static CppEmitFieldSupportContext GetEmitFieldSupportContext(StringBuilder sb, DeriveMemberModel member, DeriveTargetModel model, CppModuleState moduleState)
        => CppFieldSupportRegistry.CreateEmitFieldSupportContext(sb, member.GeneratedPropertyName, member.SourceMember.Name, member.SourceMember.Type, model.MaskInfo.Type, member.Index, moduleState);
}