using System;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public sealed class DeriveINetworkedComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(
            codeProvider,
            static (spc, nameAndContent) => spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code));
    }

    private static bool Predicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        if (cancellationToken.IsCancellationRequested)
            return false;

        if (syntaxNode is not StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl)
            return false;

        foreach (var attributeList in structDecl.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (attribute.Name is IdentifierNameSyntax { Identifier.Text: "DeriveINetworkedComponent" })
                    return true;
            }
        }

        return false;
    }

    private static (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (cancellationToken.IsCancellationRequested)
            return (string.Empty, string.Empty);

        var node = context.Node;
        var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
        var symbol = model.GetDeclaredSymbol(node, cancellationToken) as INamedTypeSymbol;
        if (symbol == null)
            throw new InvalidOperationException("Expected an INamedTypeSymbol for the attributed struct.");

        var mode = AttributeUtils.GetAttribute<byte>(
            symbol,
            "DeriveINetworkedComponentAttribute",
            "mode",
            (1 << 0) | (1 << 2));

        var emitDirtyMask = AttributeUtils.GetAttribute(
            symbol,
            "DeriveINetworkedComponentAttribute",
            "emitDirtyMask",
            true);

        var mapFields = (mode & (1 << 0)) != 0;
        var mapProperties = (mode & (1 << 1)) != 0;
        var mapPrivate = (mode & (1 << 2)) != 0;
        var mapPublic = (mode & (1 << 3)) != 0;
        var mapInternal = (mode & (1 << 4)) != 0;

        var generationModel = DeriveComponentUtils.CreateGenerationModel(
            symbol,
            mapFields: mapFields,
            mapProperties: mapProperties,
            mapPrivate: mapPrivate,
            mapPublic: mapPublic,
            mapInternal: mapInternal,
            emitDirtyMask: emitDirtyMask);

        var source = GenerateNetworkedComponent(generationModel);
        var genName = DeriveComponentUtils.GetGeneratedFileName(symbol);
        
        return (genName, source);
    }

    private static string GenerateNetworkedComponent(DeriveTargetGenerationModel model)
    {
        if (model == null)
            throw new ArgumentNullException(nameof(model));

        var info = model.TargetInfo;
        var mask = model.Mask;
        var members = model.Members;

        var sb = new StringBuilder($@"// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using LiteNetLib.Utils;
using ReadyM.Api.Generators;
using ReadyM.Api.Multiplayer;
using ReadyM.Api.Multiplayer.Extensions;
using ReadyM.Api.Multiplayer.ECS.Components;
using ReadyM.Relay.Common;

namespace {info.Namespace}
{{
    public partial struct {info.Name} : INetworkedComponent
    {{
");

        foreach (var error in DeriveComponentUtils.GetUserInputErrors(model))
        {
            sb.AppendLine($"        #error {error}");
        }

        if (model.EmitDirtyMask)
        {
            sb.AppendLine($"        private {mask.CSharpType} _dirtyMask;");
            sb.AppendLine();
        }

        foreach (var member in members)
        {
            EmitProperty(sb, mask.CSharpType, member);
        }

        EmitSerialize(sb, members);
        EmitDeserialize(sb, mask.CSharpType, members);
        EmitWriteDelta(sb, mask.CSharpType, members);
        EmitReadDelta(sb, mask.CSharpType, mask.ReadMethod, members);
        EmitSkipDelta(sb, mask.CSharpType, mask.ReadMethod, members);

        sb.AppendLine("        public void ClearDirty() => _dirtyMask = 0;");
        sb.AppendLine("        public bool IsDirty => _dirtyMask != 0;");
        sb.AppendLine("    }");
        sb.AppendLine(@"
}

#nullable disable
");

        return sb.ToString();
    }

    private static void EmitProperty(
        StringBuilder sb,
        string maskType,
        DeriveMemberGenerationModel member)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (member == null)
            throw new ArgumentNullException(nameof(member));

        var field = member.Member;
        var type = field.Type.ToDisplayString();
        if (string.IsNullOrEmpty(type))
            throw new InvalidOperationException("Member type name unexpectedly null or empty.");

        var fieldName = field.Name;
        var propertyName = member.GeneratedPropertyName;

        if (field.ReadOnly)
        {
            sb.AppendLine($"        public readonly {type} {propertyName}");
            sb.AppendLine($"            => {fieldName};");
            return;
        }

        sb.AppendLine($"        public {type} {propertyName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            get => {fieldName};");
        sb.AppendLine($"            set {{ {BuildSetterBody(maskType, member)} }}");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildSetterBody(string maskType, DeriveMemberGenerationModel member)
    {
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (member == null)
            throw new ArgumentNullException(nameof(member));

        var field = member.Member;
        var fieldName = field.Name;
        var type = field.Type ?? throw new InvalidOperationException("Member type unexpectedly null.");
        var dirtySet = $"{fieldName} = value; _dirtyMask |= ({maskType})1 << {member.Index};";

        if (!member.IsSupported)
            return dirtySet;

        if (type.SpecialType == SpecialType.System_Single)
            return $"if (Math.Abs({fieldName} - value) > {DeriveComponentUtils.FloatComparisonEpsilon}) {{ {dirtySet} }}";

        if (type.SpecialType == SpecialType.System_Double)
            return $"if (Math.Abs({fieldName} - value) > {DeriveComponentUtils.DoubleComparisonEpsilon}) {{ {dirtySet} }}";

        if (type.Name == "Vector3")
            return $"if (Vector3.DistanceSquared({fieldName}, value) > {DeriveComponentUtils.VectorComparisonEpsilon}) {{ {dirtySet} }}";

        if (type.Name == "Vector2")
            return $"if (Vector2.DistanceSquared({fieldName}, value) > {DeriveComponentUtils.VectorComparisonEpsilon}) {{ {dirtySet} }}";

        if (type.Name == "Vector4")
            return $"if (Vector4.DistanceSquared({fieldName}, value) > {DeriveComponentUtils.VectorComparisonEpsilon}) {{ {dirtySet} }}";

        if (member.IsDeltaEquatable)
        {
            if (type.IsValueType)
                return $"if (!{fieldName}.DeltaEquals(value, {DeriveComponentUtils.VectorComparisonEpsilon})) {{ {dirtySet} }}";

            return $"if (!({fieldName}?.DeltaEquals(value, {DeriveComponentUtils.VectorComparisonEpsilon}) ?? value is null)) {{ {dirtySet} }}";
        }

        if (member.IsEquatable)
        {
            if (type.IsValueType)
                return $"if (!{fieldName}.Equals(value)) {{ {dirtySet} }}";

            return $"if (!({fieldName}?.Equals(value) ?? value is null)) {{ {dirtySet} }}";
        }

        return $"if ({fieldName} != value) {{ {dirtySet} }}";
    }

    private static void EmitSerialize(
        StringBuilder sb,
        DeriveMemberGenerationModel[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void Serialize(NetDataWriter writer)");
        sb.AppendLine("        {");

        foreach (var member in members)
        {
            var field = member.Member;
            if (!member.IsSupported)
                continue;

            if (member.UsePutGet)
            {
                sb.AppendLine($"            writer.Put({field.Name});");
            }
            else if (member.IsEnum)
            {
                var baseType = SerializationHelper.GetSpecialTypeCSharpName(member.EnumBaseType);
                sb.AppendLine($"            writer.Put(({baseType}){field.Name});");
            }
            else
            {
                sb.AppendLine($"            {field.Name}.Serialize(writer);");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitDeserialize(
        StringBuilder sb,
        string maskType,
        DeriveMemberGenerationModel[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void Deserialize(NetDataReader reader)");
        sb.AppendLine("        {");

        foreach (var member in members)
        {
            var field = member.Member;
            var propertyName = member.GeneratedPropertyName;

            if (!member.IsSupported)
                continue;

            if (member.UsePutGet)
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            {propertyName} = reader.{getMethod}();");
            }
            else if (member.IsEnum)
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(member.EnumBaseType);
                sb.AppendLine($"            {propertyName} = ({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            {{ {field.Name}.Deserialize(reader); _dirtyMask |= ({maskType})1 << {member.Index}; }}");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitWriteDelta(
        StringBuilder sb,
        string maskType,
        DeriveMemberGenerationModel[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void WriteDelta(NetDataWriter writer)");
        sb.AppendLine("        {");
        sb.AppendLine("            var mask = _dirtyMask;");
        sb.AppendLine("            writer.Put(mask);");

        foreach (var member in members)
        {
            var field = member.Member;

            if (!member.IsSupported)
                continue;

            if (member.UsePutGet)
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) writer.Put({field.Name});");
            }
            else if (member.IsEnum)
            {
                var baseType = SerializationHelper.GetSpecialTypeCSharpName(member.EnumBaseType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) writer.Put(({baseType}){field.Name});");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) {field.Name}.Serialize(writer);");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitReadDelta(
        StringBuilder sb,
        string maskType,
        string maskTypeRead,
        DeriveMemberGenerationModel[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (maskTypeRead == null)
            throw new ArgumentNullException(nameof(maskTypeRead));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void ReadDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        foreach (var member in members)
        {
            var field = member.Member;
            var propertyName = member.GeneratedPropertyName;

            if (!member.IsSupported)
                continue;

            if (member.UsePutGet)
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) {propertyName} = reader.{getMethod}();");
            }
            else if (member.IsEnum)
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(member.EnumBaseType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) {propertyName} = ({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) {{ {field.Name}.Deserialize(reader); _dirtyMask |= ({maskType})1 << {member.Index}; }}");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitSkipDelta(
        StringBuilder sb,
        string maskType,
        string maskTypeRead,
        DeriveMemberGenerationModel[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (maskTypeRead == null)
            throw new ArgumentNullException(nameof(maskTypeRead));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void SkipDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        foreach (var member in members)
        {
            var field = member.Member;

            if (!member.IsSupported)
                continue;

            if (member.UsePutGet)
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) reader.{getMethod}();");
            }
            else if (member.IsEnum)
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(member.EnumBaseType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {member.Index})) != 0) {{ var dummy = default({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}); dummy.Deserialize(reader); }}");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }
}