using System;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public sealed class DeriveINetworkedComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(
            codeProvider,
            static (spc, nameAndContent) => spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code));
    }

    private static bool Predicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        if (cancellationToken.IsCancellationRequested)
            return false;

        if (syntaxNode is not StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl)
            return false;

        foreach (var attributeList in structDecl.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (attribute.Name is IdentifierNameSyntax { Identifier.Text: "DeriveINetworkedComponent" })
                    return true;
            }
        }

        return false;
    }

    private static (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return (string.Empty, string.Empty);

        var symbol = DeriveUtils.GetAttributedSymbol(context, ct);
        var targetModel = DeriveComponentUtils.GetTargetModel(symbol);
        var code = GenerateNetworkedComponent(targetModel);
        var genName = DeriveUtils.GetGeneratedFileName(symbol);

        return (genName, code);
    }

    private static string GenerateNetworkedComponent(DeriveTargetModel model)
    {
        var info = model.SourceTarget;
        var emitDirtyMask = info.EmitDirtyMask;
        var mask = model.MaskInfo;
        var members = model.Members;
        
        if (info == null)
            throw new ArgumentNullException(nameof(info));
        if (mask == null)
            throw new ArgumentNullException(nameof(mask));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        var sb = new StringBuilder($@"// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using LiteNetLib.Utils;
using ReadyM.Api.Generators;
using ReadyM.Api.Multiplayer;
using ReadyM.Api.Multiplayer.Extensions;
using ReadyM.Api.Multiplayer.ECS.Components;
using ReadyM.Relay.Common;

namespace {info.Namespace}
{{
    public partial struct {info.Name} : INetworkedComponent
    {{
");

        foreach (var error in DeriveComponentUtils.GetUserInputErrors(info, mask, members, emitDirtyMask, forCpp: false))
        {
            sb.AppendLine($"        #error {error}");
        }

        if (emitDirtyMask)
        {
            sb.AppendLine($"        private {mask.CSharpType} _dirtyMask;");
            sb.AppendLine();
        }

        foreach (var member in members)
        {
            EmitProperty(sb, mask.CSharpType, member);
        }

        EmitSerialize(sb, members);
        EmitDeserialize(sb, mask.CSharpType, members);
        EmitWriteDelta(sb, mask.CSharpType, members);
        EmitReadDelta(sb, mask.CSharpType, mask.ReadMethod, members);
        EmitSkipDelta(sb, mask.CSharpType, mask.ReadMethod, members);

        sb.AppendLine("        public void ClearDirty() => _dirtyMask = 0;");
        sb.AppendLine("        public bool IsDirty => _dirtyMask != 0;");
        sb.AppendLine("    }");
        sb.AppendLine(@"
}

#nullable disable
");

        return sb.ToString();
    }

    private static void EmitProperty(
        StringBuilder sb,
        string maskType,
        DeriveMemberModelWithSupport member)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (member == null)
            throw new ArgumentNullException(nameof(member));

        var field = member.Model.SourceMember;
        var type = field.Type.ToDisplayString();
        if (string.IsNullOrEmpty(type))
            throw new InvalidOperationException("Member type name unexpectedly null or empty.");

        var fieldName = field.Name;
        var propertyName = member.Model.GeneratedPropertyName;

        if (field.ReadOnly)
        {
            sb.AppendLine($"        public readonly {type} {propertyName}");
            sb.AppendLine($"            => {fieldName};");
            return;
        }

        sb.AppendLine($"        public {type} {propertyName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            get => {fieldName};");
        sb.AppendLine($"            set {{ {BuildSetterBody(maskType, member)} }}");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildSetterBody(string maskType, DeriveMemberModelWithSupport member)
    {
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (member == null)
            throw new ArgumentNullException(nameof(member));

        var dirtySet = $"{member.Model.SourceMember.Name} = value; _dirtyMask |= ({maskType})1 << {member.Model.Index};";

        if (!member.IsCSharpSupported || member.CSharpSupport == null)
            return dirtySet;

        return member.CSharpSupport.BuildSetterBody(maskType, member.Model);
    }

    private static void EmitSerialize(
        StringBuilder sb,
        DeriveMemberModelWithSupport[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void Serialize(NetDataWriter writer)");
        sb.AppendLine("        {");

        foreach (var member in members)
        {
            if (!member.IsCSharpSupported || member.CSharpSupport == null)
                continue;

            member.CSharpSupport.EmitSerialize(sb, member.Model);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitDeserialize(
        StringBuilder sb,
        string maskType,
        DeriveMemberModelWithSupport[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void Deserialize(NetDataReader reader)");
        sb.AppendLine("        {");

        foreach (var member in members)
        {
            if (!member.IsCSharpSupported || member.CSharpSupport == null)
                continue;

            member.CSharpSupport.EmitDeserialize(sb, maskType, member.Model);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitWriteDelta(
        StringBuilder sb,
        string maskType,
        DeriveMemberModelWithSupport[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void WriteDelta(NetDataWriter writer)");
        sb.AppendLine("        {");
        sb.AppendLine("            var mask = _dirtyMask;");
        sb.AppendLine("            writer.Put(mask);");

        foreach (var member in members)
        {
            if (!member.IsCSharpSupported || member.CSharpSupport == null)
                continue;

            member.CSharpSupport.EmitWriteDelta(sb, maskType, member.Model);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitReadDelta(
        StringBuilder sb,
        string maskType,
        string maskTypeRead,
        DeriveMemberModelWithSupport[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (maskTypeRead == null)
            throw new ArgumentNullException(nameof(maskTypeRead));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void ReadDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        foreach (var member in members)
        {
            if (!member.IsCSharpSupported || member.CSharpSupport == null)
                continue;

            member.CSharpSupport.EmitReadDelta(sb, maskType, member.Model);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitSkipDelta(
        StringBuilder sb,
        string maskType,
        string maskTypeRead,
        DeriveMemberModelWithSupport[] members)
    {
        if (sb == null)
            throw new ArgumentNullException(nameof(sb));
        if (maskType == null)
            throw new ArgumentNullException(nameof(maskType));
        if (maskTypeRead == null)
            throw new ArgumentNullException(nameof(maskTypeRead));
        if (members == null)
            throw new ArgumentNullException(nameof(members));

        sb.AppendLine("        public void SkipDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        foreach (var member in members)
        {
            if (!member.IsCSharpSupported || member.CSharpSupport == null)
                continue;

            member.CSharpSupport.EmitSkipDelta(sb, maskType, member.Model);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }
}