using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public class DeriveINetworkedComponentGenerator : IIncrementalGenerator
{
    private const string FloatComparisonEpsilon = "0.1f";
    private const string VectorComparisonEpsilon = "0.01f";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, nameAndContent) => { spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code); });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl
               && structDecl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "DeriveINetworkedComponent" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var node = context.Node;

        var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
        var symbol = model.GetDeclaredSymbol(node) as INamedTypeSymbol;

        var mode = AttributeUtils.GetAttribute<byte>(symbol, "DeriveINetworkedComponentAttribute", "Mode", (1 << 0) | (1 << 2));

        var mapFields = (mode & (1 << 0)) != 0;
        var mapProperties = (mode & (1 << 1)) != 0;
        var mapPrivate = (mode & (1 << 2)) != 0;
        var mapPublic = (mode & (1 << 3)) != 0;
        var mapInternal = (mode & (1 << 4)) != 0;

        var name = symbol!.Name;
        var source = GenerateNetworkedComponent(
            symbol,
            mapFields: mapFields,
            mapProperties: mapProperties,
            mapPrivate: mapPrivate,
            mapPublic: mapPublic,
            mapInternal: mapInternal);

        return (name, source);
    }

    private string GenerateNetworkedComponent(INamedTypeSymbol symbol, bool mapFields, bool mapProperties, bool mapPrivate, bool mapPublic, bool mapInternal)
    {
        var info = GeneratorHelper.GetSymbolInfo(
            symbol,
            mapFields: mapFields,
            mapProperties: mapProperties,
            mapPrivate: mapPrivate,
            mapPublic: mapPublic,
            mapInternal: mapInternal);

        string maskType;
        string maskTypeRead;

        switch (info.Members.Length)
        {
            case < sizeof(byte) * 8:
                maskType = "byte";
                maskTypeRead = "GetByte";
                break;
            case < sizeof(ushort) * 8:
                maskType = "ushort";
                maskTypeRead = "GetUShort";
                break;
            case < sizeof(uint) * 8:
                maskType = "uint";
                maskTypeRead = "GetUInt";
                break;
            case < sizeof(ulong) * 8:
                maskType = "ulong";
                maskTypeRead = "GetULong";
                break;
            default:
                throw new InvalidOperationException($"NetworkedComponent {info.Name} has more than 64 fields. This is not supported.");
        }

        var sb = new StringBuilder($@"
// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using LiteNetLib.Utils;
using ReadyM.Api.Generators;
using ReadyM.Api.Multiplayer;
using ReadyM.Api.Multiplayer.Mapping.Data;
using ReadyM.Api.Multiplayer.Extensions;
using ReadyM.Api.Multiplayer.ECS.Components;

namespace {info.Namespace}
{{
    public partial struct {info.Name} : INetworkedComponent
    {{
        private {maskType} _dirtyMask;
        private {maskType} _apiMask;

");
        foreach (var error in info.ErrorMessage)
        {
            sb.AppendLine($"    #error {error}");
        }

        var propertyNames = new string[info.Members.Length];
        var usePutGet = new bool[info.Members.Length];
        var isEnum = new bool[info.Members.Length];
        var enumBaseType = new SpecialType[info.Members.Length];
        var isEquatable = new bool[info.Members.Length];
        var isDeltaEquatable = new bool[info.Members.Length];
        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            usePutGet[i] = SerializationHelper.IsSerializablePrimitive(info.Members[i].Type.SpecialType);
            isEnum[i] = info.Members[i].Type.TypeKind == TypeKind.Enum;
            isEquatable[i] = SerializationHelper.IsEquatable(info.Members[i].Type);
            isDeltaEquatable[i] = SerializationHelper.IsDeltaEquatable(info.Members[i].Type);

            if (isEnum[i])
            {
                enumBaseType[i] = SerializationHelper.GetEnumBaseType(info.Members[i].Type);
            }

            var fieldName = field.Name;
            if (fieldName.StartsWith("_"))
                propertyNames[i] = char.ToUpper(fieldName[1]) + fieldName.Substring(2);
            else
                propertyNames[i] = char.ToUpper(fieldName[0]) + fieldName.Substring(2);
        }

        // public enum Fields : int
        // {
        //     Field1,
        //     Field2,
        //     ...
        // }
        sb.AppendLine("        public static class Fields\n        {");
        for (var i = 0; i < info.Members.Length; i++)
        {
            var type = info.Members[i].Type;

            // find the 
            sb.AppendLine($"            public static readonly Field<{info.Name}, {type}> {propertyNames[i]} = new({i}, static c => c.{propertyNames[i]}, static (ref c, v) => c.{propertyNames[i]}_SetFromGame(v), static (ref c, v) => c.{propertyNames[i]}_SetFromApi(v), static c => c.WasSetFromApi({i}));");
        }

        sb.AppendLine("        }\n");


        // Getters and [Obsolete] setters
        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];
            var type = field.Type.ToDisplayString();
            var propertyName = propertyNames[i];

            if (field.ReadOnly)
            {
                sb.AppendLine($"        public readonly {type} {propertyName}");
                sb.AppendLine($"            => {field.Name};");
            }
            else
            {
                sb.AppendLine($"        public {type} {propertyName}");
                sb.AppendLine("        {");
                sb.AppendLine($"            get => {field.Name};");
                sb.AppendLine($"            set => {propertyName}_SetFromGame(value);");
                sb.AppendLine("        }\n");
            }
        }

        // New setters for setting from Game and from API
        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];
            var type = field.Type.ToDisplayString();
            var propertyName = propertyNames[i];

            if (field.ReadOnly)
            {
                continue;
            }

            // Set from Game setter

            sb.AppendLine($"        private void {propertyName}_SetFromGame({type} value)");
            sb.AppendLine("        {");

            if (field.Type.SpecialType is SpecialType.System_Single or SpecialType.System_Double)
            {
                sb.AppendLine($"            if (Math.Abs({field.Name} - value) > {FloatComparisonEpsilon}) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
            }
            else if (field.Type.Name == "Vector3")
            {
                sb.AppendLine($"            if (Vector3.DistanceSquared({field.Name}, value) > {VectorComparisonEpsilon}) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
            }
            else if (field.Type.Name == "Vector2")
            {
                sb.AppendLine($"            if (Vector2.DistanceSquared({field.Name}, value) > {VectorComparisonEpsilon}) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
            }
            else if (isDeltaEquatable[i])
            {
                if (field.Type.IsValueType)
                    sb.AppendLine($"            if (!{field.Name}.DeltaEquals(value, {VectorComparisonEpsilon})) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
                else
                    sb.AppendLine($"            if (!({field.Name}?.DeltaEquals(value, {VectorComparisonEpsilon}) ?? value is null)) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
            }
            else if (isEquatable[i])
            {
                if (field.Type.IsValueType)
                    sb.AppendLine($"            if (!{field.Name}.Equals(value)) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
                else
                    sb.AppendLine($"            if (!({field.Name}?.Equals(value) ?? value is null)) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
            }
            else
            {
                sb.AppendLine($"            if ({field.Name} != value) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, false); }}");
            }

            sb.AppendLine("        }\n");

            // Set from API setter

            sb.AppendLine($"        private void {propertyName}_SetFromApi({type} value)");
            sb.AppendLine("        {");

            if (field.Type.SpecialType is SpecialType.System_Single or SpecialType.System_Double)
            {
                sb.AppendLine($"            if (Math.Abs({field.Name} - value) > {FloatComparisonEpsilon}) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
            }
            else if (field.Type.Name == "Vector3")
            {
                sb.AppendLine($"            if (Vector3.DistanceSquared({field.Name}, value) > {VectorComparisonEpsilon}) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
            }
            else if (field.Type.Name == "Vector2")
            {
                sb.AppendLine($"            if (Vector2.DistanceSquared({field.Name}, value) > {VectorComparisonEpsilon}) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
            }
            else if (isDeltaEquatable[i])
            {
                if (field.Type.IsValueType)
                    sb.AppendLine($"            if (!{field.Name}.DeltaEquals(value, {VectorComparisonEpsilon})) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
                else
                    sb.AppendLine($"            if (!({field.Name}?.DeltaEquals(value, {VectorComparisonEpsilon}) ?? value is null)) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
            }
            else if (isEquatable[i])
            {
                if (field.Type.IsValueType)
                    sb.AppendLine($"            if (!{field.Name}.Equals(value)) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
                else
                    sb.AppendLine($"            if (!({field.Name}?.Equals(value) ?? value is null)) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
            }
            else
            {
                sb.AppendLine($"            if ({field.Name} != value) {{ {field.Name} = value; SetDirty(Fields.{propertyName}, true); }}");
            }

            sb.AppendLine("        }\n");
        }

        sb.AppendLine("""
                              public void Serialize(NetDataWriter writer)
                              {
                      """);

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            if (usePutGet[i])
            {
                sb.AppendLine($"            writer.Put({field.Name});");
            }
            else if (isEnum[i])
            {
                var baseType = SerializationHelper.GetSpecialTypeCSharpName(enumBaseType[i]);
                sb.AppendLine($"            writer.Put(({baseType}){field.Name});");
            }
            else
            {
                sb.AppendLine($"            {field.Name}.Serialize(writer);");
            }
        }

        sb.AppendLine("        }\n");

        sb.AppendLine("        public void Deserialize(NetDataReader reader)");
        sb.AppendLine("        {");

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];
            var propertyName = char.ToUpper(field.Name[1]) + field.Name.Substring(2);

            if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            {propertyName} = reader.{getMethod}();");
            }
            else if (isEnum[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(enumBaseType[i]);
                sb.AppendLine($"            {field.Name} = ({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            {{ {field.Name}.Deserialize(reader); SetDirty(Fields.{propertyName}, false); }}");
            }
        }

        sb.AppendLine("        }\n");

        sb.AppendLine("""
                              public void WriteDelta(NetDataWriter writer)
                              {
                                  var mask = _dirtyMask;
                                  writer.Put(mask);
                      """);

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            if (usePutGet[i])
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) writer.Put({field.Name});");
            }
            else if (isEnum[i])
            {
                var baseType = SerializationHelper.GetSpecialTypeCSharpName(enumBaseType[i]);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) writer.Put(({baseType}){field.Name});");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {field.Name}.Serialize(writer);");
            }
        }

        sb.AppendLine("        }\n");

        sb.AppendLine("        public void ReadDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];
            var propertyName = char.ToUpper(field.Name[1]) + field.Name.Substring(2);

            if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {propertyName} = reader.{getMethod}();");
            }
            else if (isEnum[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(enumBaseType[i]);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {propertyName} = ({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {{ {field.Name}.Deserialize(reader); SetDirty(Fields.{propertyName}, false); }}");
            }
        }

        sb.AppendLine("        }\n");
        sb.AppendLine("        public void SkipDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) reader.{getMethod}();");
            }
            else if (isEnum[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(enumBaseType[i]);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {{ var dummy = default({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}); dummy.Deserialize(reader); }}");
            }
        }

        sb.AppendLine("        }\n");
        sb.AppendLine("        private void SetDirty(int field, bool fromApi)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var bit = ({maskType})(1 << field);");
        sb.AppendLine("            _dirtyMask |= bit;");
        sb.AppendLine("            if (fromApi)");
        sb.AppendLine("                _apiMask |= bit;");
        sb.AppendLine("        }");
        sb.AppendLine("        public void ClearDirty() => _dirtyMask = 0;");
        sb.AppendLine($"        public void ClearApiFlag(int field) => _apiMask = ({maskType})(_apiMask & ~(({maskType})1 << field));");
        sb.AppendLine("        public bool IsDirty => _dirtyMask != 0;");
        sb.AppendLine("        public bool ChangedFromApi => _apiMask != 0;");
        sb.AppendLine($"        private bool WasSetFromApi(int field) => 0 != (_apiMask & (({maskType})1 << field));");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}