using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Derive.CSharp;
using ReadyM.Api.Generators.Derive.CSharp.Serialization;

namespace ReadyM.Api.Generators;

/// <summary>
/// Emits <c>WriteSave</c>/<c>ReadSave</c> for a struct marked <c>[DeriveSavableComponent]</c> (a component) or
/// <c>[DeriveSaveSerializable]</c> (a value type).
/// </summary>
[Generator]
[SuppressMessage("MicrosoftCodeAnalysisDesign", "RS1032:Define diagnostic message correctly")]
internal sealed class DeriveSavableComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, result) =>
        {
            if (result.Exception is not null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        id: "DSC001",
                        title: $"{nameof(DeriveSavableComponentGenerator)} generator failed",
                        messageFormat: "Save serializer generation failed: {0}",
                        category: "Generator",
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None,
                    string.Join("\\n", result.Exception.ToString().Split(["\r\n", "\r", "\n"], StringSplitOptions.None))));

                return;
            }

            if (string.IsNullOrEmpty(result.GenName))
                return;

            spc.AddSource($"{result.GenName}.Save.g.cs", result.GenCode);
        });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return false;

        if (syntaxNode is not StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl)
            return false;

        return structDecl.AttributeLists
            .SelectMany(static x => x.Attributes)
            .Any(x => x.Name is IdentifierNameSyntax
            {
                Identifier.Text: "DeriveSavableComponent" or "DeriveSavableComponentAttribute"
                              or "DeriveSaveSerializable" or "DeriveSaveSerializableAttribute"
            });
    }

    private TransformResult Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        try
        {
            if (ct.IsCancellationRequested)
                return default;

            var symbol = DeriveUtils.GetTargetSymbol(context, ct);
            var model = DeriveComponentUtils.GetTargetModel(false, symbol, context);
            var code = GenerateSavableComponent(model);
            var name = DeriveUtils.GetGeneratedFileName(symbol);

            return TransformResult.Success(name, code);
        }
        catch (Exception ex)
        {
            return TransformResult.FatalError(ex);
        }
    }

    private string GenerateSavableComponent(DeriveTargetModel model)
    {
        var info = model.Source;
        var access = info.Symbol.DeclaredAccessibility.ToString().ToLower();

        var sb = new StringBuilder();
        var moduleState = new CSharpModuleState();
        var classState = new CSharpClassState(moduleState);
        moduleState.AddUsing("ReadyM.Api.Multiplayer.Serialization");
        moduleState.AddUsing("ReadyM.Api.Multiplayer.Extensions");

        sb.Append($$"""
namespace {{info.Namespace}};

{{access}} partial struct {{info.Name}}
{

""");

        foreach (var member in model.Members)
        {
            if (IsRawEntity(member.Source.Type) && !IsIgnored(member))
            {
                sb.AppendLine($"""
    #error Savable member '{member.Source.Name}' is a raw Entity. Persist a cross-entity reference as a PersistentId (resolved via the guid index).
""");
            }
        }

        EmitWriteSave(sb, model, classState);
        EmitReadSave(sb, model, classState);

        sb.AppendLine("""
}
""");

        var usingSb = new StringBuilder();
        usingSb.Append("""
// <auto-generated/>
#nullable enable

""");

        foreach (var ns in moduleState.Usings.Distinct().OrderBy(static x => x, StringComparer.Ordinal))
        {
            usingSb.AppendLine($"using {ns};");
        }

        sb.Insert(0, usingSb.ToString());

        sb.AppendLine("""

#nullable disable
""");

        return sb.ToString();
    }

    private void EmitWriteSave(StringBuilder sb, DeriveTargetModel model, CSharpClassState classState)
    {
        sb.AppendLine($$"""
    public static void WriteSave(ISaveWriter writer, in {{model.Source.Name}} value)
    {
        writer.BeginObject();
""");

        var methodState = new CSharpMethodState(classState);
        foreach (var member in model.Members)
        {
            if (!ShouldSerialize(member))
                continue;

            var context = new CSharpEmitSerializeContext(
                new CSharpEmitState(sb, methodState),
                CSharpFieldSupportRegistry.EmitSerializeVisitor,
                CSharpFieldSupportRegistry.SaveCodec);
            context.State.ResetIndent("        ");
            context.AppendLine($"writer.Name(\"{SaveKey(member.Source.Name)}\");");
            context.EmitSerializeVar($"value.{member.Source.Name}", member.Source.Type);
        }

        sb.AppendLine("""
        writer.EndObject();
    }

""");
    }

    private void EmitReadSave(StringBuilder sb, DeriveTargetModel model, CSharpClassState classState)
    {
        sb.AppendLine($$"""
    public static void ReadSave(ref {{model.Source.Name}} value, ISaveReader reader)
    {
        reader.BeginObject();
""");

        var methodState = new CSharpMethodState(classState);
        foreach (var member in model.Members)
        {
            if (!ShouldSerialize(member))
                continue;

            var context = new CSharpEmitDeserializeContext(
                new CSharpEmitState(sb, methodState),
                CSharpFieldSupportRegistry.EmitDeserializeVisitor,
                CSharpFieldSupportRegistry.SaveCodec);
            context.State.ResetIndent("        ");
            context.AppendLine($"reader.Name(\"{SaveKey(member.Source.Name)}\");");
            context.EmitDeserializeVar($"value.{member.Source.Name}", member.Source.Type);
        }

        sb.AppendLine("""
        reader.EndObject();
    }
""");
    }

    private static bool ShouldSerialize(DeriveMemberModel member)
        => !IsIgnored(member) && !IsRawEntity(member.Source.Type);

    // Friflo's [Ignore] marks a runtime link handled structurally, so save skips it too.
    private static bool IsIgnored(DeriveMemberModel member)
        => AttributeUtils.HasAttribute(member.Source.Symbol, "SaveIgnoreAttribute")
           || AttributeUtils.HasAttribute(member.Source.Symbol, "IgnoreAttribute");

    private static bool IsRawEntity(ITypeSymbol type)
        => type.Name == "Entity" && type.ContainingNamespace?.ToDisplayString() == "Friflo.Engine.ECS";

    // The on-disk field key: strip a leading underscore and capitalise, so "_items" reads as "Items".
    private static string SaveKey(string fieldName)
        => fieldName.Length > 1 && fieldName[0] == '_'
            ? char.ToUpperInvariant(fieldName[1]) + fieldName.Substring(2)
            : fieldName;

    private struct TransformResult(string genName, string genCode, Exception? exception)
    {
        public string GenName { get; } = genName;
        public string GenCode { get; } = genCode;
        public Exception? Exception { get; } = exception;

        public static TransformResult Success(string genName, string genCode)
            => new(genName, genCode, null);
        public static TransformResult FatalError(Exception? exception = null)
            => new(string.Empty, string.Empty, exception);
    }
}
