using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Derive.CSharp;
using ReadyM.Api.Generators.Derive.CSharp.Serialization;

namespace ReadyM.Api.Generators;

/// <summary>
/// Emits <c>WriteSave</c>/<c>ReadSave</c> for a struct marked <c>[DeriveSavableComponent]</c> (a component) or
/// <c>[DeriveSaveSerializable]</c> (a value type).
/// </summary>
[Generator]
[SuppressMessage("MicrosoftCodeAnalysisDesign", "RS1032:Define diagnostic message correctly")]
internal sealed class DeriveSavableComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, result) =>
        {
            if (result.Exception is not null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        id: "DSC001",
                        title: $"{nameof(DeriveSavableComponentGenerator)} generator failed",
                        messageFormat: "Save serializer generation failed: {0}",
                        category: "Generator",
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None,
                    string.Join("\\n", result.Exception.ToString().Split(["\r\n", "\r", "\n"], StringSplitOptions.None))));

                return;
            }

            if (string.IsNullOrEmpty(result.GenName))
                return;

            spc.AddSource($"{result.GenName}.Save.g.cs", result.GenCode);
        });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return false;

        if (syntaxNode is not StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl)
            return false;

        return structDecl.AttributeLists
            .SelectMany(static x => x.Attributes)
            .Any(x => x.Name is IdentifierNameSyntax
            {
                Identifier.Text: "DeriveSavableComponent" or "DeriveSavableComponentAttribute"
                              or "DeriveSaveSerializable" or "DeriveSaveSerializableAttribute"
            });
    }

    private TransformResult Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        try
        {
            if (ct.IsCancellationRequested)
                return default;

            var symbol = DeriveUtils.GetTargetSymbol(context, ct);
            var model = DeriveComponentUtils.GetTargetModel(false, symbol, context);
            var isComponent = AttributeUtils.HasAttribute(symbol, "DeriveSavableComponentAttribute");
            var code = GenerateSavableComponent(model, isComponent);
            var name = DeriveUtils.GetGeneratedFileName(symbol);

            return TransformResult.Success(name, code);
        }
        catch (Exception ex)
        {
            return TransformResult.FatalError(ex);
        }
    }

    private string GenerateSavableComponent(DeriveTargetModel model, bool isComponent)
    {
        var info = model.Source;
        var access = info.Symbol.DeclaredAccessibility.ToString().ToLower();
        var contract = isComponent ? "ISavableComponent" : "ISaveSerializable";

        var sb = new StringBuilder();
        var moduleState = new CSharpModuleState();
        var classState = new CSharpClassState(moduleState);
        moduleState.AddUsing("ReadyM.Api.Saves");
        moduleState.AddUsing("ReadyM.Api.Extensions");

        sb.Append($$"""
namespace {{info.Namespace}};

{{access}} partial struct {{info.Name}} : {{contract}}
{

""");

        if (isComponent)
        {
            sb.AppendLine($$"""
    public readonly string SaveName => "{{ResolveSaveName(info.Symbol)}}";
    public readonly ushort SaveVersion => {{ResolveSaveVersion(info.Symbol)}};

""");
        }

        EmitWriteSave(sb, model, classState);
        EmitReadSave(sb, model, classState);

        sb.AppendLine("""
}
""");

        var usingSb = new StringBuilder();
        usingSb.Append("""
// <auto-generated/>
#nullable enable

""");

        foreach (var ns in moduleState.Usings.Distinct().OrderBy(static x => x, StringComparer.Ordinal))
        {
            usingSb.AppendLine($"using {ns};");
        }

        sb.Insert(0, usingSb.ToString());

        sb.AppendLine("""

#nullable disable
""");

        return sb.ToString();
    }

    private void EmitWriteSave(StringBuilder sb, DeriveTargetModel model, CSharpClassState classState)
    {
        sb.AppendLine("""
    public void WriteSave(ISaveWriter writer, ISaveWriteContext context)
    {
        writer.BeginObject();
""");

        var methodState = new CSharpMethodState(classState);
        foreach (var member in model.Members)
        {
            if (!ShouldSerialize(member))
                continue;

            var context = new CSharpEmitSerializeContext(
                new CSharpEmitState(sb, methodState),
                CSharpFieldSupportRegistry.EmitSerializeVisitor,
                CSharpFieldSupportRegistry.SaveCodec);
            context.State.ResetIndent("        ");
            context.AppendLine($"writer.Name(\"{SaveKey(member.Source.Name)}\");");

            // A cross-entity reference.
            if (IsRawEntity(member.Source.Type))
            {
                context.AppendLine($"context.WriteEntityRef(writer, {member.Source.Name});");
                continue;
            }

            context.EmitSerializeVar(member.Source.Name, member.Source.Type);
        }

        sb.AppendLine("""
        writer.EndObject();
    }

""");
    }

    private void EmitReadSave(StringBuilder sb, DeriveTargetModel model, CSharpClassState classState)
    {
        sb.AppendLine("""
    public void ReadSave(ISaveReader reader, ISaveReadContext context)
    {
        reader.BeginObject();
""");

        var methodState = new CSharpMethodState(classState);
        foreach (var member in model.Members)
        {
            if (!ShouldSerialize(member))
                continue;

            var context = new CSharpEmitDeserializeContext(
                new CSharpEmitState(sb, methodState),
                CSharpFieldSupportRegistry.EmitDeserializeVisitor,
                CSharpFieldSupportRegistry.SaveCodec);
            context.State.ResetIndent("        ");
            context.AppendLine($"reader.Name(\"{SaveKey(member.Source.Name)}\");");

            // Resolve the PersistentId back to the loaded entity (default when empty or unresolved).
            if (IsRawEntity(member.Source.Type))
            {
                context.AppendLine($"{member.Source.Name} = context.ReadEntityRef(reader);");
                continue;
            }

            context.EmitDeserializeVar(member.Source.Name, member.Source.Type);
        }

        sb.AppendLine("""
        reader.EndObject();
    }
""");
    }

    private static bool ShouldSerialize(DeriveMemberModel member)
        => !IsIgnored(member);

    private static bool IsIgnored(DeriveMemberModel member)
        => AttributeUtils.HasAttribute(member.Source.Symbol, "SaveIgnoreAttribute");

    private static bool IsRawEntity(ITypeSymbol type)
        => type.Name == "Entity" && type.ContainingNamespace?.ToDisplayString() == "Friflo.Engine.ECS";

    // The on-disk field key: strip a leading underscore and capitalise, so "_items" reads as "Items".
    private static string SaveKey(string fieldName)
        => fieldName.Length > 1 && fieldName[0] == '_'
            ? char.ToUpperInvariant(fieldName[1]) + fieldName.Substring(2)
            : fieldName;

    // The [SaveName] override baked at generation time, else the type name.
    private static string ResolveSaveName(ISymbol symbol)
    {
        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name is "SaveName" or "SaveNameAttribute");

        if (attr is { ConstructorArguments.Length: > 0 } && attr.ConstructorArguments[0].Value is string name && name.Length > 0)
            return name;

        return symbol.Name;
    }

    // The [SaveVersion] override baked at generation time, else 1.
    private static ushort ResolveSaveVersion(ISymbol symbol)
    {
        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name is "SaveVersion" or "SaveVersionAttribute");

        if (attr is { ConstructorArguments.Length: > 0 } && attr.ConstructorArguments[0].Value is ushort version)
            return version;

        return 1;
    }

    private struct TransformResult(string genName, string genCode, Exception? exception)
    {
        public string GenName { get; } = genName;
        public string GenCode { get; } = genCode;
        public Exception? Exception { get; } = exception;

        public static TransformResult Success(string genName, string genCode)
            => new(genName, genCode, null);
        public static TransformResult FatalError(Exception? exception = null)
            => new(string.Empty, string.Empty, exception);
    }
}
