using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
namespace ReadyM.Api.Generators;

[Generator]
public class DeriveJsonSerializableGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform);

        var desc = new DiagnosticDescriptor(
            "RC001",
            "TextSerializable Generator Exception",
            "Exception while generating `{0}`",
            "Generator",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true
        );

        context.RegisterSourceOutput(codeProvider, (spc, nameAndContent) =>
        {
            if (nameAndContent.Exc == null)
            {
                spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code);
            }
            else
            {
                var diag = Diagnostic.Create(
                    desc,
                    Location.None,
                    nameAndContent.Name
                );
                spc.ReportDiagnostic(diag);
                spc.AddSource($"{nameAndContent.Name}.g.cs",
                             $"""
                                    /* Error!
                                    {nameAndContent.Exc}
                                    */
                                    """);
            }
        });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is TypeDeclarationSyntax { AttributeLists.Count: > 0 } typeDecl &&
               // typeDecl.Modifiers.Any(m => m.Text == "partial") &&
               typeDecl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "DeriveJsonSerializable" });
    }

    private (string Name, string Code, Exception? Exc) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var node = context.Node;

        var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
        var symbol = model.GetDeclaredSymbol(node) as INamedTypeSymbol;

        var mode = AttributeUtils.GetAttribute<byte>(symbol, "DeriveJsonSerializableAttribute", "mode", (1 << 0) | (1 << 2));
        var mapSettings = DeriveUtils.GetMapSettings(mode);
        
        var name = symbol!.Name;
        var source = GenerateTextSerializableImpl(symbol, mapSettings);
        return (name, source, null);
    }

    private bool IsTextSerializable(ITypeSymbol type)
    {
        const string attributeFullName = "ReadyM.Api.Serialization.DeriveJsonSerializableAttribute";
        return type
            .GetAttributes()
            .Any(attr => attr.AttributeClass?.ToDisplayString() == attributeFullName);
    }

    private string GenerateTextSerializableImpl(INamedTypeSymbol symbol, DeriveMapSettings mapSettings)
    {
        var access = symbol.DeclaredAccessibility.ToString().ToLower(); // public, internal, etc.
        var info = DeriveUtils.GetTargetInfo(symbol, false, false, mapSettings);

        var sb = new StringBuilder($@"// <auto-generated/>

using System;
using System.Text.Json;
using ReadyM.Api.Serialization;

namespace {info.Namespace};

{access} partial struct {info.Name}
{{");
        
        foreach (var error in info.Errors)
        {
            sb.AppendLine($"    #error {error}");
        }

        var useReadWrite = new bool[info.Members.Length];
        var readMethods = new string[info.Members.Length];
        var writeMethods = new string[info.Members.Length];
        var useTextSerialize = new bool[info.Members.Length];
        var isNullable = new bool[info.Members.Length];

        for (var i = 0; i < info.Members.Length; i++)
        {
            useReadWrite[i] = TextSerializationHelper.IsSerializablePrimitive(info.Members[i].Type.SpecialType);
            useTextSerialize[i] = IsTextSerializable(info.Members[i].Type);
            isNullable[i] = info.Members[i].Type.IsReferenceType && info.Members[i].Type.NullableAnnotation != NullableAnnotation.Annotated;

            if (useReadWrite[i])
            {
                readMethods[i] = TextSerializationHelper.GetReadMethod(info.Members[i].Type.SpecialType);
                writeMethods[i] = TextSerializationHelper.GetWriteMethod(info.Members[i].Type.SpecialType);
            }
        }
        
        sb.AppendLine($$"""
                            [RegisterJsonConverter]
                            internal class Converter : System.Text.Json.Serialization.JsonConverter<{{info.Name}}>
                            {
                                public override {{info.Name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                                    => TextDeserialize(ref reader, options);

                                public override void Write(Utf8JsonWriter writer, {{info.Name}} value, JsonSerializerOptions options)
                                    => TextSerialize(writer, value, options);
                            }
                            
                            public static {{symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}} TextDeserialize(ref Utf8JsonReader reader, JsonSerializerOptions options)
                            {
                                DebugJson.Assert(reader.TokenType == JsonTokenType.StartObject);
                                
                        """);

        if (info.IsNullable)
        {
            sb.AppendLine("""
                                  if (reader.Peek() == JsonTokenType.Null)
                                  {
                                      reader.Read();
                                      return null;
                                  }
                          """);
        }
        
        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            sb.AppendLine($"        {field.Type} {field.Name.ToLowerFirst()} = default;");
        }
        
        sb.AppendLine("""
                              while (reader.Read())
                              {
                                  if (reader.TokenType == JsonTokenType.EndObject)
                                      break;
                              
                                  DebugJson.Assert(reader.TokenType == JsonTokenType.PropertyName);
                                  var propertyName = reader.GetString();
                                  reader.Read();
                                  
                      """);
        
        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            if (i == 0)
                sb.AppendLine($"""            if (propertyName == "{field.Name.ToLowerFirst()}")""");
            else
                sb.AppendLine($"""            else if (propertyName == "{field.Name.ToLowerFirst()}")""");

            sb.AppendLine( """            {""");

            if (useReadWrite[i])
            {
                sb.AppendLine($"""
                                               {field.Name.ToLowerFirst()} = reader.{readMethods[i]}();
                               """);
            }
            else if (useTextSerialize[i])
            {
                sb.AppendLine($"""
                                               {field.Name.ToLowerFirst()} = {field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.TextDeserialize(ref reader, options);
                               """);
            }
            else
            {
                sb.AppendLine($"""
                                               {field.Name.ToLowerFirst()} = JsonSerializer.Deserialize<{field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(ref reader, options);
                               """);
            }
            
            sb.AppendLine( """            }""");
        }

        if (info.Members.Length > 0)
        {
            sb.AppendLine("""
                                      else
                                      {
                                          reader.Skip(); // skip unknown properties
                                      }
                          """);
        }

        sb.AppendLine("""        }""");

        var fieldNames = string.Join(", ", info.Members.Select(x => x.Name.ToLowerFirst()));
        sb.AppendLine($$"""
                              
                              return new {{info.Name}}({{fieldNames}});
                          }
                      """);

        sb.AppendLine($$"""
                            
                            /// <exclude />
                            public static void TextSerialize(Utf8JsonWriter writer, {{symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}} obj, JsonSerializerOptions options)
                            {
                                writer.WriteStartObject();
                        """);

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            if (useReadWrite[i])
            {
                sb.AppendLine($"""
                                       writer.{writeMethods[i]}("{field.Name.ToLowerFirst()}", obj.{field.Name});
                               """);
            }
            else if (useTextSerialize[i])
            {
                sb.AppendLine($"""
                                       writer.WritePropertyName("{field.Name.ToLowerFirst()}");
                                       {field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.TextSerialize(writer, obj.{field.Name}, options);
                               """);
            }
            else
            {
                sb.AppendLine($"""
                                       writer.WritePropertyName("{field.Name.ToLowerFirst()}");
                                       JsonSerializer.Serialize<{field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(writer, obj.{field.Name}, options);
                               """);
            }
        }

        sb.AppendLine("""
                              writer.WriteEndObject();
                      """);
        sb.AppendLine("    }");
        
        sb.AppendLine(@"
}
                      ");

        return sb.ToString();
    }
}