using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public sealed class DeriveCSharpNativeComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(
            codeProvider,
            static (spc, nameAndContent) =>
            {
                if (string.IsNullOrEmpty(nameAndContent.Name))
                    return;
                
                spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code);
            });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        if (cancellationToken.IsCancellationRequested)
            return false;

        if (syntaxNode is not StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl)
            return false;

        var attributes = structDecl.AttributeLists.SelectMany(static x => x.Attributes).ToList();
        return attributes.Any(x => x.Name is IdentifierNameSyntax { Identifier.Text: "NativeComponent" or "NativeComponentAttribute" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return (string.Empty, string.Empty);

        var symbol = DeriveUtils.GetAttributedSymbol(context, ct);
        
        bool bindDelete = false;
        
        if (AttributeUtils.HasAttribute(symbol, "NativeComponentAttribute"))
        {
            bindDelete = AttributeUtils.GetAttribute<bool>(
                symbol,
                "NativeComponentAttribute",
                "bindDelete",
                false);
        }

        if (!bindDelete)
            return (string.Empty, string.Empty);
        
        var targetModel = DeriveComponentUtils.GetTargetModel(symbol, context);
        var code = GenerateNativeBindingComponent(targetModel);
        var genName = DeriveUtils.GetGeneratedFileName(symbol);

        return (genName, code);
    }

    private string GenerateNativeBindingComponent(DeriveTargetModel model)
    {
        var info = model.Source;
        var sb = new StringBuilder();
        
        sb.Append($@"// <auto-generated/>
#nullable enable

using System.Runtime.InteropServices;
using ReadyM.Api.ECS.Managers;
using Friflo.Engine.ECS;

namespace {info.Namespace};

public partial struct {info.Name}
{{
    public unsafe class NativeEntityDeleteImpl : IEntityDeleteImpl
    {{
        [StructLayout(LayoutKind.Sequential)]
        public struct NativeBinding
        {{
            public void* Target;
            public delegate* unmanaged<void*, Friflo.Engine.ECS.RawEntity, {info.Name}*, void> OnEntityDeleteHandler;

            public bool IsValid
                => Target != null && OnEntityDeleteHandler != null;
        }}

        private NativeBinding _binding;

        public void HandleDelete(Friflo.Engine.ECS.Entity entity)
        {{
            if (!_binding.IsValid)
            {{
                throw new System.InvalidOperationException(""{info.Name}.NativeEntityDeleteImpl not bound"");
            }}

            if (!entity.TryGetComponent<{info.Name}>(out var comp))
                return;
            _binding.OnEntityDeleteHandler(_binding.Target, entity.RawEntity, &comp);
        }}

        public void BindNative(NativeBinding binding)
        {{
            _binding = binding;
        }}
    }}
}}

#nullable disable
");

        return sb.ToString();
    }
}