using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
internal class DeriveINetSerializableGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, nameAndContent) => { spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code); });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is TypeDeclarationSyntax { AttributeLists.Count: > 0 } typeDecl &&
               typeDecl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "DeriveINetSerializable" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return (string.Empty, string.Empty);

        var symbol = DeriveUtils.GetTargetSymbol(context, ct);
        var targetModel = DeriveComponentUtils.GetTargetModel(symbol, context);
        var code = GenerateINetSerializableImpl(targetModel);
        var genName = DeriveUtils.GetGeneratedFileName(symbol);

        return (genName, code);
    }

    private string GenerateINetSerializableImpl(DeriveTargetModel model)
    {
        var info = model.Source;
        
        var access = model.Source.Symbol.DeclaredAccessibility.ToString().ToLower(); // public, internal, etc.
        var sb = new StringBuilder($@"// <auto-generated/>
#nullable enable

using System.Diagnostics.Contracts;
using LiteNetLib.Utils;
using ReadyM.Api.Multiplayer.Extensions;

namespace {info.Namespace};

{access} partial struct {info.Name}
{{
");

        foreach (var error in info.Errors)
        {
            sb.AppendLine($"""
    #error {error}
""");
        }
        
        var usePutGet = new bool[info.Members.Count];
        var isEnum = new bool[info.Members.Count];
        var enumBaseType = new SpecialType[info.Members.Count];

        for (var i = 0; i < info.Members.Count; i++)
        {
            usePutGet[i] = SerializationHelper.IsSerializablePrimitive(info.Members[i].Type.SpecialType);
            isEnum[i] = info.Members[i].Type.TypeKind == TypeKind.Enum;

            if (isEnum[i])
            {
                enumBaseType[i] = SerializationHelper.GetEnumBaseType(info.Members[i].Type);
            }
        }

        sb.AppendLine("""
    [Pure]
    public void Serialize(NetDataWriter writer)
    {
""");

        for (var i = 0; i < info.Members.Count; i++)
        {
            var field = info.Members[i];

            if (isEnum[i])
            {
                var baseType = SerializationHelper.GetSpecialTypeCSharpName(enumBaseType[i]);
                sb.AppendLine($"""
        writer.Put(({baseType}){field.Name});
""");
            }
            else if (usePutGet[i])
            {
                sb.AppendLine($"""
        writer.Put({field.Name});
""");
            }
            else
            {
                sb.AppendLine($"""
        {field.Name}.Serialize(writer);
""");
            }
        }

        sb.AppendLine("""
    }
    
""");

        sb.AppendLine("""
    public void Deserialize(NetDataReader reader)
    {
""");

        for (var i = 0; i < info.Members.Count; i++)
        {
            var field = info.Members[i];

            if (isEnum[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(enumBaseType[i]);
                sb.AppendLine($"""
        {field.Name} = ({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})reader.{getMethod}();
""");
            }
            else if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"""
        {field.Name} = reader.{getMethod}();
""");
            }
            else
            {
                sb.AppendLine($"""
        {field.Name}.Deserialize(reader);
""");
            }
        }
        
        sb.AppendLine("""
    }
    
""");
        
        sb.AppendLine(@"
}

#nullable disable
                      ");

        return sb.ToString();
    }
}
