using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators
{
    [Generator]
    public sealed class DeriveCppNativeComponentGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);
            context.RegisterSourceOutput(
                codeProvider,
                static (spc, result) => spc.AddSource(result.Name + ".NativeComponentFragment.g.cs", result.Code));
        }

        private static bool Predicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
        {
            if (cancellationToken.IsCancellationRequested)
                return false;

            var structDecl = syntaxNode as StructDeclarationSyntax;
            if (structDecl == null || structDecl.AttributeLists.Count == 0)
                return false;

            foreach (var attribute in structDecl.AttributeLists.SelectMany(static x => x.Attributes))
            {
                if (attribute.Name is IdentifierNameSyntax identifierName &&
                    identifierName.Identifier.Text == "DeriveINetworkedComponent")
                {
                    return true;
                }
            }

            return false;
        }

        private static (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken cancellationToken)
        {
            if (cancellationToken.IsCancellationRequested)
                return (string.Empty, string.Empty);

            var node = context.Node;
            var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
            var symbol = model.GetDeclaredSymbol(node, cancellationToken) as INamedTypeSymbol;
            if (symbol == null)
                throw new InvalidOperationException("Expected INamedTypeSymbol for struct declaration.");

            var mode = AttributeUtils.GetAttribute<byte>(
                symbol,
                "DeriveINetworkedComponentAttribute",
                "mode",
                (1 << 0) | (1 << 2));

            var emitDirtyMask = AttributeUtils.GetAttribute(
                symbol,
                "DeriveINetworkedComponentAttribute",
                "emitDirtyMask",
                true);

            var mapFields = (mode & (1 << 0)) != 0;
            var mapProperties = (mode & (1 << 1)) != 0;
            var mapPrivate = (mode & (1 << 2)) != 0;
            var mapPublic = (mode & (1 << 3)) != 0;
            var mapInternal = (mode & (1 << 4)) != 0;

            var generationModel = DeriveComponentUtils.CreateGenerationModel(
                symbol,
                mapFields,
                mapProperties,
                mapPrivate,
                mapPublic,
                mapInternal,
                emitDirtyMask);

            var code = GenerateCppFragment(generationModel);
            return (symbol.Name, code);
        }

        private static string GenerateCppFragment(DeriveTargetGenerationModel model)
        {
            if (model == null)
                throw new ArgumentNullException(nameof(model));

            var sb = new StringBuilder();

            sb.AppendLine("#if GENERATED_CPP_FRAGMENT");
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();

            foreach (var error in DeriveComponentUtils.GetUserInputErrors(model))
            {
                sb.AppendLine("#error " + error);
            }

            if (sb[sb.Length - 1] != '\n')
                sb.AppendLine();

            foreach (var member in model.Members)
            {
                EmitCppAccessor(sb, model, member);
            }

            sb.AppendLine("private:");

            if (model.EmitDirtyMask)
            {
                sb.AppendLine("    " + model.Mask.CppType + " _dirtyMask = 0;");
            }
            else
            {
                sb.AppendLine("    " + model.Mask.CppType + " _dirtyMask = 0; // NOTE: Respecting the user-defined dirty mask size.");
            }

            sb.AppendLine();

            foreach (var member in model.Members)
            {
                var type = member.Member.Type;
                if (type == null)
                    throw new InvalidOperationException("Member type unexpectedly null.");

                var cppType = DeriveComponentUtils.GetCppTypeName(type);
                var defaultValue = DeriveComponentUtils.GetCppDefaultValue(type);
                sb.AppendLine("    " + cppType + " " + member.Member.Name + " = " + defaultValue + ";");
            }

            sb.AppendLine();
            sb.AppendLine("#endif");

            return sb.ToString();
        }

        private static void EmitCppAccessor(
            StringBuilder sb,
            DeriveTargetGenerationModel model,
            DeriveMemberGenerationModel member)
        {
            var type = member.Member.Type;
            if (type == null)
                throw new InvalidOperationException("Member type unexpectedly null.");

            var cppType = DeriveComponentUtils.GetCppTypeName(type);
            var propertyName = member.GeneratedPropertyName;
            var fieldName = member.Member.Name;

            sb.AppendLine("public:");
            sb.AppendLine("    " + cppType + " " + propertyName + "() const");
            sb.AppendLine("    {");
            sb.AppendLine("        return " + fieldName + ";");
            sb.AppendLine("    }");
            sb.AppendLine();

            if (!member.Member.ReadOnly)
            {
                sb.AppendLine("    void Set" + propertyName + "(" + cppType + " value)");
                sb.AppendLine("    {");

                var condition = DeriveComponentUtils.BuildCppSetterCondition(member);
                sb.AppendLine("        if (" + condition + ")");
                sb.AppendLine("        {");
                sb.AppendLine("            " + fieldName + " = value;");
                sb.AppendLine("            _dirtyMask |= static_cast<" + model.Mask.CppType + ">(1) << " + member.Index + ";");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }
    }
}