using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public sealed class DeriveCSharpNativeComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider.CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(
            codeProvider,
            static (spc, nameAndContent) =>
            {
                if (string.IsNullOrEmpty(nameAndContent.Name))
                    return;
                
                spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code);
            });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        if (cancellationToken.IsCancellationRequested)
            return false;

        if (syntaxNode is not StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl)
            return false;

        var attributes = structDecl.AttributeLists.SelectMany(static x => x.Attributes).ToList();
        return attributes.Any(x => x.Name is IdentifierNameSyntax { Identifier.Text: "NativeComponent" or "NativeComponentAttribute" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        if (ct.IsCancellationRequested)
            return (string.Empty, string.Empty);

        var symbol = DeriveUtils.GetTargetSymbol(context, ct);
        var targetModel = DeriveComponentUtils.GetTargetModel(symbol, context);
        
        if (!targetModel.Source.EmitBindDelete)
            return (string.Empty, string.Empty);
        
        var structDecl = (StructDeclarationSyntax)context.Node;
        var code = GenerateNativeBindingComponent(targetModel, structDecl);

        var genName = DeriveUtils.GetGeneratedFileName(symbol);

        return (genName, code);
    }
    
    private static string GetTypeParameterList(StructDeclarationSyntax structDecl)
    {
        return structDecl.TypeParameterList?.ToString() ?? string.Empty;
    }
    
    private static string GetTypeArgumentList(StructDeclarationSyntax structDecl)
    {
        if (structDecl.TypeParameterList is null)
            return string.Empty;

        var args = string.Join(
            ", ",
            structDecl.TypeParameterList.Parameters.Select(static p => p.Identifier.ToString()));

        return $"<{args}>";
    }
    
    private string GenerateNativeBindingComponent(
        DeriveTargetModel model,
        StructDeclarationSyntax structDecl)
    {
        var info = model.Source;
        var typeParameterList = GetTypeParameterList(structDecl);
        var typeArgumentList = GetTypeArgumentList(structDecl);

        var componentType = $"{info.Name}{typeArgumentList}";

        var sb = new StringBuilder();

        sb.Append($@"// <auto-generated/>
#nullable enable

using System.Runtime.InteropServices;
using ReadyM.Api.ECS.Managers;
using Friflo.Engine.ECS;

namespace {info.Namespace};

public partial struct {info.Name}{typeParameterList}
{{
    public unsafe class NativeEntityDeleteImpl : IEntityDeleteImpl
    {{
        [StructLayout(LayoutKind.Sequential)]
        public struct NativeBinding
        {{
            public void* Target;
            public delegate* unmanaged<void*, Friflo.Engine.ECS.RawEntity, {componentType}*, void> OnEntityDeleteHandler;

            public bool IsValid
                => Target != null && OnEntityDeleteHandler != null;

            public void EnsureValid()
                => EnsureValid($""{{nameof({info.Name}{typeParameterList})}}.{{nameof(NativeEntityDeleteImpl)}}"");

            public void EnsureValid(string path)
            {{
                if (Target == null)
                    throw new System.InvalidOperationException($""{{path}}.Target is null"");
                if (OnEntityDeleteHandler == null)
                    throw new System.InvalidOperationException($""{{path}}.OnEntityDeleteHandler is null"");
            }}
        }}

        private NativeBinding _binding;

        public void HandleDelete(Friflo.Engine.ECS.Entity entity)
        {{
            if (!_binding.IsValid)
            {{
                throw new System.InvalidOperationException(""{componentType}.NativeEntityDeleteImpl not bound"");
            }}

            if (!entity.TryGetComponent<{componentType}>(out var comp))
                return;

            _binding.OnEntityDeleteHandler(_binding.Target, entity.RawEntity, &comp);
        }}

        public void BindNative(NativeBinding binding)
        {{
            _binding = binding;
        }}
    }}
}}

#nullable disable
");

        return sb.ToString();
    }
}