using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public class DeriveINetSerializableGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, nameAndContent) => { spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code); });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is TypeDeclarationSyntax { AttributeLists.Count: > 0 } typeDecl &&
               // structDecl.Modifiers.Any(m => m.Text == "partial") &&
               typeDecl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "DeriveINetSerializable" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var node = context.Node;

        var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
        var symbol = model.GetDeclaredSymbol(node) as INamedTypeSymbol;

        var mode = AttributeUtils.GetAttribute<byte>(symbol, "DeriveINetSerializableAttribute", "Mode", (1 << 0) | (1 << 2));
        
        var mapFields = (mode & (1 << 0)) != 0;
        var mapProperties = (mode & (1 << 1)) != 0;
        var mapPrivate = (mode & (1 << 2)) != 0;
        var mapPublic = (mode & (1 << 3)) != 0;
        var mapInternal = (mode & (1 << 4)) != 0;
        
        var name = symbol!.Name;
        var source = GenerateINetSerializableImpl(
            symbol,
            mapFields: mapFields,
            mapProperties: mapProperties, 
            mapPrivate: mapPrivate, 
            mapPublic: mapPublic, 
            mapInternal: mapInternal);
        
        return (name, source);
    }

    private string GenerateINetSerializableImpl(INamedTypeSymbol symbol, bool mapFields, bool mapProperties, bool mapPrivate, bool mapPublic, bool mapInternal)
    {
        var info = GeneratorHelper.GetSymbolInfo(
            symbol,
            mapFields: mapFields,
            mapProperties: mapProperties, 
            mapPrivate: mapPrivate, 
            mapPublic: mapPublic, 
            mapInternal: mapInternal);
        
        var sb = new StringBuilder($@"
// <auto-generated/>

using System.Diagnostics.Contracts;
using LiteNetLib.Utils;
using ReadyM.Api.Multiplayer.Extensions;

namespace {info.Namespace};

public partial struct {info.Name}
{{
");

        foreach (var error in info.ErrorMessage)
        {
            sb.AppendLine($"    #error {error}");
        }
        
        var usePutGet = new bool[info.Members.Length];
        var isEnum = new bool[info.Members.Length];
        var enumBaseType = new SpecialType[info.Members.Length];

        for (var i = 0; i < info.Members.Length; i++)
        {
            usePutGet[i] = SerializationHelper.IsSerializablePrimitive(info.Members[i].Type.SpecialType);
            isEnum[i] = info.Members[i].Type.TypeKind == TypeKind.Enum;

            if (isEnum[i])
            {
                enumBaseType[i] = SerializationHelper.GetEnumBaseType(info.Members[i].Type);
            }
        }

        sb.AppendLine("""
                          [Pure]
                          public void Serialize(NetDataWriter writer)
                          {
                      """);

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            if (isEnum[i])
            {
                var baseType = SerializationHelper.GetSpecialTypeCSharpName(enumBaseType[i]);
                sb.AppendLine($"        writer.Put(({baseType}){field.Name});");
            }
            else if (usePutGet[i])
            {
                sb.AppendLine($"        writer.Put({field.Name});");
            }
            else
            {
                sb.AppendLine($"        {field.Name}.Serialize(writer);");
            }
        }

        sb.AppendLine("    }\n");

        sb.AppendLine("""
                          public void Deserialize(NetDataReader reader)
                          {
                      """);

        for (var i = 0; i < info.Members.Length; i++)
        {
            var field = info.Members[i];

            if (isEnum[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(enumBaseType[i]);
                sb.AppendLine($"        {field.Name} = ({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})reader.{getMethod}();");
            }
            else if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"        {field.Name} = reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"        {field.Name}.Deserialize(reader);");
            }
        }
        
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
