namespace ReadyM.Api.Generators;

/// <summary>
/// The <c>[DuplicateOf]</c> attribute, injected into every compilation that references this generator so consumers
/// do not need a runtime package to mark a duplicate.
/// </summary>
internal static class DuplicateStructAttributeSource
{
    public const string MetadataName = "ReadyM.Api.Generators.DuplicateOfAttribute";

    public const string HintName = "DuplicateOfAttribute.g.cs";

    public const string Text = """
                               // <auto-generated/>
                               #nullable enable

                               namespace ReadyM.Api.Generators
                               {
                                   /// <summary>
                                   /// Marks a partial struct as a copy of another struct under a different name.
                                   ///
                                   /// The generator emits the source struct's members into the other half of this partial. Anything the
                                   /// marked struct declares itself wins: redeclare a member to replace the copied one, or add new members
                                   /// to extend the duplicate.
                                   /// </summary>
                                   [global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
                                   internal sealed class DuplicateOfAttribute : global::System.Attribute
                                   {
                                       public DuplicateOfAttribute(global::System.Type source)
                                       {
                                           Source = source;
                                       }

                                       /// <summary>The struct to copy. Must be declared in the same compilation.</summary>
                                       public global::System.Type Source { get; }

                                       /// <summary>Member names to leave out of the copy entirely.</summary>
                                       public string[]? Exclude { get; set; }

                                       /// <summary>Copy attributes sitting on the copied members. Default true.</summary>
                                       public bool CopyAttributes { get; set; } = true;

                                       /// <summary>Copy XML documentation on the copied members. Default true.</summary>
                                       public bool CopyDocumentation { get; set; } = true;

                                       /// <summary>
                                       /// Give the duplicate the source's interfaces, remapped to itself, so
                                       /// <c>IEquatable&lt;Source&gt;</c> becomes <c>IEquatable&lt;Duplicate&gt;</c>. Default true.
                                       /// </summary>
                                       public bool CopyInterfaces { get; set; } = true;
                                   }
                               }
                               """;
}
