using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ReadyM.Api.Generators;

/// <summary>
/// Emits the arity-based query surface of <c>EcsApi</c>: <c>Query</c> and <c>QueryWithEntity</c> for
/// one to six components, each in three flavours (plain, unmanaged state, managed state), plus the
/// matching chunk loops.
/// </summary>
[Generator]
internal class EcsQueryGenerator : IIncrementalGenerator
{
    private const string EcsApiMetadataName = "ReadyM.Relay.Server.Sdk.Ecs.EcsApi";
    private const int MaxArity = 6;
    private const int WithEntityMaxArity = 2;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Every project referencing this analyzer runs it, so emit only into the one that declares the partial class.
        var declaresEcsApi = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var ecsApi = compilation.GetTypeByMetadataName(EcsApiMetadataName);
            return ecsApi is not null &&
                   SymbolEqualityComparer.Default.Equals(ecsApi.ContainingAssembly, compilation.Assembly);
        });

        context.RegisterSourceOutput(declaresEcsApi, static (spc, declared) =>
        {
            if (declared)
                spc.AddSource("EcsApi.Queries.g.cs", Emit());
        });
    }

    private static IEnumerable<int> Slots(int n) => Enumerable.Range(1, n);

    private static string Types(int n) => string.Join(", ", Slots(n).Select(i => $"T{i}"));

    private static string StructWhere(int n) => string.Join(" ", Slots(n).Select(i => $"where T{i} : struct"));

    private static string RefParams(int n) => string.Join(", ", Slots(n).Select(i => $"ref T{i} c{i}"));

    private static string CallArgs(int n) => string.Join(", ", Slots(n).Select(i => $"ref ChunkElement(ref b{i}, i, s{i})"));

    private static void ResolveIds(StringBuilder sb, int n)
    {
        sb.AppendLine($"        var ids = stackalloc int[{n}];");
        foreach (var i in Slots(n))
            sb.AppendLine($"        ids[{i - 1}] = _componentIds.Resolve<T{i}>();");
    }

    private static void ChunkBases(StringBuilder sb, int n)
    {
        foreach (var i in Slots(n))
            sb.AppendLine($"        ref var b{i} = ref ChunkBase<T{i}>(comps[{i - 1}]);");
        foreach (var i in Slots(n))
            sb.AppendLine($"        var s{i} = comps[{i - 1}].Stride;");
    }

    private static string Emit()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using ReadyM.Api.Multiplayer.Interop;");
        sb.AppendLine();
        sb.AppendLine("namespace ReadyM.Relay.Server.Sdk.Ecs;");
        sb.AppendLine();
        sb.AppendLine("public partial class EcsApi");
        sb.AppendLine("{");

        for (var n = 1; n <= WithEntityMaxArity; n++)
            AppendWithEntityDelegate(sb, n);

        for (var n = 1; n <= WithEntityMaxArity; n++)
            AppendWithEntity(sb, n);

        for (var n = 1; n <= MaxArity; n++)
            AppendArity(sb, n);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendWithEntityDelegate(StringBuilder sb, int n)
    {
        sb.AppendLine("    /// <exclude />");
        sb.AppendLine($"    public delegate void EmbedForEachEntity<{Types(n)}>({RefParams(n)}, int entityId)");
        sb.AppendLine($"        {StructWhere(n)};");
        sb.AppendLine();
    }

    private static void AppendWithEntity(StringBuilder sb, int n)
    {
        var t = Types(n);
        var w = StructWhere(n);

        sb.AppendLine($"    private static unsafe void IterateChunkWithIds<{t}>(IntPtr ids, ChunkComponent* comps, int n, int count)");
        sb.AppendLine($"        {w}");
        sb.AppendLine("    {");
        sb.AppendLine($"        var cb = (EmbedForEachEntity<{t}>)_tlsState.Callback!;");
        sb.AppendLine("        var idPtr = (int*)ids;");
        ChunkBases(sb, n);
        sb.AppendLine();
        sb.AppendLine("        for (var i = 0; i < count; i++)");
        sb.AppendLine($"            cb({CallArgs(n)}, idPtr[i]);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public unsafe void QueryWithEntity<{t}>(EmbedForEachEntity<{t}> callback)");
        sb.AppendLine($"        {w}");
        sb.AppendLine("    {");
        ResolveIds(sb, n);
        sb.AppendLine();
        sb.AppendLine("        _tlsState.Callback = callback;");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            _query(ids, {n}, static (entityIds, comps, n, count) => IterateChunkWithIds<{t}>(entityIds, comps, n, count));");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            _tlsState.Callback = null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendArity(StringBuilder sb, int n)
    {
        var t = Types(n);
        var w = StructWhere(n);
        var p = RefParams(n);
        var call = CallArgs(n);

        sb.AppendLine("    /// <exclude />");
        sb.AppendLine($"    public delegate void EmbedForEach<{t}>({p})");
        sb.AppendLine($"        {w};");
        sb.AppendLine();
        sb.AppendLine("    /// <exclude />");
        sb.AppendLine($"    public delegate void EmbedForEachState<{t}, TState>({p}, ref TState state)");
        sb.AppendLine($"        {w};");
        sb.AppendLine();
        sb.AppendLine("    /// <exclude />");
        sb.AppendLine($"    public delegate void EmbedForEachStateManaged<{t}, in TState>({p}, TState state)");
        sb.AppendLine($"        {w}");
        sb.AppendLine("        where TState : class;");
        sb.AppendLine();

        sb.AppendLine($"    private static unsafe void IterateChunk<{t}>(IntPtr ids, ChunkComponent* comps, int n, int count)");
        sb.AppendLine($"        {w}");
        sb.AppendLine("    {");
        sb.AppendLine($"        var cb = (EmbedForEach<{t}>)_tlsState.Callback!;");
        ChunkBases(sb, n);
        sb.AppendLine();
        sb.AppendLine("        for (var i = 0; i < count; i++)");
        sb.AppendLine($"            cb({call});");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    private static unsafe void IterateChunkState<{t}, TState>(IntPtr ids, ChunkComponent* comps, int n, int count)");
        sb.AppendLine($"        {w} where TState : unmanaged");
        sb.AppendLine("    {");
        sb.AppendLine($"        var cb = (EmbedForEachState<{t}, TState>)_tlsState.Callback!;");
        sb.AppendLine("        var sp = (TState*)_tlsState.State;");
        ChunkBases(sb, n);
        sb.AppendLine();
        sb.AppendLine("        for (var i = 0; i < count; i++)");
        sb.AppendLine($"            cb({call}, ref *sp);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    private static unsafe void IterateChunkManagedState<{t}, TState>(IntPtr ids, ChunkComponent* comps, int n, int count)");
        sb.AppendLine($"        {w} where TState : class");
        sb.AppendLine("    {");
        sb.AppendLine($"        var cb = (EmbedForEachStateManaged<{t}, TState>)_tlsState.Callback!;");
        sb.AppendLine("        var ms = (TState)_tlsState.ManagedState!;");
        ChunkBases(sb, n);
        sb.AppendLine();
        sb.AppendLine("        for (var i = 0; i < count; i++)");
        sb.AppendLine($"            cb({call}, ms);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public unsafe void Query<{t}>(EmbedForEach<{t}> callback)");
        sb.AppendLine($"        {w}");
        sb.AppendLine("    {");
        ResolveIds(sb, n);
        sb.AppendLine();
        sb.AppendLine("        _tlsState.Callback = callback;");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            _query(ids, {n}, static (entityIds, comps, n, count) => IterateChunk<{t}>(entityIds, comps, n, count));");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            _tlsState.Callback = null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public unsafe void Query<{t}, TState>(TState state, EmbedForEachStateManaged<{t}, TState> callback)");
        sb.AppendLine($"        {w} where TState : class");
        sb.AppendLine("    {");
        ResolveIds(sb, n);
        sb.AppendLine();
        sb.AppendLine("        _tlsState.Callback = callback;");
        sb.AppendLine("        _tlsState.ManagedState = state;");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            _query(ids, {n}, static (entityIds, comps, n, count) => IterateChunkManagedState<{t}, TState>(entityIds, comps, n, count));");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            _tlsState.Callback = null;");
        sb.AppendLine("            _tlsState.ManagedState = null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public unsafe void Query<{t}, TState>(ref TState state, EmbedForEachState<{t}, TState> callback)");
        sb.AppendLine($"        {w} where TState : unmanaged");
        sb.AppendLine("    {");
        ResolveIds(sb, n);
        sb.AppendLine();
        sb.AppendLine("        fixed (TState* sp = &state)");
        sb.AppendLine("        {");
        sb.AppendLine("            _tlsState.Callback = callback;");
        sb.AppendLine("            _tlsState.State = (IntPtr)sp;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                _query(ids, {n}, static (entityIds, comps, n, count) => IterateChunkState<{t}, TState>(entityIds, comps, n, count));");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                _tlsState.Callback = null;");
        sb.AppendLine("                _tlsState.State = IntPtr.Zero;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
