using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
internal class InteropTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, nameAndContent) =>
        {
            spc.AddSource($"{nameAndContent.Name}.InteropId.g.cs", nameAndContent.Code);
        });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl &&
               structDecl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "InteropType" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var node = (StructDeclarationSyntax)context.Node;
        var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
        var symbol = model.GetDeclaredSymbol(node) as INamedTypeSymbol;

        var ns = symbol?.ContainingNamespace.ToDisplayString() ?? "Interop";
        var name = symbol?.Name ?? "UnknownStruct";

        var code = $@"// <auto-generated/>

using ReadyM.Api.Interop.Registry;

namespace {ns};

public partial struct {name} : IInteropType
{{
    public static int Id;
    public int GetClassId() => Id;
}}
";
        return (name, code);
    }
}
