using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public class NetSerializableGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, nameAndContent) => { spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code); });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is TypeDeclarationSyntax { AttributeLists.Count: > 0 } typeDecl &&
               // structDecl.Modifiers.Any(m => m.Text == "partial") &&
               typeDecl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "DeriveINetSerializable" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var node = context.Node;

        var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
        var symbol = model.GetDeclaredSymbol(node) as INamedTypeSymbol;

        var name = symbol!.Name;
        var source = GenerateINetSerializableImpl(symbol);
        return (name, source);
    }

    private bool IsINetSerializable(ITypeSymbol type)
    {
        const string fullName = "LiteNetLib.Utils.INetSerializable";
        return type.AllInterfaces.Any(i => i.ContainingNamespace.ToDisplayString() + "." + i.Name == fullName);
    }

    private string GenerateINetSerializableImpl(INamedTypeSymbol symbol)
    {
        var info = GeneratorHelper.GetSymbolInfo(symbol, requireFields: true, requirePublic: true);

        var sb = new StringBuilder($@"
// <auto-generated/>

using System.Diagnostics.Contracts;
using LiteNetLib.Utils;

namespace {info.Namespace};

public partial struct {info.Name}
{{
");
        var usePutGet = new bool[info.Fields.Length];
        var useSerialize = new bool[info.Fields.Length];
        var isEnum = new bool[info.Fields.Length];
        var enumBaseType = new SpecialType[info.Fields.Length];

        for (var i = 0; i < info.Fields.Length; i++)
        {
            usePutGet[i] = SerializationHelper.IsSerializablePrimitive(info.Fields[i].Type.SpecialType);
            useSerialize[i] = IsINetSerializable(info.Fields[i].Type);
            isEnum[i] = info.Fields[i].Type.TypeKind == TypeKind.Enum;

            if (isEnum[i])
            {
                enumBaseType[i] = SerializationHelper.GetEnumBaseType(info.Fields[i].Type);
            }
        }

        sb.AppendLine("""
                          [Pure]
                          public void Serialize(NetDataWriter writer)
                          {
                      """);

        for (var i = 0; i < info.Fields.Length; i++)
        {
            var field = info.Fields[i];

            if (isEnum[i])
            {
                var baseType = SerializationHelper.GetSpecialTypeCSharpName(enumBaseType[i]);
                sb.AppendLine($"        writer.Put(({baseType}){field.Name});");
            }
            else if (usePutGet[i])
            {
                sb.AppendLine($"        writer.Put({field.Name});");
            }
            else if (useSerialize[i])
            {
                sb.AppendLine($"        {field.Name}.Serialize(writer);");
            }
            else
            {
                sb.AppendLine($"        #error Cannot serialize field {field.Name} of type {field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}");
            }
        }

        sb.AppendLine("    }\n");

        sb.AppendLine("""
                          public void Deserialize(NetDataReader reader)
                          {
                      """);

        if (info.UseCons)
        {
            sb.AppendLine($"        #error Cannot deserialize {info.Name} using a constructor, INetSerializable requires instance methods");
        }
        else
        {
            for (var i = 0; i < info.Fields.Length; i++)
            {
                var field = info.Fields[i];

                if (isEnum[i])
                {
                    var getMethod = SerializationHelper.GetDeserializationMethod(enumBaseType[i]);
                    sb.AppendLine($"        {field.Name} = ({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})reader.{getMethod}();");
                }
                else if (usePutGet[i])
                {
                    var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                    sb.AppendLine($"        {field.Name} = reader.{getMethod}();");
                }
                else if (useSerialize[i])
                {
                    sb.AppendLine($"        {field.Name}.Deserialize(reader);");
                }
                else
                {
                    sb.AppendLine($"        #error Cannot deserialize {field.Name} of type {field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}");
                }
            }
        }
        
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
