using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public class NetworkedComponentGenerator : IIncrementalGenerator
{
    private const string FloatComparisonEpsilon = "0.1f";
    private const string VectorComparisonEpsilon = "0.01f";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var codeProvider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform);

        context.RegisterSourceOutput(codeProvider, (spc, nameAndContent) => { spc.AddSource($"{nameAndContent.Name}.g.cs", nameAndContent.Code); });
    }

    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is StructDeclarationSyntax { AttributeLists.Count: > 0 } structDecl &&
               structDecl.Modifiers.Any(m => m.Text == "partial")
               && structDecl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "NetworkedComponent" });
    }

    private (string Name, string Code) Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var node = context.Node;

        var model = context.SemanticModel.Compilation.GetSemanticModel(node.SyntaxTree);
        var symbol = model.GetDeclaredSymbol(node) as INamedTypeSymbol;

        var name = symbol!.Name;
        var source = GenerateNetworkedComponent(symbol);
        return (name, source);
    }

    private string GenerateNetworkedComponent(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace.ToDisplayString();
        var name = symbol.Name;
        var fields = symbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.DeclaredAccessibility == Accessibility.Private && !f.IsStatic)
            .ToArray();

        string maskType;
        string maskTypeRead;

        switch (fields.Length)
        {
            case < sizeof(byte) * 8:
                maskType = "byte";
                maskTypeRead = "GetByte";
                break;
            case < sizeof(ushort) * 8:
                maskType = "ushort";
                maskTypeRead = "GetUShort";
                break;
            case < sizeof(uint) * 8:
                maskType = "uint";
                maskTypeRead = "GetUInt";
                break;
            case < sizeof(ulong) * 8:
                maskType = "ulong";
                maskTypeRead = "GetULong";
                break;
            default:
                throw new InvalidOperationException($"NetworkedComponent {name} has more than 64 fields. This is not supported.");
        }

        var sb = new StringBuilder($@"
// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using LiteNetLib.Utils;
using ReadyM.Api.Generators;
using ReadyM.Api.Multiplayer;
using ReadyM.Api.Multiplayer.Extensions;
using ReadyM.Api.Multiplayer.ECS.Components;
using ReadyM.Relay.Common;

namespace {ns}
{{
    public partial struct {name} : INetworkedComponent
    {{
        private {maskType} _dirtyMask;

");

        for (int i = 0; i < fields.Length; i++)
        {
            var field = fields[i];
            var type = field.Type.ToDisplayString();
            var propertyName = char.ToUpper(field.Name[1]) + field.Name.Substring(2);

            sb.AppendLine($"        public {type} {propertyName}");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => {field.Name};");

            if (field.Type.SpecialType is SpecialType.System_Single or SpecialType.System_Double)
            {
                sb.AppendLine($"            set {{ if (Math.Abs({field.Name} - value) > {FloatComparisonEpsilon}) {{ {field.Name} = value; _dirtyMask |= ({maskType})1 << {i}; }} }}");
            }
            else if (field.Type.Name == "Vector3")
            {
                sb.AppendLine($"            set {{ if (Vector3.DistanceSquared({field.Name}, value) > {VectorComparisonEpsilon}) {{ {field.Name} = value; _dirtyMask |= ({maskType})1 << {i}; }} }}");
            }
            else if (field.Type.Name == "Vector2")
            {
                sb.AppendLine($"            set {{ if (Vector2.DistanceSquared({field.Name}, value) > {VectorComparisonEpsilon}) {{ {field.Name} = value; _dirtyMask |= ({maskType})1 << {i}; }} }}");
            }
            else
            {
                sb.AppendLine($"            set {{ if ({field.Name} != value) {{ {field.Name} = value; _dirtyMask |= ({maskType})1 << {i}; }} }}");
            }

            sb.AppendLine("        }\n");
        }

        bool[] usePutGet = new bool[fields.Length];
        for (int i = 0; i < fields.Length; i++)
        {
            usePutGet[i] = SerializationHelper.IsSerializablePrimitive(fields[i].Type.SpecialType);
        }

        sb.AppendLine($$"""
                                public void Serialize(NetDataWriter writer)
                                {
                        """);

        for (int i = 0; i < fields.Length; i++)
        {
            var field = fields[i];

            if (usePutGet[i])
            {
                sb.AppendLine($"            writer.Put({field.Name});");
            }
            else
            {
                sb.AppendLine($"            {field.Name}.Serialize(writer);");
            }
        }

        sb.AppendLine("        }\n");
        
        sb.AppendLine("        public void Deserialize(NetDataReader reader)");
        sb.AppendLine("        {");

        for (int i = 0; i < fields.Length; i++)
        {
            var field = fields[i];
            var propertyName = char.ToUpper(field.Name[1]) + field.Name.Substring(2);

            if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            {propertyName} = reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            {{ {field.Name}.Deserialize(reader); _dirtyMask |= ({maskType})1 << {i}; }}");
            }
        }

        sb.AppendLine("        }\n");

        sb.AppendLine("""
                              public void WriteDelta(NetDataWriter writer)
                              {
                                  var mask = _dirtyMask;
                                  writer.Put(mask);
                      """);

        for (int i = 0; i < fields.Length; i++)
        {
            var field = fields[i];

            if (usePutGet[i])
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) writer.Put({field.Name});");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {field.Name}.Serialize(writer);");
            }
        }

        sb.AppendLine("        }\n");

        sb.AppendLine("        public void ReadDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        for (int i = 0; i < fields.Length; i++)
        {
            var field = fields[i];
            var propertyName = char.ToUpper(field.Name[1]) + field.Name.Substring(2);

            if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {propertyName} = reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {{ {field.Name}.Deserialize(reader); _dirtyMask |= ({maskType})1 << {i}; }}");
            }
        }

        sb.AppendLine("        }\n");
        sb.AppendLine("        public void SkipDelta(NetDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var mask = reader.{maskTypeRead}();");

        for (int i = 0; i < fields.Length; i++)
        {
            var field = fields[i];

            if (usePutGet[i])
            {
                var getMethod = SerializationHelper.GetDeserializationMethod(field.Type.SpecialType);
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) reader.{getMethod}();");
            }
            else
            {
                sb.AppendLine($"            if ((mask & (({maskType})1 << {i})) != 0) {{ var dummy = default({field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}); dummy.Deserialize(reader); }}");
            }
        }

        sb.AppendLine("        }\n");
        sb.AppendLine("        public void ClearDirty() => _dirtyMask = 0;");
        sb.AppendLine("        public bool IsDirty => _dirtyMask != 0;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}