using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
public class RpcEventGenerator : IIncrementalGenerator
{
    private const string UserIdTypeName = "PlayerId";
    private const string SenderParameterName = "__sender";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rpcMethods = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(m => m is not null)
            .Collect();

        context.RegisterSourceOutput(rpcMethods, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is MethodDeclarationSyntax method &&
        method.AttributeLists.Count > 0;

    private static RpcMethodInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not MethodDeclarationSyntax methodSyntax)
            return null;

        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol;

        // Check for [RpcEvent] attribute via semantic model
        var rpcAttr = methodSymbol?.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is "RpcEventAttribute" or "RpcEvent");

        if (rpcAttr == null)
            return null;

        var attributeSyntax = rpcAttr
            .ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        var args = attributeSyntax.ArgumentList!.Arguments;

        var constants = args.Select(arg => context.SemanticModel.GetOperation(arg.Expression)?.ConstantValue.Value)
            .Where(val => val is not null)
            .Select(x => x!.ToString())
            .ToArray();

        return new RpcMethodInfo(methodSymbol, constants);
    }

    private static void GenerateSources(SourceProductionContext context, ImmutableArray<RpcMethodInfo?> rawMethods)
    {
        var methods = rawMethods
            .Where(m => m is not null)
            .Select(m => m!)
            .OrderBy(m => m.Symbol.ToDisplayString()) // Deterministic order
            .ToList();

        var groupsByClass = methods.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default);

        int eventCode = 0;

        foreach (var group in groupsByClass)
        {
            var minEventCode = eventCode;
            var maxEventCode = eventCode;
            
            var classSymbol = group.Key;
            var ns = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var fullClassName = classSymbol.ToDisplayString();

            var sb = new StringBuilder($$"""
                                         // <auto-generated/>
                                         using System;
                                         using LiteNetLib;
                                         using LiteNetLib.Utils;
                                         using ReadyM.Api.Multiplayer;
                                         using ReadyM.Api.Multiplayer.Protocol;
                                         using ReadyM.Api.Multiplayer.Protocol.Enums;
                                         using ReadyM.Relay.Common.Protocol;

                                         namespace {{ns}}
                                         {
                                             public partial class {{className}}
                                             {

                                         """);

            var dispatchCases = new StringBuilder();

            foreach (var method in group)
            {
                if (eventCode > byte.MaxValue)
                {
                    sb.AppendLine("""#error "Too many RPC events; limit is 256." """);
                    break;
                }

                var methodSymbol = method.Symbol;
                var methodName = methodSymbol.Name;

                var parameters = methodSymbol.Parameters;

                bool valid = false;
                bool hasSender = false;
                bool hasPayload = false;
                bool isSerializablePrimitive = false;
                bool isNetSerializable = false;
                ITypeSymbol? payloadType = null;

                if (parameters.Length == 0)
                {
                    // void OnX()
                    valid = true;
                }
                else if (parameters.Length == 1)
                {
                    if (parameters[0].Type.Name == UserIdTypeName && parameters[0].Name == SenderParameterName)
                    {
                        // void OnX(ushort __sender)
                        valid = true;
                        hasSender = true;
                    }
                    else if (parameters[0].Type.AllInterfaces.Any(i => i.Name == "INetSerializable"))
                    {
                        // void OnX(T payload)
                        valid = true;
                        hasPayload = true;
                        isNetSerializable = true;
                        payloadType = parameters[0].Type;
                    }
                    else if (SerializationHelper.IsSerializablePrimitive(parameters[0].Type.SpecialType))
                    {
                        // int, string, etc.
                        valid = true;
                        hasPayload = true;
                        isSerializablePrimitive = true;
                        payloadType = parameters[0].Type;
                    }
                    else
                    {
                        valid = true;
                        hasPayload = true;
                        payloadType = parameters[0].Type; // T must be registered in RelayClient
                    }
                }
                else if (parameters.Length == 2)
                {
                    if (parameters[0].Type.Name == UserIdTypeName && parameters[0].Name == SenderParameterName &&
                        parameters[1].Type.AllInterfaces.Any(i => i.Name == "INetSerializable"))
                    {
                        // void OnX(ushort __sender, T payload)
                        valid = true;
                        hasSender = true;
                        hasPayload = true;
                        isNetSerializable = true;
                        payloadType = parameters[1].Type;
                    }
                    else if (parameters[0].Type.Name == UserIdTypeName && parameters[0].Name == SenderParameterName &&
                             SerializationHelper.IsSerializablePrimitive(parameters[1].Type.SpecialType))
                    {
                        // void OnX(ushort __sender, int payload)
                        valid = true;
                        hasSender = true;
                        isSerializablePrimitive = true;
                        hasPayload = true;
                        payloadType = parameters[1].Type;
                    }
                    else if (parameters[0].Type.Name == UserIdTypeName && parameters[0].Name == SenderParameterName)
                    {
                        // void OnX(ushort __sender, T payload), T must be registered in RelayClient
                        valid = true;
                        hasSender = true;
                        hasPayload = true;
                        payloadType = parameters[1].Type;
                    }
                }

                if (!valid)
                {
                    sb.AppendLine($"""#error "Invalid RPC handler '{methodName}'. Supported signatures: void OnX(), void OnX(ushort __sender), void OnX(T), or void OnX(ushort __sender, T) where T is either INetSerializable, or primitive" """);
                    continue;
                }

                var shortName = methodName.StartsWith("On") ? methodName.Substring(2) : methodName;

                var sendMethod = $"Send{shortName}";
                var argList = hasPayload ? $"{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} payload" : "";

                var relayMode = method.AttributeParams.FirstOrDefault(); // enum

                if (relayMode is null)
                {
                    sb.AppendLine($"""#warning "RelayMode must be specified in RpcEvent attribute for method '{methodName}'" """);
                    relayMode = "0"; // default
                }

                var eventCaching = "0"; // default
                if (method.AttributeParams.Length == 2)
                {
                    // EventCaching enum
                    eventCaching = method.AttributeParams[1];
                }

                sb.AppendLine($$"""
                                        public void {{sendMethod}}({{argList}})
                                        {
                                            var writer = new NetDataWriter();
                                            writer.PutCustomEventHeader({{eventCode}}, RelayClient.LocalPlayer.PlayerId, (RelayMode){{relayMode}}, (EventCaching){{eventCaching}});
                                """);

                if (hasPayload)
                {
                    if (isSerializablePrimitive)
                    {
                        sb.AppendLine("            writer.Put(payload);");
                    }
                    else if (isNetSerializable)
                    {
                        sb.AppendLine("            payload.Serialize(writer);");
                    }
                    else
                    {
                        sb.AppendLine("            Serializer.SerializeObject(writer, payload);");
                    }
                }

                sb.AppendLine("""
                                          RelayClient.SendMessageToServer(writer, DeliveryMethod.ReliableOrdered);
                                      }

                              """);

                dispatchCases.AppendLine($"            case {eventCode}:\n            {{");

                if (hasPayload)
                {
                    if (isSerializablePrimitive)
                    {
                        var getMethod = SerializationHelper.GetDeserializationMethod(payloadType!.SpecialType);
                        dispatchCases.AppendLine($"                var payload = reader.{getMethod}();");
                    }
                    else if (isNetSerializable)
                    {
                        dispatchCases.AppendLine($"                var payload = new {payloadType}();");
                        dispatchCases.AppendLine( "                payload.Deserialize(reader);");
                    }
                    else
                    {
                        dispatchCases.AppendLine($"                var payload = Serializer.DeserializeObject<{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(reader);");
                    }
                }

                dispatchCases.Append("                ");
                dispatchCases.Append(methodName);
                dispatchCases.Append('(');

                if (hasSender)
                    dispatchCases.Append("header.Sender");

                if (hasSender && hasPayload)
                    dispatchCases.Append(", ");

                if (hasPayload)
                    dispatchCases.Append("payload");

                dispatchCases.AppendLine(");");
                dispatchCases.AppendLine("                break;");
                dispatchCases.AppendLine("            }");

                maxEventCode = eventCode;
                eventCode++;
            }

            // Emit OnCustomEvent override
            sb.AppendLine($$"""
                                    protected void OnCustomEvent(CustomEventHeader header, NetDataReader reader)
                                    {
                                        switch (header.EventCode)
                                        {
                            {{dispatchCases}}
                                            default:
                                                throw new InvalidOperationException($"Unknown event code: {header.EventCode}");
                                        }
                                    }
                                    
                                    protected void InitRpc()
                                    {
                                        RelayClient[{{minEventCode}}, {{maxEventCode}}].OnCustomEvent += OnCustomEvent;
                                    }
                                    
                                    protected void DeInitRpc()
                                    {
                                        RelayClient[{{minEventCode}}, {{maxEventCode}}].OnCustomEvent -= OnCustomEvent;
                                    }
                            """);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var hintName = $"{fullClassName.Replace('.', '_')}_RpcEvents.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }

    private sealed class RpcMethodInfo(IMethodSymbol symbol, string[] attr)
    {
        public IMethodSymbol Symbol { get; } = symbol;
        public string[] AttributeParams { get; } = attr;
    }
}