using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

/// <summary>
/// Runs on the shared (Common) project. Finds classes marked [ServerRpcContracts],
/// reads their partial void method stubs (one per RPC), sorts them alphabetically,
/// and emits two files:
///   1. Partial implementations (required by C# partial method rules).
///   2. ServerRpcManifest - the single source of truth for code assignment.
///
/// Both the server plugin and the client mod reference the compiled Common assembly,
/// so they share this manifest without independently computing anything.
/// </summary>
[Generator]
internal class ServerRpcContractGenerator : IIncrementalGenerator
{
    private const string ContractsAttributeName = "ServerRpcContractsAttribute";
    private const string ManifestClassName = "ServerRpcManifest";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contractClasses = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(x => x is not null)
            .Collect();

        context.RegisterSourceOutput(contractClasses, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is ClassDeclarationSyntax cls && cls.AttributeLists.Count > 0;

    private static ContractClassInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not ClassDeclarationSyntax classSyntax)
            return null;

        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
        if (classSymbol is null)
            return null;

        var hasAttr = classSymbol.GetAttributes()
            .Any(a => a.AttributeClass?.Name is "ServerRpcContractsAttribute" or "ServerRpcContracts");
        if (!hasAttr)
            return null;

        // Collect the partial void method stubs. Their names are the RPC event names.
        var methods = classSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.IsPartialDefinition && m.ReturnsVoid && m.IsStatic)
            .OrderBy(m => m.Name)
            .ToList();

        return new ContractClassInfo(classSymbol, methods);
    }

    private static void GenerateSources(
        SourceProductionContext context,
        ImmutableArray<ContractClassInfo?> rawClasses)
    {
        var classes = rawClasses.Where(c => c is not null).Select(c => c!).ToList();
        if (classes.Count == 0)
            return;

        // Multiple [ServerRpcContracts] classes are allowed (e.g. one per feature area),
        // but they all feed into a single flat manifest. Detect name collisions across them.
        var allMethods = classes
            .SelectMany(c => c.Methods.Select(m => (Class: c, Method: m)))
            .OrderBy(x => x.Method.Name)
            .ToList();

        var duplicates = allMethods
            .GroupBy(x => x.Method.Name)
            .Where(g => g.Count() > 1)
            .ToList();

        foreach (var dup in duplicates)
        {
            foreach (var (cls, method) in dup)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "SRPC001", "Duplicate RPC name",
                        "RPC name '{0}' is declared more than once across [ServerRpcContracts] classes.",
                        "ServerRpc", DiagnosticSeverity.Error, true),
                    method.Locations.FirstOrDefault(),
                    method.Name));
            }
        }

        // Use the namespace of the first contracts class as the manifest namespace.
        // All [ServerRpcContracts] classes in a plugin should share the same root namespace.
        var manifestNs = classes[0].Symbol.ContainingNamespace.ToDisplayString();

        // Partial implementations (required by C# for public/protected partial methods)
        foreach (var cls in classes)
        {
            EmitPartialImplementations(context, cls);
        }

        // The manifest: single source of truth for TotalEventCount, Offset, and {Name}Code.
        EmitManifest(context, manifestNs, allMethods.Select(x => x.Method).ToList());
    }

    private static void EmitPartialImplementations(
        SourceProductionContext context,
        ContractClassInfo cls)
    {
        var ns = cls.Symbol.ContainingNamespace.ToDisplayString();
        var className = cls.Symbol.Name;
        var access = cls.Symbol.DeclaredAccessibility.ToString().ToLower();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"{access} static partial class {className}");
        sb.AppendLine("{");

        foreach (var method in cls.Methods)
        {
            var paramList = string.Join(", ", method.Parameters.Select(
                p => $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));
            sb.AppendLine($"    public static partial void {method.Name}({paramList}) {{ }}");
        }

        sb.AppendLine("}");

        context.AddSource(
            $"{cls.Symbol.ToDisplayString().Replace('.', '_')}_Contracts.g.cs",
            sb.ToString());
    }

    private static void EmitManifest(
        SourceProductionContext context,
        string ns,
        List<IMethodSymbol> methods)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using ReadyM.Api.Multiplayer.Protocol;");
        sb.AppendLine("using ReadyM.Api.Multiplayer.Protocol.Enums;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Single source of truth for server RPC code assignment in this plugin.");
        sb.AppendLine("/// Referenced by both the server handler and client event generators.");
        sb.AppendLine("/// Set <see cref=\"Offset\"/> once at plugin startup before any InitRpc() runs:");
        sb.AppendLine("/// <code>");
        sb.AppendLine($"///   {ManifestClassName}.Offset = offsetProvider.GetNextOffset({ManifestClassName}.TotalEventCount);");
        sb.AppendLine("/// </code>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {ManifestClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const byte TotalEventCount = {methods.Count};");
        sb.AppendLine();
        sb.AppendLine("    public static byte Offset { get; set; }");
        sb.AppendLine();

        for (var i = 0; i < methods.Count; i++)
        {
            var name = methods[i].Name;
            sb.AppendLine($"    // Alphabetical rank {i} - code is stable as long as this name is not renamed or removed.");
            sb.AppendLine($"    public static RelayMessageCode {name}Code =>");
            sb.AppendLine($"        (RelayMessageCode)(RelayMessageCode.MinServerRpcEvent + Offset + {i});");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource($"{ManifestClassName}.g.cs", sb.ToString());
    }

    private sealed class ContractClassInfo(INamedTypeSymbol symbol, List<IMethodSymbol> methods)
    {
        public INamedTypeSymbol Symbol { get; } = symbol;
        public List<IMethodSymbol> Methods { get; } = methods;
    }
}