using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
internal class ServerRpcEventGenerator : IIncrementalGenerator
{
    private const string ContextTypeName = "IRelayClientNetworkThreadContext";
    private const string ContextParameterName = "__context";
    private const string EventCodeTypeName = "RelayMessageCode";
    private const string EventCodeParameterName = "__eventCode";

    private const string ManifestClassName = "ServerRpcEventManifest";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serverRpcMethods = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serverRpcMethods, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is MethodDeclarationSyntax method &&
        method.AttributeLists.Count > 0;

    private static ServerRpcMethodInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not MethodDeclarationSyntax methodSyntax)
            return null;

        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodSyntax);

        var rpcAttr = methodSymbol?.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is
                "ServerRpcEventAttribute" or
                "ServerRpcEvent"
            );

        if (rpcAttr == null)
            return null;

        var attributeSyntax = rpcAttr.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        var args = attributeSyntax!.ArgumentList!.Arguments;

        var constants = args
            .Select(arg => context.SemanticModel.GetOperation(arg.Expression)?.ConstantValue.Value)
            .Where(val => val is not null)
            .Select(x => x!.ToString())
            .ToArray();

        return new ServerRpcMethodInfo(methodSymbol!, constants);
    }

    private static void GenerateSources(SourceProductionContext context,
        ImmutableArray<ServerRpcMethodInfo?> rawMethods)
    {
        var methods = rawMethods
            .Where(m => m is not null)
            .Select(m => m!)
            .OrderBy(m => m.EventName) // global alphabetical sort - this is the ID assignment
            .ToList();

        if (methods.Count == 0)
            return;

        var duplicates = methods.GroupBy(x => x.EventName)
            .Where(g => g.Count() > 1)
            .SelectMany(y => y)
            .ToList();

        foreach (var dup in duplicates)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("ERROR", "Error", "Event: {0} has a duplicate event name", "Error",
                    DiagnosticSeverity.Error, true),
                dup.Symbol.Locations[0],
                dup.EventName));
        }

        // Same algorithm as ServerRpcHandlerGenerator: alphabetical rank = code.
        // As long as [ServerRpcEvent] names match [ServerRpcHandler] names across
        // the plugin pair, both sides arrive at the same table independently.
        var codeByName = methods
            .Select(m => m.EventName)
            .Distinct()
            .Select((name, i) => (name, code: i))
            .ToDictionary(x => x.name, x => x.code);

        GenerateManifest(context, methods, codeByName);
        ProcessEvents(context, methods, codeByName);
    }

    private static void GenerateManifest(
        SourceProductionContext context,
        List<ServerRpcMethodInfo> methods,
        Dictionary<string, int> codeByName)
    {
        var ns = methods[0].Symbol.ContainingType.ContainingNamespace.ToDisplayString();

        var src = $$"""
                    // <auto-generated/>
                    namespace {{ns}};

                    /// <summary>
                    /// Plugin-level server RPC manifest for the client side, generated from all [ServerRpcEvent]
                    /// attributes in this compilation. Set <see cref="Offset"/> exactly once at plugin startup,
                    /// before calling <c>OnScopeStart()</c> on any event class, using the same
                    /// <c>ServerRpcOffsetProvider</c> instance and the same call order as the server side:
                    /// <code>
                    ///   {{ManifestClassName}}.Offset = offsetProvider.GetNextOffset({{ManifestClassName}}.TotalEventCount);
                    /// </code>
                    /// </summary>
                    internal static class {{ManifestClassName}}
                    {
                        /// <summary>
                        /// Total distinct server RPC event names in this plugin, assigned at compile time.
                        /// Must equal <c>ServerRpcHandlerManifest.TotalEventCount</c> in the paired server plugin.
                        /// </summary>
                        public const byte TotalEventCount = {{codeByName.Count}};

                        /// <summary>
                        /// Base offset within <c>RelayMessageCode.MinServerRpcEvent</c>, set once at startup.
                        /// </summary>
                        public static byte Offset { get; set; }
                    }
                    """;

        context.AddSource($"{ManifestClassName}.g.cs", src);
    }

    private static void ProcessEvents(
        SourceProductionContext context,
        List<ServerRpcMethodInfo> methods,
        Dictionary<string, int> codeByName)
    {
        var groupsByClass = methods.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default);

        foreach (var group in groupsByClass)
        {
            var classSymbol = group.Key;
            var ns = classSymbol!.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var fullClassName = classSymbol.ToDisplayString();
            var access = classSymbol.DeclaredAccessibility.ToString().ToLower();

            var sb = new StringBuilder($$"""
                                         // <auto-generated/>
                                         using System;
                                         using LiteNetLib;
                                         using LiteNetLib.Utils;
                                         using ReadyM.Api.Multiplayer;
                                         using ReadyM.Api.Multiplayer.Protocol;
                                         using ReadyM.Api.Multiplayer.Protocol.Enums;
                                         using ReadyM.Api.Multiplayer.Client;
                                         using ReadyM.Api.Multiplayer.Extensions;

                                         namespace {{ns}};

                                         {{access}} partial class {{className}}
                                         {

                                         """);

            var dispatchCases = new StringBuilder();
            var initCalls = new StringBuilder();
            var deinitCalls = new StringBuilder();

            foreach (var method in group)
            {
                var methodSymbol = method.Symbol;
                var methodName = methodSymbol.Name;

                var eventName = method.AttributeParams.FirstOrDefault();
                if (eventName is null)
                {
                    sb.AppendLine(
                        $"""#error "EventName must be specified in ServerRpcEvent attribute for method '{methodName}'" """);
                    break;
                }

                if (!codeByName.TryGetValue(eventName, out var globalCode))
                    continue;

                var parameters = methodSymbol.Parameters;

                bool valid = true;
                int? contextIndex = null;
                int? eventCodeIndex = null;
                List<(ITypeSymbol? Type, bool IsSerializablePrimitive, bool IsNetSerializable)> paramTypes = [];

                for (var i = 0; i < parameters.Length; i++)
                {
                    var param = parameters[i];
                    if (param.Name == ContextParameterName)
                    {
                        if (param.Type.Name != ContextTypeName)
                        {
                            valid = false;
                            break;
                        }

                        contextIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Name == EventCodeParameterName)
                    {
                        if (param.Type.Name != EventCodeTypeName)
                        {
                            valid = false;
                            break;
                        }

                        eventCodeIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (SerializationHelper.IsINetSerializable(param.Type))
                    {
                        paramTypes.Add((param.Type, false, true));
                    }
                    else if (SerializationHelper.IsSerializablePrimitive(param.Type.SpecialType))
                    {
                        paramTypes.Add((param.Type, true, false));
                    }
                    else
                    {
                        paramTypes.Add((param.Type, false, false));
                    }
                }

                if (!valid)
                {
                    sb.AppendLine(
                        $"""#error "Invalid server RPC handler '{methodName}'. Supported signatures: void OnX([IRelayClientNetworkThreadContext __context], [RelayMessageCode __eventCode], [T arg...]) where T is either INetSerializable, or primitive" """);
                    continue;
                }

                var codeExpr =
                    $"(RelayMessageCode)(RelayMessageCode.MinServerRpcEvent + {ManifestClassName}.Offset + {globalCode})";

                // --- SendX (client → server) ---
                var shortName = methodName.StartsWith("On") ? methodName.Substring(2) : methodName;
                var sendMethod = $"Send{shortName}";
                var sendParamList = new StringBuilder();

                var payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i == eventCodeIndex || i == contextIndex) continue;
                    if (payloadCount > 0) sendParamList.Append(", ");
                    sendParamList.Append(paramTypes[i].Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    sendParamList.Append($" payload{payloadCount}");
                    payloadCount++;
                }

                sb.AppendLine($$"""
                                    public void {{sendMethod}}({{sendParamList}})
                                    {
                                        var message = RelayMessage.ToServer({{codeExpr}}, DeliveryMethod.ReliableOrdered);
                                        var writer = message.Writer;
                                """);

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i == eventCodeIndex || i == contextIndex) continue;
                    var (_, isSP, isNS) = paramTypes[i];
                    if (isSP) sb.AppendLine($"        writer.Put(payload{payloadCount});");
                    else if (isNS) sb.AppendLine($"        payload{payloadCount}.Serialize(writer);");
                    else sb.AppendLine($"        Serializer.SerializeObject(writer, payload{payloadCount});");
                    payloadCount++;
                }

                sb.AppendLine("""
                                      RelayClient.SendMessage(message);
                                  }

                              """);

                // --- Dispatch case (server → client receive path) ---
                dispatchCases.AppendLine($"            case {globalCode}:\n            {{");

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    var (payloadType, isSP, isNS) = paramTypes[i];
                    if (i == contextIndex || i == eventCodeIndex) continue;

                    if (isSP)
                    {
                        var getter = SerializationHelper.GetDeserializationMethod(payloadType!.SpecialType);
                        dispatchCases.AppendLine($"                var payload{payloadCount} = reader.{getter}();");
                    }
                    else if (isNS)
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = new {payloadType}();");
                        dispatchCases.AppendLine($"                payload{payloadCount}.Deserialize(reader);");
                    }
                    else
                    {
                        dispatchCases.AppendLine(
                            $"                var payload{payloadCount} = Serializer.DeserializeObject<{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(reader);");
                    }

                    payloadCount++;
                }

                dispatchCases.Append("                ");
                dispatchCases.Append(methodName);
                dispatchCases.Append('(');
                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i > 0) dispatchCases.Append(", ");
                    if (i == eventCodeIndex)
                    {
                        dispatchCases.Append("header.EventCode");
                        continue;
                    }

                    if (i == contextIndex)
                    {
                        dispatchCases.Append("context");
                        continue;
                    }

                    dispatchCases.Append($"payload{payloadCount}");
                    payloadCount++;
                }

                dispatchCases.AppendLine(");");
                dispatchCases.AppendLine("                break;");
                dispatchCases.AppendLine("            }");

                // IRelayClient has single-code overloads; use them since codes within this class
                // may not be contiguous (other classes' events interleave alphabetically).
                if (initCalls.Length > 0) initCalls.AppendLine();
                initCalls.Append($"        RelayClient.AddServerRpcMessageHandler({codeExpr}, OnServerEvent);");
                if (deinitCalls.Length > 0) deinitCalls.AppendLine();
                deinitCalls.Append($"        RelayClient.RemoveServerRpcMessageHandler({codeExpr}, OnServerEvent);");
            }

            sb.AppendLine($$"""
                                protected void OnServerEvent(ServerEventHeader header, NetDataReader reader)
                                {
                                    switch ((int)header.EventCode - (int)RelayMessageCode.MinServerRpcEvent - {{ManifestClassName}}.Offset)
                                    {
                            {{dispatchCases}}
                                        default:
                                            throw new InvalidOperationException($"Unknown event code: {header.EventCode}");
                                    }
                                }
                                    
                                protected override void InitRpc()
                                {
                            {{initCalls}}
                                }
                                    
                                protected override void DeInitRpc()
                                {
                            {{deinitCalls}}
                                }
                            """);

            sb.AppendLine("}");

            var hintName = $"{fullClassName.Replace('.', '_')}_RpcEvents.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }

    private sealed class ServerRpcMethodInfo(IMethodSymbol symbol, string[] attr)
    {
        public IMethodSymbol Symbol { get; } = symbol;
        public string[] AttributeParams { get; } = attr;
        public string EventName => AttributeParams.FirstOrDefault() ?? string.Empty;
    }
}