using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
internal class ServerRpcHandlerGenerator : IIncrementalGenerator
{
    private const string ContextTypeName = "IRelayServerNetworkThreadContext";
    private const string PlayerIdTypeName = "PlayerId";
    private const string ContextParameterName = "__context";
    private const string SenderParameterName = "__sender";
    private const string EventCodeTypeName = "RelayMessageCode";
    private const string EventCodeParameterName = "__eventCode";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serverRpcMethods = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serverRpcMethods, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is MethodDeclarationSyntax method &&
        method.AttributeLists.Count > 0;

    private static ServerRpcMethodInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not MethodDeclarationSyntax methodSyntax)
            return null;

        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodSyntax);

        var rpcAttr = methodSymbol?.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is
            "ServerRpcHandlerAttribute" or
            "ServerRpcHandler"
            );

        if (rpcAttr == null)
            return null;

        var attributeSyntax = rpcAttr
            .ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        var args = attributeSyntax!.ArgumentList!.Arguments;

        var constants = args.Select(arg => context.SemanticModel.GetOperation(arg.Expression)?.ConstantValue.Value)
            .Where(val => val is not null)
            .Select(x => x!.ToString())
            .ToArray();

        return new ServerRpcMethodInfo(methodSymbol!, constants);
    }

    private static void GenerateSources(SourceProductionContext context, ImmutableArray<ServerRpcMethodInfo?> rawMethods)
    {
        var methods = rawMethods
            .Where(m => m is not null)
            .Select(m => m!)
            .OrderBy(m => m.EventName) // Deterministic order
            .ToList();

        var handlerDuplicates = methods.GroupBy(x => x.EventName)
              .Where(g => g.Count() > 1)
              .SelectMany(y => y)
              .ToList();

        foreach (var duplicate in handlerDuplicates)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("ERROR", "Error", "Handler: {0} has a duplicate event name", "Error", DiagnosticSeverity.Error, true),
                duplicate?.Symbol?.Locations[0],
                duplicate?.EventName));
        }

        ProcessHandlers(context, methods);
    }

    private static void ProcessHandlers(SourceProductionContext context, List<ServerRpcMethodInfo?> methods)
    {
        var groupsByClass = methods.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default);

        byte baseEventCode = 0;

        foreach (var group in groupsByClass)
        {
            var classSymbol = group.Key;
            var ns = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var fullClassName = classSymbol.ToDisplayString();
            var access = classSymbol.DeclaredAccessibility.ToString().ToLower(); // public, internal, etc.

            var sb = new StringBuilder($$"""
                                         // <auto-generated/>
                                         using System;
                                         using LiteNetLib;
                                         using LiteNetLib.Utils;
                                         using ReadyM.Api.Multiplayer.Protocol;
                                         using ReadyM.Api.Multiplayer.Protocol.Enums;
                                         using ReadyM.Relay;
                                         using ReadyM.Relay.Server.Rpc;
                                         
                                         namespace {{ns}};
                                         
                                         {{access}} partial class {{className}}
                                         {

                                         """);

            var dispatchCases = new StringBuilder();
            var initCalls = new StringBuilder();
            var deinitCalls = new StringBuilder();
            var eventCodes = new StringBuilder();

            foreach (var method in group)
            {
                var methodSymbol = method!.Symbol;
                var methodName = methodSymbol.Name;

                var eventName = method.AttributeParams.FirstOrDefault();
                if (eventName is null)
                {
                    sb.AppendLine($"""#error "EventName must be specified in ServerRpcHandler attribute for method '{methodName}'" """);
                    break;
                }
                var eventCode = $"(RelayMessageCode.MinServerRpcEvent + {baseEventCode})";

                var parameters = methodSymbol.Parameters;

                var valid = true;
                int? contextIndex = null;
                int? senderIndex = null;
                int? eventCodeIndex = null;
                List<(ITypeSymbol? Type, bool IsSerializablePrimitive, bool IsNetSerializable)> paramTypes = [];

                for (var i = 0; i < parameters.Length; i++)
                {
                    var param = parameters[i];
                    if (param.Name == ContextParameterName)
                    {
                        if (param.Type.Name != ContextTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // IRelayServerNetworkThreadContext __context
                        contextIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Name == SenderParameterName)
                    {
                        if (param.Type.Name != PlayerIdTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // PlayerId __sender
                        senderIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Name == EventCodeParameterName)
                    {
                        if (param.Type.Name != EventCodeTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // RelayMessageCode  __eventCode
                        eventCodeIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Type.AllInterfaces.Any(x => x.Name == "INetSerializable"))
                    {
                        // T payload
                        var isNetSerializable = true;
                        var payloadType = param.Type;
                        paramTypes.Add((payloadType, false, isNetSerializable));
                    }
                    else if (SerializationHelper.IsSerializablePrimitive(param.Type.SpecialType))
                    {
                        // int, string, etc.
                        var isSerializablePrimitive = true;
                        var payloadType = param.Type;
                        paramTypes.Add((payloadType, isSerializablePrimitive, false));
                    }
                    else
                    {
                        // T payload
                        var payloadType = param.Type; // T must be registered in RelayClient
                        paramTypes.Add((payloadType, false, false));
                    }
                }

                if (!valid)
                {
                    sb.AppendLine($"""#error "Invalid server RPC handler '{methodName}'. Supported signatures: void OnX([IRelayServerNetworkThreadContext __context], [PlayerId __sender], [RelayMessageCode __eventCode], [T arg...]) where T is either INetSerializable, or primitive" """);
                    continue;
                }

                dispatchCases.AppendLine($"            case {eventCode}:\n            {{");

                var payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    var (payloadType, isSerializablePrimitive, isNetSerializable) = paramTypes[i];

                    if (i == contextIndex || i == senderIndex || i == eventCodeIndex)
                        continue;
                    
                    if (isSerializablePrimitive)
                    {
                        var getMethod = SerializationHelper.GetDeserializationMethod(payloadType!.SpecialType);
                        dispatchCases.AppendLine($"                var payload{payloadCount} = reader.{getMethod}();");
                    }
                    else if (isNetSerializable)
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = new {payloadType}();");
                        dispatchCases.AppendLine($"                payload{payloadCount}.Deserialize(reader);");
                    }
                    else
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = Serializer.DeserializeObject<{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(reader);");
                    }

                    payloadCount++;
                }

                dispatchCases.Append("                ");
                dispatchCases.Append(methodName);
                dispatchCases.Append('(');

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i > 0)
                        dispatchCases.Append(", ");

                    if (i == senderIndex)
                    {
                        dispatchCases.Append("header.Sender");
                        continue;
                    }

                    if (i == eventCodeIndex)
                    {
                        dispatchCases.Append("header.EventCode");
                        continue;
                    }

                    if (i == contextIndex)
                    {
                        dispatchCases.Append("context");
                        continue;
                    }
                    
                    dispatchCases.Append($"payload{payloadCount}");
                    payloadCount++;
                }

                dispatchCases.AppendLine(");");
                dispatchCases.AppendLine("                break;");
                dispatchCases.AppendLine("            }");

                if (eventCodes.Length > 0)
                    eventCodes.AppendLine();
                eventCodes.Append($"    public readonly RelayMessageCode {eventName}Code = {eventCode};");
                if (initCalls.Length > 0)
                    initCalls.AppendLine();
                initCalls.Append($"        RelayServer.AddServerRpcMessageHandler({eventCode}, OnServerRpcEventHandler);");
                if (deinitCalls.Length > 0)
                    deinitCalls.AppendLine();
                deinitCalls.Append($"        RelayServer.RemoveServerRpcMessageHandler({eventCode}, OnServerRpcEventHandler);");
                
                baseEventCode++;
            }

            // Emit OnServerEvent
            sb.AppendLine($$"""
                            {{eventCodes}}
                                    
                                private void OnServerRpcEventHandler(IRelayServerNetworkThreadContext context, ServerEventHeader header, NetDataReader reader)
                                {
                                    switch (header.EventCode)
                                    {
                            {{dispatchCases}}
                                        default:
                                            throw new InvalidOperationException($"Unknown event code: {header.EventCode}");
                                    }
                                }
                                   
                                public override void InitRpc(RpcRelayServer rpc)
                                {
                                    base.InitRpc(rpc);
                            {{initCalls}}
                                }
                                    
                                public override void DeInitRpc()
                                {
                            {{deinitCalls}}
                                    base.DeInitRpc();
                                }
                            """);

            sb.AppendLine("}");

            var hintName = $"{fullClassName.Replace('.', '_')}_RpcHandlers.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }  

    private sealed class ServerRpcMethodInfo(IMethodSymbol symbol, string[] attr)
    {
        public IMethodSymbol Symbol { get; } = symbol;
        public string[] AttributeParams { get; } = attr;
        public string EventName => AttributeParams.FirstOrDefault() ?? string.Empty;
    }
}
