using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReadyM.Api.Generators;

[Generator]
internal class ServerRpcHandlerGenerator : IIncrementalGenerator
{
    private const string PlayerIdTypeName = "PlayerId";
    private const string SenderParameterName = "__sender";
    private const string EventCodeTypeName = "RelayMessageCode";
    private const string EventCodeParameterName = "__eventCode";

    // Name of the per-plugin manifest generated alongside the per-class files.
    // Referenced directly in generated InitRpc / DeInitRpc / SendX / {Name}Code.
    private const string ManifestClassName = "ServerRpcHandlerManifest";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serverRpcMethods = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serverRpcMethods, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is MethodDeclarationSyntax method &&
        method.AttributeLists.Count > 0;

    private static ServerRpcMethodInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not MethodDeclarationSyntax methodSyntax)
            return null;

        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodSyntax);

        var rpcAttr = methodSymbol?.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is
            "ServerRpcHandlerAttribute" or
            "ServerRpcHandler"
            );

        if (rpcAttr == null)
            return null;

        var attributeSyntax = rpcAttr.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        var args = attributeSyntax!.ArgumentList!.Arguments;

        var constants = args
            .Select(arg => context.SemanticModel.GetOperation(arg.Expression)?.ConstantValue.Value)
            .Where(val => val is not null)
            .Select(x => x!.ToString())
            .ToArray();

        return new ServerRpcMethodInfo(methodSymbol!, constants);
    }

    private static void GenerateSources(SourceProductionContext context, ImmutableArray<ServerRpcMethodInfo?> rawMethods)
    {
        var methods = rawMethods
            .Where(m => m is not null)
            .Select(m => m!)
            .OrderBy(m => m.EventName) // global alphabetical sort - this is the ID assignment
            .ToList();

        if (methods.Count == 0)
            return;

        // Duplicate check across all classes - with global assignment, any duplicate name
        // collides regardless of which class it lives in.
        var duplicates = methods.GroupBy(x => x.EventName)
            .Where(g => g.Count() > 1)
            .SelectMany(y => y)
            .ToList();

        foreach (var dup in duplicates)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("ERROR", "Error", "Handler: {0} has a duplicate event name", "Error", DiagnosticSeverity.Error, true),
                dup.Symbol.Locations[0],
                dup.EventName));
        }

        // Global code table: alphabetical rank of each unique event name = its code offset.
        // Both this generator and ServerRpcEventGenerator produce the same table for the same
        // set of names, giving stable codes regardless of how many classes each name appears in.
        var codeByName = methods
            .Select(m => m.EventName)
            .Distinct()                       // already in sorted order (methods sorted above)
            .Select((name, i) => (name, code: i))
            .ToDictionary(x => x.name, x => x.code);

        // One manifest per plugin compilation: holds TotalEventCount (const) and Offset (set at startup).
        // The caller sets Offset once before any OnScopeStart() is invoked.
        GenerateManifest(context, methods, codeByName);

        ProcessHandlers(context, methods, codeByName);
    }

    private static void GenerateManifest(
        SourceProductionContext context,
        List<ServerRpcMethodInfo> methods,
        Dictionary<string, int> codeByName)
    {
        // Use the namespace of the alphabetically-first event's class as the manifest namespace.
        // All handler classes in a plugin should share the same root namespace; if not,
        // the generated per-class files need a using for this namespace.
        var ns = methods[0].Symbol.ContainingType.ContainingNamespace.ToDisplayString();

        var src = $$"""
            // <auto-generated/>
            namespace {{ns}};

            /// <summary>
            /// Plugin-level server RPC manifest, generated from all [ServerRpcHandler] attributes
            /// in this compilation. Set <see cref="Offset"/> exactly once at plugin startup, before
            /// calling <c>OnScopeStart()</c> on any handler class:
            /// <code>
            ///   {{ManifestClassName}}.Offset = offsetProvider.GetNextOffset({{ManifestClassName}}.TotalEventCount);
            /// </code>
            /// </summary>
            internal static class {{ManifestClassName}}
            {
                /// <summary>
                /// Total distinct server RPC event names in this plugin, assigned at compile time.
                /// This is the number of event-code slots to reserve from the offset provider.
                /// </summary>
                public const byte TotalEventCount = {{codeByName.Count}};

                /// <summary>
                /// Base offset within <c>RelayMessageCode.MinServerRpcEvent</c>, set once at startup.
                /// </summary>
                public static byte Offset { get; set; }
            }
            """;

        context.AddSource($"{ManifestClassName}.g.cs", src);
    }

    private static void ProcessHandlers(
        SourceProductionContext context,
        List<ServerRpcMethodInfo> methods,
        Dictionary<string, int> codeByName)
    {
        var groupsByClass = methods.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default);

        // Group enumeration order is intentionally irrelevant now: each method carries its
        // globally-assigned code from codeByName, so the class structure does not affect IDs.
        foreach (var group in groupsByClass)
        {
            var classSymbol = group.Key;
            var ns = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var fullClassName = classSymbol.ToDisplayString();
            var access = classSymbol.DeclaredAccessibility.ToString().ToLower();

            var sb = new StringBuilder($$"""
                                         // <auto-generated/>
                                         using System;
                                         using LiteNetLib;
                                         using LiteNetLib.Utils;
                                         using ReadyM.Api.Multiplayer.Protocol;
                                         using ReadyM.Api.Multiplayer.Protocol.Enums;
                                         using ReadyM.Relay;
                                         
                                         namespace {{ns}};
                                         
                                         {{access}} partial class {{className}}
                                         {

                                         """);

            var dispatchCases = new StringBuilder();
            var eventCodes = new StringBuilder();
            var initCalls = new StringBuilder();
            var deinitCalls = new StringBuilder();

            foreach (var method in group)
            {
                var methodSymbol = method.Symbol;
                var methodName = methodSymbol.Name;

                var eventName = method.AttributeParams.FirstOrDefault();
                if (eventName is null)
                {
                    sb.AppendLine($"""#error "EventName must be specified in ServerRpcHandler attribute for method '{methodName}'" """);
                    break;
                }

                if (!codeByName.TryGetValue(eventName, out var globalCode))
                    continue; // duplicate, already reported

                var parameters = methodSymbol.Parameters;

                var valid = true;
                int? contextIndex = null;
                int? senderIndex = null;
                int? eventCodeIndex = null;
                ITypeSymbol? senderType = null;
                List<(ITypeSymbol? Type, bool IsSerializablePrimitive, bool IsNetSerializable)> paramTypes = [];

                for (var i = 0; i < parameters.Length; i++)
                {
                    var param = parameters[i];
                    if (param.Name == SenderParameterName)
                    {
                        if (param.Type.Name != PlayerIdTypeName) { valid = false; break; }
                        senderType = param.Type;
                        senderIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Name == EventCodeParameterName)
                    {
                        if (param.Type.Name != EventCodeTypeName) { valid = false; break; }
                        eventCodeIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Type.AllInterfaces.Any(x => x.Name == "INetSerializable"))
                    {
                        paramTypes.Add((param.Type, false, true));
                    }
                    else if (SerializationHelper.IsSerializablePrimitive(param.Type.SpecialType))
                    {
                        paramTypes.Add((param.Type, true, false));
                    }
                    else
                    {
                        paramTypes.Add((param.Type, false, false));
                    }
                }

                if (!valid)
                {
                    sb.AppendLine($"""#error "Invalid server RPC handler '{methodName}'. Supported signatures: void HandleX([PlayerId __sender], [RelayMessageCode __eventCode], [T arg...]) where T is either INetSerializable, or primitive" """);
                    continue;
                }

                // Inline event code expression used throughout. globalCode is a compile-time
                // constant; Offset resolves at runtime from the manifest.
                var codeExpr = $"(RelayMessageCode)(RelayMessageCode.MinServerRpcEvent + {ManifestClassName}.Offset + {globalCode})";

                // --- SendX (server → client response) ---
                var recipientTypeDisplay = senderType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    ?? "global::ReadyM.Api.Idents.PlayerId";

                var sendParamList = new StringBuilder($"{recipientTypeDisplay} recipient");
                var sendPayloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i == senderIndex || i == eventCodeIndex || i == contextIndex)
                        continue;
                    sendParamList.Append($", {paramTypes[i].Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} payload{sendPayloadCount}");
                    sendPayloadCount++;
                }

                sb.AppendLine($$"""
                                    public void Send{{eventName}}({{sendParamList}})
                                    {
                                        var writer = new NetDataWriter();
                                        writer.Put((byte){{eventName}}Code);
                                """);

                sendPayloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i == senderIndex || i == eventCodeIndex || i == contextIndex) continue;
                    var (_, isSP, isNS) = paramTypes[i];
                    if (isSP)      sb.AppendLine($"        writer.Put(payload{sendPayloadCount});");
                    else if (isNS) sb.AppendLine($"        payload{sendPayloadCount}.Serialize(writer);");
                    else           sb.AppendLine($"        Serializer.SerializeObject(writer, payload{sendPayloadCount});");
                    sendPayloadCount++;
                }

                sb.AppendLine("""
                                      RpcApi.SendToOne(recipient, writer, DeliveryMethod.ReliableOrdered);
                                  }

                              """);

                // --- Dispatch case ---
                // Switch subtracts (MinServerRpcEvent + Offset), so cases are the bare global codes.
                // globalCode is a compile-time constant, so this remains a proper constant case label.
                dispatchCases.AppendLine($"            case {globalCode}:\n            {{");

                var payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    var (payloadType, isSP, isNS) = paramTypes[i];
                    if (i == contextIndex || i == senderIndex || i == eventCodeIndex) continue;

                    if (isSP)
                    {
                        var getter = SerializationHelper.GetDeserializationMethod(payloadType!.SpecialType);
                        dispatchCases.AppendLine($"                var payload{payloadCount} = reader.{getter}();");
                    }
                    else if (isNS)
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = new {payloadType}();");
                        dispatchCases.AppendLine($"                payload{payloadCount}.Deserialize(reader);");
                    }
                    else
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = Serializer.DeserializeObject<{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(reader);");
                    }
                    payloadCount++;
                }

                dispatchCases.Append("                ");
                dispatchCases.Append(methodName);
                dispatchCases.Append('(');
                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i > 0) dispatchCases.Append(", ");
                    if (i == senderIndex)    { dispatchCases.Append("header.Sender");    continue; }
                    if (i == eventCodeIndex) { dispatchCases.Append("header.EventCode"); continue; }
                    if (i == contextIndex)   { dispatchCases.Append("context");          continue; }
                    dispatchCases.Append($"payload{payloadCount}");
                    payloadCount++;
                }
                dispatchCases.AppendLine(");");
                dispatchCases.AppendLine("                break;");
                dispatchCases.AppendLine("            }");

                // {eventName}Code: property (not field) because Offset is a runtime value.
                if (eventCodes.Length > 0) eventCodes.AppendLine();
                eventCodes.Append($"    public RelayMessageCode {eventName}Code => {codeExpr};");

                // Per-method registration: codes within a class are not necessarily contiguous
                // (other classes' events interleave alphabetically), so we can't use a range.
                if (initCalls.Length > 0) initCalls.AppendLine();
                initCalls.Append($"        RpcApi.AddServerRpcMessageHandler({codeExpr}, OnServerRpcEventHandler);");
                if (deinitCalls.Length > 0) deinitCalls.AppendLine();
                deinitCalls.Append($"        RpcApi.RemoveServerRpcMessageHandler({codeExpr}, OnServerRpcEventHandler);");
            }

            sb.AppendLine($$"""
                            {{eventCodes}}
                                    
                                private void OnServerRpcEventHandler(ServerEventHeader header, NetDataReader reader)
                                {
                                    switch ((int)header.EventCode - (int)RelayMessageCode.MinServerRpcEvent - {{ManifestClassName}}.Offset)
                                    {
                            {{dispatchCases}}
                                        default:
                                            throw new InvalidOperationException($"Unknown event code: {header.EventCode}");
                                    }
                                }
                                   
                                protected override void InitRpc()
                                {
                            {{initCalls}}
                                }
                                    
                                protected override void DeInitRpc()
                                {
                            {{deinitCalls}}
                                }
                            """);

            sb.AppendLine("}");

            var hintName = $"{fullClassName.Replace('.', '_')}_RpcHandlers.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }

    private sealed class ServerRpcMethodInfo(IMethodSymbol symbol, string[] attr)
    {
        public IMethodSymbol Symbol { get; } = symbol;
        public string[] AttributeParams { get; } = attr;
        public string EventName => AttributeParams.FirstOrDefault() ?? string.Empty;
    }
}