using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using ReadyM.Api.Generators;

namespace ReadyM.Relay.Common.Generators;

[Generator]
public class ServerRpcEventGenerator : IIncrementalGenerator
{
    private const string ContextTypeName = "IRelayClientNetworkThreadContext";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serverRpcMethods = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serverRpcMethods, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is MethodDeclarationSyntax method &&
        method.AttributeLists.Count > 0;

    private static ServerRpcMethodInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not MethodDeclarationSyntax methodSyntax)
            return null;

        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol;

        var rpcAttr = methodSymbol?.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is
            "ServerRpcEventAttribute" or
            "ServerRpcEvent"
            );

        if (rpcAttr == null)
            return null;

        var attributeSyntax = rpcAttr
            .ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        var args = attributeSyntax.ArgumentList!.Arguments;

        var constants = args.Select(arg => context.SemanticModel.GetOperation(arg.Expression)?.ConstantValue.Value)
            .Where(val => val is not null)
            .Select(x => x!.ToString())
            .ToArray();

        return new ServerRpcMethodInfo(methodSymbol, constants);
    }

    private static void GenerateSources(SourceProductionContext context, ImmutableArray<ServerRpcMethodInfo?> rawMethods)
    {
        var methods = rawMethods
            .Where(m => m is not null)
            .Select(m => m!)
            .OrderBy(m => m.EventName) // Deterministic order
            .ToList();

        var eventDuplicates = methods.GroupBy(x => x.EventName)
              .Where(g => g.Count() > 1)
              .SelectMany(y => y)
              .ToList();

        foreach (var duplicate in eventDuplicates)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("ERROR", "Error", "Event: {0} has a duplicate event name", "Error", DiagnosticSeverity.Error, true),
                duplicate?.Symbol?.Locations[0],
                duplicate?.EventName));
        }

        ProcessEvents(context, methods);
    }

    private static void ProcessEvents(SourceProductionContext context, List<ServerRpcMethodInfo?> methods)
    {
        var groupsByClass = methods.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default);

        byte baseEventCode = 0;

        foreach (var group in groupsByClass)
        {
            var classSymbol = group.Key;
            var ns = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var fullClassName = classSymbol.ToDisplayString();

            var sb = new StringBuilder($$"""
                                         // <auto-generated/>
                                         using System;
                                         using LiteNetLib;
                                         using LiteNetLib.Utils;
                                         using ReadyM.Api.Multiplayer;
                                         using ReadyM.Api.Multiplayer.Protocol;
                                         using ReadyM.Api.Multiplayer.Protocol.Enums;
                                         using ReadyM.Api.Multiplayer.Client;
                                         using ReadyM.Api.Multiplayer.Extensions;
                                         using ReadyM.Api.Multiplayer.Server.Rpc;
                                         using ReadyM.Relay.Common.Protocol;

                                         namespace {{ns}}
                                         {
                                             public partial class {{className}}
                                             {

                                         """);

            var dispatchCases = new StringBuilder();
            var initMethods = new StringBuilder();
            var deinitMethods = new StringBuilder();

            foreach (var method in group)
            {
                var methodSymbol = method.Symbol;
                var methodName = methodSymbol.Name;

                var eventName = method.AttributeParams.FirstOrDefault();
                if (eventName is null)
                {
                    sb.AppendLine($"""#error "EventName must be specified in ServerRpcHandler attribute for method '{methodName}'" """);
                    break;
                }
                
                var eventCode = $"(RelayMessageCode.MinServerRpcEvent + {baseEventCode})";
                var eventCodeByte = $"(byte){eventCode}";

                var parameters = methodSymbol.Parameters;

                bool valid = false;
                bool hasPayload = false;
                bool isSerializablePrimitive = false;
                bool isNetSerializable = false;
                ITypeSymbol? payloadType = null;
                string payloadParameterName = "";

                if (parameters.Length == 0)
                {
                    // void OnX()
                    valid = true;
                }
                else if (parameters.Length == 1)
                {
                    if (parameters[0].Type.AllInterfaces.Any(i => i.Name == "INetSerializable"))
                    {
                        // void OnX(T payload)
                        valid = true;
                        hasPayload = true;
                        isNetSerializable = true;
                        payloadType = parameters[0].Type;
                        payloadParameterName = parameters[0].Name;
                    }
                    else if (SerializationHelper.IsSerializablePrimitive(parameters[0].Type.SpecialType))
                    {
                        // int, string, etc.
                        valid = true;
                        hasPayload = true;
                        isSerializablePrimitive = true;
                        payloadType = parameters[0].Type;
                        payloadParameterName = parameters[0].Name;
                    }
                    else
                    {
                        valid = true;
                        hasPayload = true;
                        payloadType = parameters[0].Type; // T must be registered in RelayClient
                        payloadParameterName = parameters[0].Name;
                    }
                }

                if (!valid)
                {
                    sb.AppendLine($"""#error "Invalid server RPC handler '{methodName}'. Supported signatures: void OnX() or void OnX(T) where T is either INetSerializable, or primitive" """);
                    continue;
                }

                var shortName = methodName.StartsWith("On") ? methodName.Substring(2) : methodName;

                var sendMethod = $"Send{shortName}";
                var argList = hasPayload ? $"{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {payloadParameterName}" : "";

                sb.AppendLine($$"""
                                        public void {{sendMethod}}({{argList}})
                                        {
                                            var message = RelayMessage.ToServer({{eventCode}}, DeliveryMethod.ReliableOrdered);
                                            var writer = message.Writer;
                                            //var writer = new NetDataWriter();
                                            //writer.PutServerRpcEventHeader({{eventCode}});
                                """);

                if (hasPayload)
                {
                    if (isSerializablePrimitive)
                    {
                        sb.AppendLine($"            writer.Put({payloadParameterName});");
                    }
                    else if (isNetSerializable)
                    {
                        sb.AppendLine($"            {payloadParameterName}.Serialize(writer);");
                    }
                    else
                    {
                        sb.AppendLine($"            Serializer.SerializeObject(writer, {payloadParameterName});");
                    }
                }

                sb.AppendLine("""
                                          RelayClient.SendMessage(message);
                                      }

                              """);

                dispatchCases.AppendLine($"            case {eventCode}:\n            {{");

                if (hasPayload)
                {
                    if (isSerializablePrimitive)
                    {
                        var getMethod = SerializationHelper.GetDeserializationMethod(payloadType!.SpecialType);
                        dispatchCases.AppendLine($"                var payload = reader.{getMethod}();");
                    }
                    else if (isNetSerializable)
                    {
                        dispatchCases.AppendLine($"                var payload = new {payloadType}();");
                        dispatchCases.AppendLine("                payload.Deserialize(reader);");
                    }
                    else
                    {
                        dispatchCases.AppendLine($"                var payload = Serializer.DeserializeObject<{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(reader);");
                    }
                }

                dispatchCases.Append("                ");
                dispatchCases.Append(methodName);
                dispatchCases.Append('(');

                if (hasPayload)
                    dispatchCases.Append("payload");

                dispatchCases.AppendLine(");");
                dispatchCases.AppendLine("                break;");
                dispatchCases.AppendLine("            }");

                initMethods.AppendLine($"RelayClient.AddServerRpcMessageHandler({eventCode}, OnServerEvent);");
                deinitMethods.AppendLine($"RelayClient.RemoveServerRpcMessageHandler({eventCode}, OnServerEvent);");
                baseEventCode++;
            }

            // Emit OnServerEvent override
            sb.AppendLine($$"""
                                    protected void OnServerEvent(IRelayClientNetworkThreadContext context, ServerEventHeader header, NetDataReader reader)
                                    {
                                        switch (header.EventCode)
                                        {
                            {{dispatchCases}}
                                            default:
                                                throw new InvalidOperationException($"Unknown event code: {header.EventCode}");
                                        }
                                    }
                                    
                                    protected void InitRpc()
                                    {
                                        {{initMethods}}
                                    }
                                    
                                    protected void DeInitRpc()
                                    {
                                        {{deinitMethods}}
                                    }
                            """);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var hintName = $"{fullClassName.Replace('.', '_')}_RpcEvents.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }

    private sealed class ServerRpcMethodInfo(IMethodSymbol symbol, string[] attr)
    {
        public IMethodSymbol Symbol { get; } = symbol;
        public string[] AttributeParams { get; } = attr;
        public string EventName => AttributeParams.FirstOrDefault() ?? string.Empty;
    }
}