using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators;

namespace ReadyM.Relay.Common.Generators;

[Generator]
public class ServerRpcEventGenerator : IIncrementalGenerator
{
    private const string ContextTypeName = "IRelayClientNetworkThreadContext";
    private const string ContextParameterName = "__context";
    private const string EventCodeTypeName = "RelayMessageCode";
    private const string EventCodeParameterName = "__eventCode";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serverRpcMethods = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(m => m is not null)
            .Collect();

        context.RegisterSourceOutput(serverRpcMethods, GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken _) =>
        node is MethodDeclarationSyntax method &&
        method.AttributeLists.Count > 0;

    private static ServerRpcMethodInfo? Transform(GeneratorSyntaxContext context, CancellationToken _)
    {
        if (context.Node is not MethodDeclarationSyntax methodSyntax)
            return null;

        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol;

        var rpcAttr = methodSymbol?.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is
            "ServerRpcEventAttribute" or
            "ServerRpcEvent"
            );

        if (rpcAttr == null)
            return null;

        var attributeSyntax = rpcAttr
            .ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        var args = attributeSyntax!.ArgumentList!.Arguments;

        var constants = args.Select(arg => context.SemanticModel.GetOperation(arg.Expression)?.ConstantValue.Value)
            .Where(val => val is not null)
            .Select(x => x!.ToString())
            .ToArray();

        return new ServerRpcMethodInfo(methodSymbol!, constants);
    }

    private static void GenerateSources(SourceProductionContext context, ImmutableArray<ServerRpcMethodInfo?> rawMethods)
    {
        var methods = rawMethods
            .Where(m => m is not null)
            .Select(m => m!)
            .OrderBy(m => m.EventName) // Deterministic order
            .ToList();

        var eventDuplicates = methods.GroupBy(x => x.EventName)
              .Where(g => g.Count() > 1)
              .SelectMany(y => y)
              .ToList();

        foreach (var duplicate in eventDuplicates)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("ERROR", "Error", "Event: {0} has a duplicate event name", "Error", DiagnosticSeverity.Error, true),
                duplicate?.Symbol?.Locations[0],
                duplicate?.EventName));
        }

        ProcessEvents(context, methods);
    }

    private static void ProcessEvents(SourceProductionContext context, List<ServerRpcMethodInfo?> methods)
    {
        var groupsByClass = methods.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default);

        byte baseEventCode = 0;

        foreach (var group in groupsByClass)
        {
            var classSymbol = group.Key;
            var ns = classSymbol!.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var fullClassName = classSymbol.ToDisplayString();
            var access = classSymbol.DeclaredAccessibility.ToString().ToLower(); // public, internal, etc.

            var sb = new StringBuilder($$"""
                                         // <auto-generated/>
                                         using System;
                                         using LiteNetLib;
                                         using LiteNetLib.Utils;
                                         using ReadyM.Api.Multiplayer;
                                         using ReadyM.Api.Multiplayer.Protocol;
                                         using ReadyM.Api.Multiplayer.Protocol.Enums;
                                         using ReadyM.Api.Multiplayer.Client;
                                         using ReadyM.Api.Multiplayer.Extensions;

                                         namespace {{ns}};

                                         {{access}} partial class {{className}}
                                         {

                                         """);

            var dispatchCases = new StringBuilder();
            var initCalls = new StringBuilder();
            var deinitCalls = new StringBuilder();

            foreach (var method in group)
            {
                var methodSymbol = method.Symbol;
                var methodName = methodSymbol.Name;

                var eventName = method.AttributeParams.FirstOrDefault();
                if (eventName is null)
                {
                    sb.AppendLine($"""#error "EventName must be specified in ServerRpcHandler attribute for method '{methodName}'" """);
                    break;
                }
                
                var eventCode = $"(RelayMessageCode.MinServerRpcEvent + {baseEventCode})";
                var eventCodeByte = $"(byte){eventCode}";

                var parameters = methodSymbol.Parameters;

                bool valid = true;
                int? contextIndex = null;
                int? eventCodeIndex = null;
                List<(ITypeSymbol? Type, bool IsSerializablePrimitive, bool IsNetSerializable)> paramTypes = [];

                for (var i = 0; i < parameters.Length; i++)
                {
                    var param = parameters[i];
                    if (param.Name == ContextParameterName)
                    {
                        if (param.Type.Name != ContextTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // IRelayClientNetworkThreadContext __context
                        contextIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (param.Name == EventCodeParameterName)
                    {
                        if (param.Type.Name != EventCodeTypeName)
                        {
                            valid = false;
                            break;
                        }
                        // RelayMessageCode __eventCode
                        eventCodeIndex = i;
                        paramTypes.Add((null, false, false));
                    }
                    else if (SerializationHelper.IsINetSerializable(param.Type))
                    {
                        // T payload
                        var isNetSerializable = true;
                        var payloadType = param.Type;
                        paramTypes.Add((payloadType, false, isNetSerializable));
                    }
                    else if (SerializationHelper.IsSerializablePrimitive(param.Type.SpecialType))
                    {
                        // int, string, etc.
                        var isSerializablePrimitive = true;
                        var payloadType = param.Type;
                        paramTypes.Add((payloadType, isSerializablePrimitive, false));
                    }
                    else
                    {
                        // T payload
                        var payloadType = param.Type; // T must be registered in RelayClient
                        paramTypes.Add((payloadType, false, false));
                    }
                }

                if (!valid)
                {
                    sb.AppendLine($"""#error "Invalid server RPC handler '{methodName}'. Supported signatures: void OnX([IRelayClientNetworkThreadContext __context], [RelayMessageCode __eventCode], [T arg...]) where T is either INetSerializable, or primitive" """);
                    continue;
                }

                var shortName = methodName.StartsWith("On") ? methodName.Substring(2) : methodName;

                var sendMethod = $"Send{shortName}";
                var sendParamList = new StringBuilder();

                var payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i == eventCodeIndex)
                        continue;

                    if (i == contextIndex)
                        continue;

                    if (payloadCount > 0)
                        sendParamList.Append(", ");

                    var payloadType = paramTypes[i].Type;
                    sendParamList.Append(payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    sendParamList.Append($" payload{payloadCount}");
                    payloadCount++;
                }

                sb.AppendLine($$"""
                                    public void {{sendMethod}}({{sendParamList}})
                                    {
                                        var message = RelayMessage.ToServer({{eventCode}}, DeliveryMethod.ReliableOrdered);
                                        var writer = message.Writer;
                                """);

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    var (_, isSerializablePrimitive, isNetSerializable) = paramTypes[i];

                    if (i == eventCodeIndex)
                        continue;

                    if (i == contextIndex)
                        continue;

                    if (isSerializablePrimitive)
                    {
                        sb.AppendLine($"        writer.Put(payload{payloadCount});");
                    }
                    else if (isNetSerializable)
                    {
                        sb.AppendLine($"        payload{payloadCount}.Serialize(writer);");
                    }
                    else
                    {
                        sb.AppendLine($"        Serializer.SerializeObject(writer, payload{payloadCount});");
                    }

                    payloadCount++;
                }

                sb.AppendLine("""
                                      RelayClient.SendMessage(message);
                                  }

                              """);

                dispatchCases.AppendLine($"            case {eventCode}:\n            {{");

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    var (payloadType, isSerializablePrimitive, isNetSerializable) = paramTypes[i];

                    if (i == contextIndex || i == eventCodeIndex)
                        continue;

                    if (isSerializablePrimitive)
                    {
                        var getMethod = SerializationHelper.GetDeserializationMethod(payloadType!.SpecialType);
                        dispatchCases.AppendLine($"                var payload{payloadCount} = reader.{getMethod}();");
                    }
                    else if (isNetSerializable)
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = new {payloadType}();");
                        dispatchCases.AppendLine($"                payload{payloadCount}.Deserialize(reader);");
                    }
                    else
                    {
                        dispatchCases.AppendLine($"                var payload{payloadCount} = Serializer.DeserializeObject<{payloadType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(reader);");
                    }

                    payloadCount++;
                }

                dispatchCases.Append("                ");
                dispatchCases.Append(methodName);
                dispatchCases.Append('(');

                payloadCount = 0;
                for (var i = 0; i < paramTypes.Count; i++)
                {
                    if (i > 0)
                        dispatchCases.Append(", ");

                    if (i == eventCodeIndex)
                    {
                        dispatchCases.Append("header.EventCode");
                        continue;
                    }

                    if (i == contextIndex)
                    {
                        dispatchCases.Append("context");
                        continue;
                    }

                    dispatchCases.Append($"payload{payloadCount}");
                    payloadCount++;
                }

                dispatchCases.AppendLine(");");
                dispatchCases.AppendLine("                break;");
                dispatchCases.AppendLine("            }");

                if (initCalls.Length > 0)
                    initCalls.AppendLine();
                initCalls.Append($"        RelayClient.AddServerRpcMessageHandler({eventCode}, OnServerEvent);");
                if (deinitCalls.Length > 0)
                    deinitCalls.AppendLine();
                deinitCalls.Append($"        RelayClient.RemoveServerRpcMessageHandler({eventCode}, OnServerEvent);");
                baseEventCode++;
            }

            // Emit OnServerEvent override
            sb.AppendLine($$"""
                                protected void OnServerEvent(ServerEventHeader header, NetDataReader reader)
                                {
                                    switch (header.EventCode)
                                    {
                            {{dispatchCases}}
                                        default:
                                            throw new InvalidOperationException($"Unknown event code: {header.EventCode}");
                                    }
                                }
                                    
                                protected void InitRpc()
                                {
                            {{initCalls}}
                                }
                                    
                                protected void DeInitRpc()
                                {
                            {{deinitCalls}}
                                }
                            """);

            sb.AppendLine("}");

            var hintName = $"{fullClassName.Replace('.', '_')}_RpcEvents.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }

    private sealed class ServerRpcMethodInfo(IMethodSymbol symbol, string[] attr)
    {
        public IMethodSymbol Symbol { get; } = symbol;
        public string[] AttributeParams { get; } = attr;
        public string EventName => AttributeParams.FirstOrDefault() ?? string.Empty;
    }
}