using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ReadyM.Api.Generators;

[Generator]
internal class WrapperGenerator : IIncrementalGenerator
{
    private bool Predicate(SyntaxNode syntaxNode, CancellationToken ct)
    {
        return syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 } decl &&
               decl.Modifiers.Any(m => m.Text == "partial")
               && decl.AttributeLists
                   .SelectMany(a => a.Attributes)
                   .Any(attr => attr.Name is IdentifierNameSyntax { Identifier.Text: "WrapperFor" });
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate,
                transform: static (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax) ctx.Node;
                    var semanticModel = ctx.SemanticModel;

                    List<string> includedRegexes = [];
                    foreach (var attrList in classDecl.AttributeLists)
                    {
                        foreach (var attr in attrList.Attributes)
                        {
                            var symbolInfo = semanticModel.GetSymbolInfo(attr);
                            if (symbolInfo.Symbol is IMethodSymbol attrCtor &&
                                attrCtor.ContainingType.ToDisplayString().Contains("WrapperInclude"))
                            {
                                var argExpr = attr.ArgumentList?.Arguments.FirstOrDefault()?.Expression;
                                if (argExpr is LiteralExpressionSyntax strLiteral)
                                {
                                    var regex = strLiteral.Token.ValueText;
                                    if (!string.IsNullOrEmpty(regex))
                                    {
                                        includedRegexes.Add(regex);
                                    }
                                }
                            }
                        }
                    }

                    foreach (var attrList in classDecl.AttributeLists)
                    {
                        foreach (var attr in attrList.Attributes)
                        {
                            var symbolInfo = semanticModel.GetSymbolInfo(attr);
                            if (symbolInfo.Symbol is IMethodSymbol attrCtor &&
                                attrCtor.ContainingType.ToDisplayString().Contains("WrapperFor"))
                            {
                                var argExpr = attr.ArgumentList?.Arguments.FirstOrDefault()?.Expression;
                                if (argExpr is TypeOfExpressionSyntax typeOfExpr)
                                {
                                    var typeSymbol = semanticModel.GetTypeInfo(typeOfExpr.Type).Type;
                                    return (classDecl, typeSymbol, excludedRegexes: includedRegexes);
                                }
                            }
                        }
                    }

                    return default;
                })
            .Where(static t => t != default);

        context.RegisterSourceOutput(classDeclarations, (spc, tuple) =>
        {
            var (classDecl, wrappedType, included) = tuple;
            if (wrappedType is not INamedTypeSymbol targetType)
                return;

            var namespaceName = "ReadyM.Api.ECS.Worlds"; // TODO
            var className = classDecl.Identifier.Text;
            var access = classDecl.Modifiers.Any(m => m.Text == "public") ? "public" : "internal";
            var wrappedTypeName = targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            const string wrappedFieldName = "_wrapped";

            var sb = new StringBuilder("// <auto-generated/>\n\n");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Diagnostics.CodeAnalysis;");

            // add using for the wrapped type namespace
            if (!string.IsNullOrEmpty(targetType.ContainingNamespace.ToDisplayString()))
            {
                sb.AppendLine($"using {targetType.ContainingNamespace.ToDisplayString()};");
            }

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName};");
            }

            sb.AppendLine($"{access} partial class {className} {{");
            sb.AppendLine($"    private readonly {wrappedTypeName} {wrappedFieldName};");
            sb.AppendLine();
            
            // TODO: Generate this if not present
            // sb.AppendLine($"    internal {className}({wrappedTypeName} wrapped) : this() => {wrappedFieldName} = wrapped;");
            
            sb.AppendLine();

            var includedRegexes = included
                .Select(x => new Regex(x))
                .ToList();

            // Generate methods
            var methods = targetType.GetMembers().OfType<IMethodSymbol>()
                .Concat(targetType.BaseType?.GetMembers().OfType<IMethodSymbol>() ?? []);
            foreach (var member in methods)
            {
                if (member.DeclaredAccessibility != Accessibility.Public
                    || member.IsStatic
                    || member.MethodKind != MethodKind.Ordinary)
                    continue;

                var methodName = member.Name;

                if (!includedRegexes.Any(regex => regex.IsMatch(methodName)))
                {
                    continue; // skip excluded methods
                }

                var returnType = member.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                var genericParams = member.TypeParameters.Length > 0
                    ? $"<{string.Join(", ", member.TypeParameters.Select(tp => tp.Name))}>"
                    : string.Empty;
                var typeConstraints = "";

                // generate "where T1: constraint" clauses if any
                if (member.TypeParameters.Length > 0)
                {
                    var csb = new StringBuilder();

                    foreach (var memberTypeParameter in member.TypeParameters)
                    {
                        List<string> cs = [];
                        if (memberTypeParameter.HasReferenceTypeConstraint)
                        {
                            cs.Add("class");
                        }

                        if (memberTypeParameter.HasValueTypeConstraint)
                        {
                            cs.Add("struct");
                        }

                        if (memberTypeParameter.HasUnmanagedTypeConstraint)
                        {
                            cs.Add("unmanaged");
                        }

                        if (memberTypeParameter.HasConstructorConstraint)
                        {
                            cs.Add("new()");
                        }

                        if (memberTypeParameter.ConstraintTypes.Length > 0)
                        {
                            cs.AddRange(memberTypeParameter.ConstraintTypes
                                .Select(ct => ct.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
                        }

                        if (cs.Count > 0)
                        {
                            csb.Append($" where {memberTypeParameter.Name} : {string.Join(", ", cs)}");
                        }
                    }

                    typeConstraints = csb.ToString();
                }

                var parameters = member.Parameters
                    .Select(p => $"{GetModifier(p.RefKind)}{p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} {p.Name}")
                    .ToArray();
                var parameterList = string.Join(", ", parameters);
                var argumentList = string.Join(", ", member.Parameters.Select(p => $"{GetModifier(p.RefKind)}{p.Name}"));

                sb.AppendLine($"    [ExcludeFromCodeCoverage] public {returnType} {methodName}{genericParams}({parameterList}){typeConstraints} => {wrappedFieldName}.{methodName}{genericParams}({argumentList});");
            }

            // Generate properties
            var properties = targetType.GetMembers().OfType<IPropertySymbol>()
                .Concat(targetType.BaseType?.GetMembers().OfType<IPropertySymbol>() ?? []);
            foreach (var prop in properties)
            {
                if (prop.DeclaredAccessibility != Accessibility.Public || prop.IsStatic) continue;

                var name = prop.Name;

                if (!includedRegexes.Any(regex => regex.IsMatch(name)))
                {
                    continue; // skip excluded properties
                }

                var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                var hasGetter = prop.GetMethod != null;
                var hasSetter = prop.SetMethod != null;
                var isInitOnly = prop.SetMethod?.IsInitOnly ?? false;

                sb.Append($"   [ExcludeFromCodeCoverage] public {typeName} {name} ");
                sb.Append("{ ");
                if (hasGetter) sb.Append($"get => {wrappedFieldName}.{name}; ");
                if (hasSetter && !isInitOnly)
                {
                    // init properties not supported in netstandard2.1
                    sb.Append($"set => {wrappedFieldName}.{name} = value; ");
                }

                sb.AppendLine("}");
            }
            
            // Generate events
            var events = targetType.GetMembers().OfType<IEventSymbol>()
                .Concat(targetType.BaseType?.GetMembers().OfType<IEventSymbol>() ?? []);
            foreach (var evt in events)
            {
                if (evt.DeclaredAccessibility != Accessibility.Public || evt.IsStatic) continue;

                var name = evt.Name;

                if (!includedRegexes.Any(regex => regex.IsMatch(name)))
                {
                    continue; // skip excluded events
                }

                var typeName = evt.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                sb.AppendLine($"   [ExcludeFromCodeCoverage] public event {typeName} {name} {{ add => {wrappedFieldName}.{name} += value; remove => {wrappedFieldName}.{name} -= value; }}");
            }

            sb.AppendLine("}"); // class

            var hintName = $"{className}.g.cs";
            spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static string GetModifier(RefKind refKind) => refKind switch
    {
        RefKind.Out => "out ",
        RefKind.Ref => "ref ",
        RefKind.In => "in ",
        _ => ""
    };
}