using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Archetypes;

namespace ReadyM.Api.Generators.Mods;

/// Completes a <c>[ModConfig]</c> class: the registration that tells the SDK which file to fill it
/// from, so it is read out of the mod's own folder before anything asks for it.
[Generator]
internal class ModConfigGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var configs = context.SyntaxProvider.ForAttributeWithMetadataName(
                ArchetypeNames.ModConfigAttribute,
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                static (syntax, _) => (Symbol: syntax.TargetSymbol as INamedTypeSymbol, syntax.SemanticModel.Compilation))
            .Select(static (found, ct) => Emit(found.Symbol, found.Compilation, ct));

        context.RegisterSourceOutput(configs, static (spc, generated) =>
        {
            if (generated is { } source)
                spc.AddSource(source.HintName, source.Source);
        });
    }

    private static (string HintName, string Source)? Emit(
        INamedTypeSymbol? symbol,
        Compilation compilation,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (symbol is null)
            return null;

        var read = ModConfigShape.Read(symbol);

        if (read.Problems.Any(problem => problem.Severity == DiagnosticSeverity.Error))
            return null;

        var name = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        var ns = ArchetypeNames.NamespaceOf(symbol);

        if (ns.Length > 0)
        {
            writer.Line($"namespace {ns};");
            writer.Line();
        }

        using (writer.Braces($"partial class {symbol.Name}"))
        {
            writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

            using (writer.Braces("public static class Registration"))
            {
                writer.Line("private static bool _registered;");
                writer.Line();

                if (ExtendsEmitter.HasModuleInitializer(compilation))
                    writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");

                using (writer.Braces("public static void Register()"))
                {
                    using (writer.Braces("if (_registered)"))
                        writer.Line("return;");

                    writer.Line();
                    writer.Line("_registered = true;");
                    writer.Line();
                    writer.Line(
                        $"{ArchetypeNames.ModConfigRegistry}.Declare<{name}>({Literal(read.FileName)});");
                }
            }
        }

        return (ArchetypeNames.HintOf(symbol, "ModConfig"), writer.ToString());
    }

    private static string Literal(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
