using System.Threading;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Archetypes;

namespace ReadyM.Api.Generators.Mods;

/// Completes a <c>[ModEntry]</c> class: the folder the mod was loaded from, the start the loader
/// calls, and the registration that tells the loader this assembly is a mod at all.
[Generator]
internal class ModEntryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entries = context.SyntaxProvider.ForAttributeWithMetadataName(
                ArchetypeNames.ModEntryAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntax, _) => (Symbol: syntax.TargetSymbol as INamedTypeSymbol, syntax.SemanticModel.Compilation))
            .Select(static (found, ct) => Emit(found.Symbol, found.Compilation, ct));

        context.RegisterSourceOutput(entries, static (spc, generated) =>
        {
            if (generated is { } source)
                spc.AddSource(source.HintName, source.Source);
        });
    }

    private static (string HintName, string Source)? Emit(
        INamedTypeSymbol? symbol,
        Compilation compilation,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (symbol is null)
            return null;

        var read = ModEntryShape.Read(symbol);

        if (read.Problems.Any(problem => problem.Severity == DiagnosticSeverity.Error))
            return null;

        var name = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        var ns = ArchetypeNames.NamespaceOf(symbol);

        if (ns.Length > 0)
        {
            writer.Line($"namespace {ns};");
            writer.Line();
        }

        using (writer.Braces($"partial class {symbol.Name} : {ArchetypeNames.ModEntry}"))
        {
            writer.Line("/// This mod's own folder, which holds its assemblies, manifest and any files it ships.");
            writer.Line("/// <remarks>Pushed in after the constructor runs, so it reads as empty in one.</remarks>");
            writer.Line("public string ModDirectory { get; private set; } = string.Empty;");
            writer.Line();

            writer.Line($"void {ArchetypeNames.ModEntry}.SetModDirectory(string directory)");
            writer.Line("    => ModDirectory = directory;");
            writer.Line();

            if (read.Start is null)
            {
                using (writer.Braces($"void {ArchetypeNames.ModEntry}.Start()"))
                {
                }
            }
            else
            {
                writer.Line($"void {ArchetypeNames.ModEntry}.Start()");
                writer.Line($"    => {ModEntryShape.StartName}();");
            }

            writer.Line();
            writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

            using (writer.Braces("public static class Registration"))
            {
                // A module initializer runs this where the target has one, and the mod loader runs
                // it for every assembly it loads.
                writer.Line("private static bool _registered;");
                writer.Line();

                if (ExtendsEmitter.HasModuleInitializer(compilation))
                    writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");

                using (writer.Braces("public static void Register()"))
                {
                    using (writer.Braces("if (_registered)"))
                        writer.Line("return;");

                    writer.Line();
                    writer.Line("_registered = true;");
                    writer.Line();
                    writer.Line($"{ArchetypeNames.ModEntryRegistry}.Declare<{name}>();");
                }
            }
        }

        return (ArchetypeNames.HintOf(symbol, "ModEntry"), writer.ToString());
    }
}
