namespace ReadyM.Api.Mapping.Events;

/// <summary>
/// A game event's policy: three questions the mapped event manager asks the event itself. Generated by
/// <see cref="DeriveIGameEventAttribute"/> from the event's discriminator attribute, or written by hand.
/// </summary>
public interface IGameEvent
{
    /// <summary>The game raised it on this machine: should the ECS be told?</summary>
    GameEventNotifyResult CanGameEventNotifyEcs(GameEventContextRegistry contexts);

    /// <summary>The game raised it on this machine: may the game code behind it run here?</summary>
    GameEventResult CanGameEventRunLocally(GameEventContextRegistry contexts);

    /// <summary>It arrived through the ECS: should the game play it on this machine?</summary>
    GameEventResult CanEcsInvokeGameEvent(GameEventContextRegistry contexts);
}
