<?xml version="1.0" encoding="utf-8"?>

<Project>
    <PropertyGroup>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!-- silence CS1591 warning for missing XML comments -->
        <NoWarn>$(NoWarn);1591</NoWarn>
        <!-- Do not create additional runtime-specific output directories -->
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'DebugProduction'">
        <DefineConstants>$(DefineConstants);DEBUG;PRODUCTION_MASTER_SERVER</DefineConstants>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <OutputPath>bin\DebugProduction\</OutputPath>
        <DebugSymbols>true</DebugSymbols>
        <IntermediateOutputPath>obj\DebugProduction\</IntermediateOutputPath>
        <StripSymbols>false</StripSymbols>       <!-- keeps the .pdb (Windows) / .dbg (Linux) -->
        <NativeDebugSymbols>true</NativeDebugSymbols>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Testing'">
        <DefineConstants>$(DefineConstants);DEBUG;TESTING</DefineConstants>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <OutputPath>bin\Testing\</OutputPath>
        <DebugSymbols>true</DebugSymbols>
        <IntermediateOutputPath>obj\Testing\</IntermediateOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DefineConstants>$(DefineConstants)</DefineConstants>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Aot)' == 'true'">
        <DefineConstants>$(DefineConstants);NATIVE_AOT</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Agones)' == 'true'">
        <DefineConstants>$(DefineConstants);AGONES</DefineConstants>
    </PropertyGroup>
</Project>
