using System.Reflection;
using Friflo.Engine.ECS;
using ReadyM.SDK.Archetypes;
using ReadyM.SDK.Chunks;
using ReadyM.SDK.Entity;
using ReadyM.SDK.Tests.Server.Fixtures;
using Position = ReadyM.SDK.Tests.Server.Fixtures.Position;

namespace ReadyM.SDK.Tests.Server;

/// <summary>
/// That the interfaces generated code implements cannot gain a member without someone deciding to.
/// </summary>
/// <remarks>
/// A mod carries its generated code and keeps running against later SDKs, so a member added to one
/// of these interfaces stops every already-compiled mod from loading. The two halves can be held to
/// that differently. The server-only interfaces target net10.0 and can give a new member a body, so
/// a type that predates it still satisfies them, and BareView below is the proof. The shared ones
/// also target netstandard2.0, which has no default implementations at all, so nothing can soften an
/// addition there and the member list is pinned instead.
/// </remarks>
public class InterfaceExtensibilityTests : ServerSdkTest
{
    // -- the shared interfaces: pinned, because netstandard2.0 allows no default bodies -----------

    /// <summary>
    /// The one thing an archetype, a mixin and a chunk view all are. It is what Delete takes, so it
    /// has to stay this small: a member added here cannot be given a body on netstandard2.0, and
    /// every already-compiled shape would stop satisfying it.
    /// </summary>
    [Fact]
    public void IEntityShape_has_not_gained_members()
        => AssertMembers(typeof(IEntityShape), "Handle", "get_Handle");

    [Fact]
    public void IArchetypeQueryable_has_not_gained_members()
        => AssertMembers(typeof(IArchetypeQueryable),
            "Handle", "get_Handle", "set_Handle",
            "Components", "get_Components");

    /// <summary>A marker, and it has to stay one: nothing here can be given a body.</summary>
    [Fact]
    public void IArchetype_has_not_gained_members()
        => AssertMembers(typeof(IArchetype));

    [Fact]
    public void IArchetypeMixin_has_not_gained_members()
        => AssertMembers(typeof(IArchetypeMixin));

    private static void AssertMembers(Type type, params string[] expected)
    {
        var actual = type
            .GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Select(member => member.Name)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        Assert.Equal(expected.OrderBy(name => name, StringComparer.Ordinal).ToArray(), actual);
    }

    /// <summary>
    /// What the markers buy: a shape can now satisfy IArchetype by carrying only its state, so an
    /// SDK that adds behaviour elsewhere leaves an already-compiled mod alone. Before the shrink
    /// this type could not exist without implementing five members.
    /// </summary>
    private readonly struct BareArchetype : IArchetype
    {
        public EntityHandle Handle { get; init; }

        public ComponentSet Components => PositionAccessors.Components;
    }

    private static bool ValidOf<T>(T shape) where T : struct, IArchetypeQueryable => shape.IsValid();

    [Fact]
    public void An_archetype_carrying_only_its_state_satisfies_the_interface()
    {
        var npc = Spawn<Npc>();
        var bare = new BareArchetype { Handle = EntityHandle.Of(npc) };

        Assert.True(ValidOf(bare));
        Assert.True(bare.Handle.Is<Position>());
        Assert.False(bare.Handle.Is<QuestGiver>());
    }

    /// An author still calls the member the generator emits, which wins over the extension.
    [Fact]
    public void A_generated_archetype_keeps_its_own_members()
    {
        var npc = Spawn<Npc>();

        Assert.True(npc.IsValid);
        Assert.True(npc.Is<Position>());
        Assert.False(npc.TryAs<Placed>(out _));
        Assert.True(npc.TryAs<Npc>(out _));
    }

    // -- the server interface: a member may be added, provided it has a body ----------------------

    /// <summary>
    /// Stands in for a view generated by an older SDK: it implements what a chunk view must, and
    /// leaves SlotCount to the interface. If this stops compiling, a member was added that an
    /// already-compiled mod cannot satisfy.
    /// </summary>
    private readonly ref struct BareView : IArchetypeChunkView<BareView>
    {
        private readonly ComponentChunk _position;
        private readonly int _index;

        private BareView(ComponentChunk position, int index)
        {
            _position = position;
            _index = index;
        }

        public BareView At(int index) => new(_position, index);

        // Not declared as implementing IEntityShape, because a view generated before that interface
        // existed did not know about it. Every generated view has always had this property, so the
        // runtime matches it to the new member implicitly and such a view still loads.
        public EntityHandle Handle => default;

        public static ComponentSet Components => PositionAccessors.Components;

        public static BareView Bind(
            ReadOnlySpan<ChunkSlot> slots,
            ReadOnlySpan<RawEntity> entities,
            EntityHandle prototype)
            => new(new ComponentChunk(slots[0]), 0);

        public float X => PositionAccessors.GetX(_position, _index);
    }

    private static int SlotsOf<TView>() where TView : IArchetypeChunkView<TView>, allows ref struct
        => TView.SlotCount;

    [Fact]
    public void A_chunk_view_that_does_not_state_its_slot_count_gets_it_from_its_components()
    {
        Assert.Equal(1, SlotsOf<BareView>());
        Assert.Equal(PositionAccessors.Components.Count, SlotsOf<BareView>());
    }

    /// The default is not just compilable: a query driven by such a view reads the right values.
    [Fact]
    public void A_query_over_a_view_without_a_slot_count_reads_correctly()
    {
        Spawn<Npc>().X = 3f;
        Spawn<Boulder>().X = 4f;

        var total = 0f;
        var enumerator = Entities.Query<Position>().Chunks<BareView>();

        while (enumerator.MoveNext())
            total += enumerator.Current.X;

        enumerator.Dispose();

        Assert.Equal(7f, total);
    }
}
