using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ReadyM.Api.Generators.Archetypes;

namespace ReadyM.Api.Generators.Commands;

/// Completes a class that declares [Command] methods: it implements the provider interface and registers each
/// one, writing the call its author could have written by hand.
[Generator]
internal class CommandGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider.ForAttributeWithMetadataName(
                ArchetypeNames.CommandAttribute,
                static (node, _) => node is MethodDeclarationSyntax,
                static (syntax, _) => (Symbol: syntax.TargetSymbol as IMethodSymbol, syntax.SemanticModel.Compilation))
            .Collect();

        context.RegisterSourceOutput(methods, static (spc, found) => Emit(spc, found));
    }

    private static void Emit(
        SourceProductionContext spc,
        IEnumerable<(IMethodSymbol? Symbol, Compilation Compilation)> found)
    {
        var compilation = found.Select(pair => pair.Compilation).FirstOrDefault();

        var byType = found
            .Select(pair => pair.Symbol)
            .Where(method => method is not null)
            .Select(method => method!)
            .GroupBy(method => method.ContainingType, SymbolEqualityComparer.Default);

        foreach (var group in byType)
        {
            if (group.Key is not INamedTypeSymbol type) continue;

            var commands = group
                .Select(method => CommandShape.Read(method, spc))
                .Where(shape => shape is not null)
                .Select(shape => shape!.Value)
                .OrderBy(shape => shape.Name, System.StringComparer.Ordinal)
                .ToList();

            if (commands.Count == 0) continue;

            spc.AddSource(
                $"{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "")}.Commands.g.cs",
                Write(type, commands, compilation));
        }
    }

    private static string Write(INamedTypeSymbol type, IReadOnlyList<CommandShape> commands, Compilation? compilation)
    {
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        var ns = ArchetypeNames.NamespaceOf(type);

        if (ns.Length > 0)
        {
            writer.Line($"namespace {ns};");
            writer.Line();
        }

        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        using (writer.Braces($"partial class {type.Name} : {ArchetypeNames.CommandProvider}"))
        {
            using (writer.Braces(
                       $"void {ArchetypeNames.CommandProvider}.RegisterCommands({ArchetypeNames.CommandRegistry} registry)"))
            {
                foreach (var command in commands)
                {
                    writer.Line(
                        $"registry.Add({Quote(command.Name)}, {command.Method}, "
                        + $"{Quote(command.Usage)}, {(command.Permission is null ? "null" : Quote(command.Permission))});");
                }
            }

            writer.Line();
            writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");

            using (writer.Braces("public static class CommandRegistration"))
            {
                writer.Line("private static bool _registered;");
                writer.Line();

                if (compilation is not null && ExtendsEmitter.HasModuleInitializer(compilation))
                    writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");

                using (writer.Braces("public static void Register()"))
                {
                    using (writer.Braces("if (_registered)"))
                        writer.Line("return;");

                    writer.Line();
                    writer.Line("_registered = true;");
                    writer.Line($"{ArchetypeNames.CommandProvidersRegistry}.Hold<{name}>();");
                }
            }
        }

        return writer.ToString();
    }

    private static string Quote(string text) => "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
